
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hp
 */
public class Account extends javax.swing.JFrame {

    /**
     * Creates new form Account
     */
    String accountNumber;
    public Account(String accountNumber) throws SQLException {
        this.accountNumber=accountNumber;
        initComponents();
        Conn c=new Conn();
        
        accountLabel.setText(accountLabel.getText()+accountNumber);
        String query="select * from balance where accountNumber = '"+accountNumber+"'";
        ResultSet rs = c.s.executeQuery(query);

        int balance=0;
        int count=0;
            

        while(rs.next())
        {
            if(rs.getString("type").equals("Deposit"))
            {
                balance+=Integer.parseInt(rs.getString("amount"));
            }else{
                    balance-=Integer.parseInt(rs.getString("amount"));
            }count++;
        }
        System.out.println(balance);
        takaLabel.setText(takaLabel.getText()+balance);
        
        if(count>=0)
        {
            accountNumberLabel1.setText(accountNumberLabel1.getText()+accountNumber);
            
            String query1="select * from addApplication3 where accountNumber = '"+accountNumber+"'";
            ResultSet rs1 = c.s.executeQuery(query1);
            if(rs1.next())
            {
                String type=rs1.getString("accountType");
                accountTypeLabel1.setText(accountTypeLabel1.getText()+type);

                String debit=rs1.getString("debitCardNumber");
                debitCardNumberLabel1.setText(debitCardNumberLabel1.getText()+debit);

                String credit=rs1.getString("creditCardNumber");
                creditCardNumberLabel1.setText(creditCardNumberLabel1.getText()+credit);
                count++;
            }
        }
   
        
        if(count>=0)
        {
            String query1="select * from addApplication2_1 where accountNumber = '"+accountNumber+"'";
            ResultSet rs1 = c.s.executeQuery(query1);
            if(rs1.next())
            {
                
                String address=rs1.getString("presentAddress");
                customerAddressLabel1.setText(customerAddressLabel1.getText()+address);
            }
                
            
            
        }
        if(count>=0)
        {
            String query1="select * from addApplication1 where accountNumber = '"+accountNumber+"'";
                
            ResultSet rs1 = c.s.executeQuery(query1);
            if(rs1.next())
            {
                String fName=rs1.getString("firstName");
                String LName=rs1.getString("lastName");
                customerNameLabel1.setText(customerNameLabel1.getText()+fName+" "+LName);
            }
            
        }
        /*if(count>=0)
        {
            
            
        }*/
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        backgroundPanel = new javax.swing.JPanel();
        sideBarPanel = new javax.swing.JPanel();
        homeBtnPanel = new javax.swing.JPanel();
        homeBtnLabel = new javax.swing.JLabel();
        transferBtnPanel = new javax.swing.JPanel();
        transferBtnLabel = new javax.swing.JLabel();
        accountBtnPanel = new javax.swing.JPanel();
        accountBtnLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cardsBtnPanel = new javax.swing.JPanel();
        cardsBtnLabel = new javax.swing.JLabel();
        profileBtnPanel = new javax.swing.JPanel();
        profileBtnLabel = new javax.swing.JLabel();
        logoutBtnPanel = new javax.swing.JPanel();
        logoutBtnLabel = new javax.swing.JLabel();
        passBookPanel = new javax.swing.JPanel();
        logoLabel = new javax.swing.JLabel();
        customerAddressLabel = new javax.swing.JLabel();
        customerAddressLabel1 = new javax.swing.JLabel();
        accountTypeLabel = new javax.swing.JLabel();
        accountNumberLabel = new javax.swing.JLabel();
        debitCardNumberLabel = new javax.swing.JLabel();
        creditCardNumberLabel = new javax.swing.JLabel();
        accountStatusLabel = new javax.swing.JLabel();
        accountStatusLabel1 = new javax.swing.JLabel();
        accountTypeLabel1 = new javax.swing.JLabel();
        accountNumberLabel1 = new javax.swing.JLabel();
        debitCardNumberLabel1 = new javax.swing.JLabel();
        creditCardNumberLabel1 = new javax.swing.JLabel();
        customerNameLabel = new javax.swing.JLabel();
        customerNameLabel1 = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        addressLabel1 = new javax.swing.JLabel();
        addressLabel2 = new javax.swing.JLabel();
        phoneNumberLabel = new javax.swing.JLabel();
        phoneNumberLabel1 = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        emailLabel1 = new javax.swing.JLabel();
        passBookLabel = new javax.swing.JLabel();
        SKYBANKLabel = new javax.swing.JLabel();
        headingLabel1 = new javax.swing.JLabel();
        balancepanel1 = new javax.swing.JPanel();
        skyBankLabel = new javax.swing.JLabel();
        availableBalanceLabel = new javax.swing.JLabel();
        accountLabel = new javax.swing.JLabel();
        takaLabel = new javax.swing.JLabel();
        balanceLabel1 = new javax.swing.JLabel();
        closeBtnLabel = new javax.swing.JLabel();
        messageLabel = new javax.swing.JLabel();
        SKYBANKLabel2 = new javax.swing.JLabel();
        SKYBANKLabel3 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        backgroundPanel.setBackground(new java.awt.Color(255, 255, 255));
        backgroundPanel.setPreferredSize(new java.awt.Dimension(1120, 630));
        backgroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sideBarPanel.setBackground(new java.awt.Color(0, 51, 255));

        homeBtnPanel.setBackground(new java.awt.Color(0, 0, 255));
        homeBtnPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeBtnPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeBtnPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeBtnPanelMouseExited(evt);
            }
        });

        homeBtnLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        homeBtnLabel.setForeground(new java.awt.Color(255, 255, 255));
        homeBtnLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homeBtnLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/white-home.png"))); // NOI18N
        homeBtnLabel.setText(" Home");

        javax.swing.GroupLayout homeBtnPanelLayout = new javax.swing.GroupLayout(homeBtnPanel);
        homeBtnPanel.setLayout(homeBtnPanelLayout);
        homeBtnPanelLayout.setHorizontalGroup(
            homeBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeBtnPanelLayout.createSequentialGroup()
                .addComponent(homeBtnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        homeBtnPanelLayout.setVerticalGroup(
            homeBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homeBtnPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homeBtnLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addContainerGap())
        );

        transferBtnPanel.setBackground(new java.awt.Color(0, 0, 255));
        transferBtnPanel.setPreferredSize(new java.awt.Dimension(118, 65));
        transferBtnPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transferBtnPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                transferBtnPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                transferBtnPanelMouseExited(evt);
            }
        });

        transferBtnLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        transferBtnLabel.setForeground(new java.awt.Color(255, 255, 255));
        transferBtnLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        transferBtnLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/transfer-icon.png"))); // NOI18N
        transferBtnLabel.setText(" Transfer");

        javax.swing.GroupLayout transferBtnPanelLayout = new javax.swing.GroupLayout(transferBtnPanel);
        transferBtnPanel.setLayout(transferBtnPanelLayout);
        transferBtnPanelLayout.setHorizontalGroup(
            transferBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(transferBtnLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        transferBtnPanelLayout.setVerticalGroup(
            transferBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transferBtnPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(transferBtnLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addContainerGap())
        );

        accountBtnPanel.setBackground(new java.awt.Color(0, 0, 255));
        accountBtnPanel.setPreferredSize(new java.awt.Dimension(118, 65));
        accountBtnPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accountBtnPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                accountBtnPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                accountBtnPanelMouseExited(evt);
            }
        });

        accountBtnLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        accountBtnLabel.setForeground(new java.awt.Color(255, 255, 255));
        accountBtnLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        accountBtnLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/white-moneybag.png"))); // NOI18N
        accountBtnLabel.setText(" Account");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/white-indicate.png"))); // NOI18N

        javax.swing.GroupLayout accountBtnPanelLayout = new javax.swing.GroupLayout(accountBtnPanel);
        accountBtnPanel.setLayout(accountBtnPanelLayout);
        accountBtnPanelLayout.setHorizontalGroup(
            accountBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountBtnPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(accountBtnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        accountBtnPanelLayout.setVerticalGroup(
            accountBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
            .addGroup(accountBtnPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(accountBtnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cardsBtnPanel.setBackground(new java.awt.Color(0, 0, 255));
        cardsBtnPanel.setPreferredSize(new java.awt.Dimension(118, 65));
        cardsBtnPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cardsBtnPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cardsBtnPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cardsBtnPanelMouseExited(evt);
            }
        });

        cardsBtnLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        cardsBtnLabel.setForeground(new java.awt.Color(255, 255, 255));
        cardsBtnLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cardsBtnLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/white-card.png"))); // NOI18N
        cardsBtnLabel.setText(" Cards");

        javax.swing.GroupLayout cardsBtnPanelLayout = new javax.swing.GroupLayout(cardsBtnPanel);
        cardsBtnPanel.setLayout(cardsBtnPanelLayout);
        cardsBtnPanelLayout.setHorizontalGroup(
            cardsBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardsBtnPanelLayout.createSequentialGroup()
                .addComponent(cardsBtnLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        cardsBtnPanelLayout.setVerticalGroup(
            cardsBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardsBtnPanelLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(cardsBtnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        profileBtnPanel.setBackground(new java.awt.Color(0, 0, 255));
        profileBtnPanel.setPreferredSize(new java.awt.Dimension(118, 65));
        profileBtnPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileBtnPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                profileBtnPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                profileBtnPanelMouseExited(evt);
            }
        });

        profileBtnLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        profileBtnLabel.setForeground(new java.awt.Color(255, 255, 255));
        profileBtnLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        profileBtnLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/white-user-icon.png"))); // NOI18N
        profileBtnLabel.setText(" Profile");

        javax.swing.GroupLayout profileBtnPanelLayout = new javax.swing.GroupLayout(profileBtnPanel);
        profileBtnPanel.setLayout(profileBtnPanelLayout);
        profileBtnPanelLayout.setHorizontalGroup(
            profileBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profileBtnPanelLayout.createSequentialGroup()
                .addComponent(profileBtnLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        profileBtnPanelLayout.setVerticalGroup(
            profileBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profileBtnPanelLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(profileBtnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        logoutBtnPanel.setBackground(new java.awt.Color(0, 0, 255));
        logoutBtnPanel.setPreferredSize(new java.awt.Dimension(118, 65));
        logoutBtnPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutBtnPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutBtnPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutBtnPanelMouseExited(evt);
            }
        });

        logoutBtnLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        logoutBtnLabel.setForeground(new java.awt.Color(255, 255, 255));
        logoutBtnLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoutBtnLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/white-logout-logo.png"))); // NOI18N
        logoutBtnLabel.setText(" Logout");

        javax.swing.GroupLayout logoutBtnPanelLayout = new javax.swing.GroupLayout(logoutBtnPanel);
        logoutBtnPanel.setLayout(logoutBtnPanelLayout);
        logoutBtnPanelLayout.setHorizontalGroup(
            logoutBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoutBtnPanelLayout.createSequentialGroup()
                .addComponent(logoutBtnLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        logoutBtnPanelLayout.setVerticalGroup(
            logoutBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoutBtnPanelLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(logoutBtnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout sideBarPanelLayout = new javax.swing.GroupLayout(sideBarPanel);
        sideBarPanel.setLayout(sideBarPanelLayout);
        sideBarPanelLayout.setHorizontalGroup(
            sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homeBtnPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(transferBtnPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
            .addComponent(accountBtnPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
            .addComponent(cardsBtnPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
            .addComponent(profileBtnPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
            .addComponent(logoutBtnPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        sideBarPanelLayout.setVerticalGroup(
            sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarPanelLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(homeBtnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(transferBtnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(accountBtnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(cardsBtnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(profileBtnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(logoutBtnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        backgroundPanel.add(sideBarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -7, -1, 640));

        passBookPanel.setBackground(new java.awt.Color(255, 255, 255));
        passBookPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        passBookPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/banklogo-sm.png"))); // NOI18N
        passBookPanel.add(logoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 14, -1, -1));

        customerAddressLabel.setBackground(new java.awt.Color(255, 255, 255));
        customerAddressLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        customerAddressLabel.setText("Customer Address :");
        passBookPanel.add(customerAddressLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 130, -1));

        customerAddressLabel1.setBackground(new java.awt.Color(255, 255, 255));
        customerAddressLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        customerAddressLabel1.setForeground(new java.awt.Color(0, 153, 255));
        passBookPanel.add(customerAddressLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 340, 20));

        accountTypeLabel.setBackground(new java.awt.Color(255, 255, 255));
        accountTypeLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        accountTypeLabel.setText("Account Type :");
        passBookPanel.add(accountTypeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 110, -1));

        accountNumberLabel.setBackground(new java.awt.Color(255, 255, 255));
        accountNumberLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        accountNumberLabel.setText("Account Number :");
        passBookPanel.add(accountNumberLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 120, -1));

        debitCardNumberLabel.setBackground(new java.awt.Color(255, 255, 255));
        debitCardNumberLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        debitCardNumberLabel.setText("Debit Card Number :");
        passBookPanel.add(debitCardNumberLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 140, -1));

        creditCardNumberLabel.setBackground(new java.awt.Color(255, 255, 255));
        creditCardNumberLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        creditCardNumberLabel.setText("Credit Card Number :");
        passBookPanel.add(creditCardNumberLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 140, -1));

        accountStatusLabel.setBackground(new java.awt.Color(255, 255, 255));
        accountStatusLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        accountStatusLabel.setText("Account Status :");
        passBookPanel.add(accountStatusLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 110, -1));

        accountStatusLabel1.setBackground(new java.awt.Color(255, 255, 255));
        accountStatusLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        accountStatusLabel1.setForeground(new java.awt.Color(0, 153, 255));
        accountStatusLabel1.setText("Active");
        passBookPanel.add(accountStatusLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 260, -1));

        accountTypeLabel1.setBackground(new java.awt.Color(255, 255, 255));
        accountTypeLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        accountTypeLabel1.setForeground(new java.awt.Color(0, 153, 255));
        passBookPanel.add(accountTypeLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 270, 20));

        accountNumberLabel1.setBackground(new java.awt.Color(255, 255, 255));
        accountNumberLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        accountNumberLabel1.setForeground(new java.awt.Color(0, 153, 255));
        passBookPanel.add(accountNumberLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 270, 20));

        debitCardNumberLabel1.setBackground(new java.awt.Color(255, 255, 255));
        debitCardNumberLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        debitCardNumberLabel1.setForeground(new java.awt.Color(0, 153, 255));
        passBookPanel.add(debitCardNumberLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 270, 20));

        creditCardNumberLabel1.setBackground(new java.awt.Color(255, 255, 255));
        creditCardNumberLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        creditCardNumberLabel1.setForeground(new java.awt.Color(0, 153, 255));
        passBookPanel.add(creditCardNumberLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 270, 20));

        customerNameLabel.setBackground(new java.awt.Color(255, 255, 255));
        customerNameLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        customerNameLabel.setText("Customer Name :");
        passBookPanel.add(customerNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 120, -1));

        customerNameLabel1.setBackground(new java.awt.Color(255, 255, 255));
        customerNameLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        customerNameLabel1.setForeground(new java.awt.Color(0, 153, 255));
        passBookPanel.add(customerNameLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 270, 20));

        addressLabel.setBackground(new java.awt.Color(255, 255, 255));
        addressLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        addressLabel.setText("Address :");
        passBookPanel.add(addressLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, 110, -1));

        addressLabel1.setBackground(new java.awt.Color(255, 255, 255));
        addressLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        addressLabel1.setForeground(new java.awt.Color(0, 153, 255));
        addressLabel1.setText("Nayapaltan,");
        passBookPanel.add(addressLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 110, 170, -1));

        addressLabel2.setBackground(new java.awt.Color(255, 255, 255));
        addressLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        addressLabel2.setForeground(new java.awt.Color(0, 153, 255));
        addressLabel2.setText("Dhaka-1000");
        passBookPanel.add(addressLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 140, 170, -1));

        phoneNumberLabel.setBackground(new java.awt.Color(255, 255, 255));
        phoneNumberLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        phoneNumberLabel.setText("Phone Number :");
        passBookPanel.add(phoneNumberLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 170, 120, -1));

        phoneNumberLabel1.setBackground(new java.awt.Color(255, 255, 255));
        phoneNumberLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        phoneNumberLabel1.setForeground(new java.awt.Color(0, 153, 255));
        phoneNumberLabel1.setText("78965432123");
        passBookPanel.add(phoneNumberLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 170, 170, -1));

        emailLabel.setBackground(new java.awt.Color(255, 255, 255));
        emailLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        emailLabel.setText("Email :");
        passBookPanel.add(emailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, 140, -1));

        emailLabel1.setBackground(new java.awt.Color(255, 255, 255));
        emailLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        emailLabel1.setForeground(new java.awt.Color(0, 153, 255));
        emailLabel1.setText("skybank.co.in");
        passBookPanel.add(emailLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 200, 180, -1));

        passBookLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        passBookLabel.setForeground(new java.awt.Color(0, 153, 255));
        passBookLabel.setText("Pass Book");
        passBookPanel.add(passBookLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));

        SKYBANKLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        SKYBANKLabel.setForeground(new java.awt.Color(0, 153, 255));
        SKYBANKLabel.setText("Sky Bank");
        passBookPanel.add(SKYBANKLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 30, -1, -1));

        backgroundPanel.add(passBookPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 73, 901, 336));

        headingLabel1.setBackground(new java.awt.Color(0, 0, 0));
        headingLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 3, 36)); // NOI18N
        headingLabel1.setForeground(new java.awt.Color(0, 51, 255));
        headingLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headingLabel1.setText("ACCOUNT");
        backgroundPanel.add(headingLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 13, 963, -1));

        balancepanel1.setBackground(new java.awt.Color(255, 255, 255));
        balancepanel1.setForeground(new java.awt.Color(255, 255, 255));
        balancepanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        skyBankLabel.setBackground(new java.awt.Color(255, 255, 255));
        skyBankLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        skyBankLabel.setForeground(new java.awt.Color(255, 255, 255));
        skyBankLabel.setText("Sky Bank");
        balancepanel1.add(skyBankLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, -1, -1));

        availableBalanceLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        availableBalanceLabel.setForeground(new java.awt.Color(255, 255, 255));
        availableBalanceLabel.setText("Available Balance");
        balancepanel1.add(availableBalanceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        accountLabel.setBackground(new java.awt.Color(255, 255, 255));
        accountLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        accountLabel.setForeground(new java.awt.Color(255, 255, 255));
        accountLabel.setText("Account #   ");
        balancepanel1.add(accountLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 250, -1));

        takaLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        takaLabel.setForeground(new java.awt.Color(255, 255, 255));
        takaLabel.setText("Taka   ");
        balancepanel1.add(takaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 250, -1));

        balanceLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/card-sky-blue.png"))); // NOI18N
        balancepanel1.add(balanceLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, -1));

        backgroundPanel.add(balancepanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 416, -1, 191));

        closeBtnLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/close-btn.png"))); // NOI18N
        closeBtnLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBtnLabelMouseClicked(evt);
            }
        });
        backgroundPanel.add(closeBtnLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 10, -1, -1));

        messageLabel.setBackground(new java.awt.Color(255, 255, 255));
        messageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/verified-mail.png"))); // NOI18N
        messageLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        messageLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                messageLabelMouseClicked(evt);
            }
        });
        backgroundPanel.add(messageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 470, -1, -1));

        SKYBANKLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        SKYBANKLabel2.setForeground(new java.awt.Color(0, 153, 255));
        SKYBANKLabel2.setText("Chat with Sky Bank");
        backgroundPanel.add(SKYBANKLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 570, -1, -1));

        SKYBANKLabel3.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        SKYBANKLabel3.setForeground(new java.awt.Color(0, 153, 255));
        SKYBANKLabel3.setText("For Any Query Click Below");
        backgroundPanel.add(SKYBANKLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 450, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 633, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void homeBtnPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBtnPanelMouseClicked
        Home H;
        try {
            H = new Home(accountNumber);
            setVisible(false);
            H.setVisible(true);
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(Account.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_homeBtnPanelMouseClicked

    private void homeBtnPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBtnPanelMouseEntered
        JPanel btn= homeBtnPanel;
        isEntered(btn);
    }//GEN-LAST:event_homeBtnPanelMouseEntered

    private void homeBtnPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBtnPanelMouseExited
        JPanel btn= homeBtnPanel;
        isExited(btn);
    }//GEN-LAST:event_homeBtnPanelMouseExited

    private void transferBtnPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transferBtnPanelMouseClicked
        Transfer TF;
        try {
            TF = new Transfer(accountNumber);
             setVisible(false);
            TF.setVisible(true);
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(Account.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_transferBtnPanelMouseClicked

    private void transferBtnPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transferBtnPanelMouseEntered
        JPanel btn= transferBtnPanel;
        isEntered(btn);
    }//GEN-LAST:event_transferBtnPanelMouseEntered

    private void transferBtnPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transferBtnPanelMouseExited
        JPanel btn= transferBtnPanel;
        isExited(btn);
    }//GEN-LAST:event_transferBtnPanelMouseExited

    private void accountBtnPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountBtnPanelMouseClicked
        /*Account A= new Account();
        setVisible(false);
        A.setVisible(true);
        dispose();*/
    }//GEN-LAST:event_accountBtnPanelMouseClicked

    private void accountBtnPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountBtnPanelMouseEntered
        JPanel btn= accountBtnPanel;
        isEntered(btn);
    }//GEN-LAST:event_accountBtnPanelMouseEntered

    private void accountBtnPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountBtnPanelMouseExited
        JPanel btn= accountBtnPanel;
        isExited(btn);
    }//GEN-LAST:event_accountBtnPanelMouseExited

    private void cardsBtnPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cardsBtnPanelMouseClicked
        Cards CD;
        try {
            CD = new Cards(accountNumber);
            setVisible(false);
            CD.setVisible(true);
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(Account.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_cardsBtnPanelMouseClicked

    private void cardsBtnPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cardsBtnPanelMouseEntered
        JPanel btn= cardsBtnPanel;
        isEntered(btn);
    }//GEN-LAST:event_cardsBtnPanelMouseEntered

    private void cardsBtnPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cardsBtnPanelMouseExited
        JPanel btn= cardsBtnPanel;
        isExited(btn);
    }//GEN-LAST:event_cardsBtnPanelMouseExited

    private void profileBtnPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileBtnPanelMouseClicked
        Profile P;
        try {
            P = new Profile(accountNumber);
            setVisible(false);
            P.setVisible(true);
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(Account.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_profileBtnPanelMouseClicked

    private void profileBtnPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileBtnPanelMouseEntered
        JPanel btn= profileBtnPanel;
        isEntered(btn);
    }//GEN-LAST:event_profileBtnPanelMouseEntered

    private void profileBtnPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileBtnPanelMouseExited
        JPanel btn= profileBtnPanel;
        isExited(btn);
    }//GEN-LAST:event_profileBtnPanelMouseExited

    private void logoutBtnPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnPanelMouseClicked
        Login L= new Login();
        setVisible(false);
        L.setVisible(true);
        dispose();
    }//GEN-LAST:event_logoutBtnPanelMouseClicked

    private void logoutBtnPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnPanelMouseEntered
        JPanel btn= logoutBtnPanel;
        isEntered(btn);
    }//GEN-LAST:event_logoutBtnPanelMouseEntered

    private void logoutBtnPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnPanelMouseExited
        JPanel btn= logoutBtnPanel;
        isExited(btn);
    }//GEN-LAST:event_logoutBtnPanelMouseExited

    private void closeBtnLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnLabelMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeBtnLabelMouseClicked

    private void messageLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_messageLabelMouseClicked
        Message M= new Message(accountNumber);
        setVisible(false);
        M.setVisible(true);
        dispose();
    }//GEN-LAST:event_messageLabelMouseClicked
    void isEntered(JPanel btn)
    {
        btn.setBackground(new Color(0,0,204));
    }
    
    void isExited(JPanel btn)
    {
        btn.setBackground(new Color(0,0,255));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Account("").setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Account.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SKYBANKLabel;
    private javax.swing.JLabel SKYBANKLabel2;
    private javax.swing.JLabel SKYBANKLabel3;
    private javax.swing.JLabel accountBtnLabel;
    private javax.swing.JPanel accountBtnPanel;
    private javax.swing.JLabel accountLabel;
    private javax.swing.JLabel accountNumberLabel;
    private javax.swing.JLabel accountNumberLabel1;
    private javax.swing.JLabel accountStatusLabel;
    private javax.swing.JLabel accountStatusLabel1;
    private javax.swing.JLabel accountTypeLabel;
    private javax.swing.JLabel accountTypeLabel1;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JLabel addressLabel1;
    private javax.swing.JLabel addressLabel2;
    private javax.swing.JLabel availableBalanceLabel;
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JLabel balanceLabel1;
    private javax.swing.JPanel balancepanel1;
    private javax.swing.JLabel cardsBtnLabel;
    private javax.swing.JPanel cardsBtnPanel;
    private javax.swing.JLabel closeBtnLabel;
    private javax.swing.JLabel creditCardNumberLabel;
    private javax.swing.JLabel creditCardNumberLabel1;
    private javax.swing.JLabel customerAddressLabel;
    private javax.swing.JLabel customerAddressLabel1;
    private javax.swing.JLabel customerNameLabel;
    private javax.swing.JLabel customerNameLabel1;
    private javax.swing.JLabel debitCardNumberLabel;
    private javax.swing.JLabel debitCardNumberLabel1;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel emailLabel1;
    private javax.swing.JLabel headingLabel1;
    private javax.swing.JLabel homeBtnLabel;
    private javax.swing.JPanel homeBtnPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JLabel logoutBtnLabel;
    private javax.swing.JPanel logoutBtnPanel;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JLabel passBookLabel;
    private javax.swing.JPanel passBookPanel;
    private javax.swing.JLabel phoneNumberLabel;
    private javax.swing.JLabel phoneNumberLabel1;
    private javax.swing.JLabel profileBtnLabel;
    private javax.swing.JPanel profileBtnPanel;
    private javax.swing.JPanel sideBarPanel;
    private javax.swing.JLabel skyBankLabel;
    private javax.swing.JLabel takaLabel;
    private javax.swing.JLabel transferBtnLabel;
    private javax.swing.JPanel transferBtnPanel;
    // End of variables declaration//GEN-END:variables
}
