
import java.awt.Color;
import java.sql.ResultSet;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hp
 */
public class Admin14 extends javax.swing.JFrame {

    /**
     * Creates new form Admin14
     */
    public Admin14() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        admin2Panel = new javax.swing.JPanel();
        sideBarPanel = new javax.swing.JPanel();
        searchBtnPanel = new javax.swing.JPanel();
        searchBtnLabel = new javax.swing.JLabel();
        statementBtnPanel = new javax.swing.JPanel();
        statementBtnLabel = new javax.swing.JLabel();
        profileBtnPanel = new javax.swing.JPanel();
        profileBtnLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        exitBtnPanel = new javax.swing.JPanel();
        exitBtnLabel = new javax.swing.JLabel();
        admin2_2Panel = new javax.swing.JPanel();
        personalInformationLabel = new javax.swing.JLabel();
        printButton = new javax.swing.JButton();
        adminPanelLabel = new javax.swing.JLabel();
        searchAccountLabel = new javax.swing.JLabel();
        admin2Panel1 = new javax.swing.JPanel();
        sideBarPanel1 = new javax.swing.JPanel();
        searchBtnPanel1 = new javax.swing.JPanel();
        searchBtnLabel1 = new javax.swing.JLabel();
        statementBtnPanel1 = new javax.swing.JPanel();
        statementBtnLabel1 = new javax.swing.JLabel();
        profileBtnPanel1 = new javax.swing.JPanel();
        profileBtnLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        exitBtnPanel1 = new javax.swing.JPanel();
        exitBtnLabel1 = new javax.swing.JLabel();
        admin2_2Panel1 = new javax.swing.JPanel();
        personalInformationLabel1 = new javax.swing.JLabel();
        printButton1 = new javax.swing.JButton();
        adminPanelLabel1 = new javax.swing.JLabel();
        searchAccountLabel1 = new javax.swing.JLabel();
        admin14Panel = new javax.swing.JPanel();
        sideBarPanel3 = new javax.swing.JPanel();
        balanceBtnPanel = new javax.swing.JPanel();
        balanceBtnLabel = new javax.swing.JLabel();
        withdrawBtnPanel = new javax.swing.JPanel();
        withdrawBtnLabel = new javax.swing.JLabel();
        depositBtnPanel = new javax.swing.JPanel();
        depositBtnLabel = new javax.swing.JLabel();
        transferBtnPanel = new javax.swing.JPanel();
        transferBtnLabel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        exitBtnPanel3 = new javax.swing.JPanel();
        exitBtnLabel3 = new javax.swing.JLabel();
        admin14_2Panel = new javax.swing.JPanel();
        transferAmountLabel = new javax.swing.JLabel();
        enterAccountNumberLabel = new javax.swing.JLabel();
        enterAccountNumberTextField = new javax.swing.JTextField();
        entertransferAmountLabel = new javax.swing.JLabel();
        enterTransferAmountTextField = new javax.swing.JTextField();
        transferAmountButton = new javax.swing.JButton();
        enterReceiverAccountNumberTextField = new javax.swing.JTextField();
        enterReceiverAccountNumberLabel = new javax.swing.JLabel();
        adminPanelLabel3 = new javax.swing.JLabel();
        balanceDepositWithdrawTransferLabel = new javax.swing.JLabel();
        closeBtnLabel = new javax.swing.JLabel();

        admin2Panel.setBackground(new java.awt.Color(255, 255, 255));
        admin2Panel.setPreferredSize(new java.awt.Dimension(1120, 630));

        sideBarPanel.setBackground(new java.awt.Color(102, 0, 153));

        searchBtnPanel.setBackground(new java.awt.Color(153, 0, 153));
        searchBtnPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchBtnPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchBtnPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchBtnPanelMouseExited(evt);
            }
        });

        searchBtnLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        searchBtnLabel.setForeground(new java.awt.Color(255, 255, 255));
        searchBtnLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        searchBtnLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/white-search-person.png"))); // NOI18N
        searchBtnLabel.setText(" Search");

        javax.swing.GroupLayout searchBtnPanelLayout = new javax.swing.GroupLayout(searchBtnPanel);
        searchBtnPanel.setLayout(searchBtnPanelLayout);
        searchBtnPanelLayout.setHorizontalGroup(
            searchBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchBtnPanelLayout.createSequentialGroup()
                .addComponent(searchBtnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        searchBtnPanelLayout.setVerticalGroup(
            searchBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchBtnPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchBtnLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addContainerGap())
        );

        statementBtnPanel.setBackground(new java.awt.Color(153, 0, 153));
        statementBtnPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                statementBtnPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                statementBtnPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                statementBtnPanelMouseExited(evt);
            }
        });

        statementBtnLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        statementBtnLabel.setForeground(new java.awt.Color(255, 255, 255));
        statementBtnLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        statementBtnLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/white-moneybag.png"))); // NOI18N
        statementBtnLabel.setText(" Statement");

        javax.swing.GroupLayout statementBtnPanelLayout = new javax.swing.GroupLayout(statementBtnPanel);
        statementBtnPanel.setLayout(statementBtnPanelLayout);
        statementBtnPanelLayout.setHorizontalGroup(
            statementBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statementBtnPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(statementBtnLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        statementBtnPanelLayout.setVerticalGroup(
            statementBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, statementBtnPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statementBtnLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addContainerGap())
        );

        profileBtnPanel.setBackground(new java.awt.Color(153, 0, 153));
        profileBtnPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileBtnPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                profileBtnPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                profileBtnPanelMouseExited(evt);
            }
        });

        profileBtnLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        profileBtnLabel.setForeground(new java.awt.Color(255, 255, 255));
        profileBtnLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        profileBtnLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/white-user-icon.png"))); // NOI18N
        profileBtnLabel.setText("Profile");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/white-indicate.png"))); // NOI18N

        javax.swing.GroupLayout profileBtnPanelLayout = new javax.swing.GroupLayout(profileBtnPanel);
        profileBtnPanel.setLayout(profileBtnPanelLayout);
        profileBtnPanelLayout.setHorizontalGroup(
            profileBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profileBtnPanelLayout.createSequentialGroup()
                .addComponent(profileBtnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        profileBtnPanelLayout.setVerticalGroup(
            profileBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profileBtnPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(profileBtnLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addContainerGap())
        );

        exitBtnPanel.setBackground(new java.awt.Color(153, 0, 153));
        exitBtnPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitBtnPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitBtnPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitBtnPanelMouseExited(evt);
            }
        });

        exitBtnLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        exitBtnLabel.setForeground(new java.awt.Color(255, 255, 255));
        exitBtnLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitBtnLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/white-close-icon.png"))); // NOI18N
        exitBtnLabel.setText(" Exit");

        javax.swing.GroupLayout exitBtnPanelLayout = new javax.swing.GroupLayout(exitBtnPanel);
        exitBtnPanel.setLayout(exitBtnPanelLayout);
        exitBtnPanelLayout.setHorizontalGroup(
            exitBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exitBtnPanelLayout.createSequentialGroup()
                .addComponent(exitBtnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        exitBtnPanelLayout.setVerticalGroup(
            exitBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exitBtnPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exitBtnLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout sideBarPanelLayout = new javax.swing.GroupLayout(sideBarPanel);
        sideBarPanel.setLayout(sideBarPanelLayout);
        sideBarPanelLayout.setHorizontalGroup(
            sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(searchBtnPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(statementBtnPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(profileBtnPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(exitBtnPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        sideBarPanelLayout.setVerticalGroup(
            sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarPanelLayout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(searchBtnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(profileBtnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(statementBtnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(exitBtnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        admin2_2Panel.setBackground(new java.awt.Color(102, 0, 153));

        personalInformationLabel.setBackground(new java.awt.Color(0, 0, 0));
        personalInformationLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 36)); // NOI18N
        personalInformationLabel.setForeground(new java.awt.Color(255, 255, 255));
        personalInformationLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        personalInformationLabel.setText("Personal Information");

        printButton.setBackground(new java.awt.Color(0, 51, 102));
        printButton.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        printButton.setForeground(new java.awt.Color(255, 255, 255));
        printButton.setText("Print");
        printButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        printButton.setMaximumSize(new java.awt.Dimension(120, 40));
        printButton.setMinimumSize(new java.awt.Dimension(120, 40));
        printButton.setPreferredSize(new java.awt.Dimension(120, 40));
        printButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout admin2_2PanelLayout = new javax.swing.GroupLayout(admin2_2Panel);
        admin2_2Panel.setLayout(admin2_2PanelLayout);
        admin2_2PanelLayout.setHorizontalGroup(
            admin2_2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(personalInformationLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, admin2_2PanelLayout.createSequentialGroup()
                .addContainerGap(234, Short.MAX_VALUE)
                .addComponent(printButton, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(217, 217, 217))
        );
        admin2_2PanelLayout.setVerticalGroup(
            admin2_2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(admin2_2PanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(personalInformationLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 359, Short.MAX_VALUE)
                .addComponent(printButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        adminPanelLabel.setBackground(new java.awt.Color(0, 0, 0));
        adminPanelLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 3, 36)); // NOI18N
        adminPanelLabel.setForeground(new java.awt.Color(102, 0, 153));
        adminPanelLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        adminPanelLabel.setText("ADMIN PANEL");

        searchAccountLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        searchAccountLabel.setForeground(new java.awt.Color(102, 0, 153));
        searchAccountLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        searchAccountLabel.setText("Search Account");

        admin2Panel1.setBackground(new java.awt.Color(255, 255, 255));
        admin2Panel1.setPreferredSize(new java.awt.Dimension(1120, 630));

        sideBarPanel1.setBackground(new java.awt.Color(102, 0, 153));

        searchBtnPanel1.setBackground(new java.awt.Color(153, 0, 153));
        searchBtnPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchBtnPanel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchBtnPanel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchBtnPanel1MouseExited(evt);
            }
        });

        searchBtnLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        searchBtnLabel1.setForeground(new java.awt.Color(255, 255, 255));
        searchBtnLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        searchBtnLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/white-search-person.png"))); // NOI18N
        searchBtnLabel1.setText(" Search");

        javax.swing.GroupLayout searchBtnPanel1Layout = new javax.swing.GroupLayout(searchBtnPanel1);
        searchBtnPanel1.setLayout(searchBtnPanel1Layout);
        searchBtnPanel1Layout.setHorizontalGroup(
            searchBtnPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchBtnPanel1Layout.createSequentialGroup()
                .addComponent(searchBtnLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        searchBtnPanel1Layout.setVerticalGroup(
            searchBtnPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchBtnPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchBtnLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addContainerGap())
        );

        statementBtnPanel1.setBackground(new java.awt.Color(153, 0, 153));
        statementBtnPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                statementBtnPanel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                statementBtnPanel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                statementBtnPanel1MouseExited(evt);
            }
        });

        statementBtnLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        statementBtnLabel1.setForeground(new java.awt.Color(255, 255, 255));
        statementBtnLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        statementBtnLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/white-moneybag.png"))); // NOI18N
        statementBtnLabel1.setText(" Statement");

        javax.swing.GroupLayout statementBtnPanel1Layout = new javax.swing.GroupLayout(statementBtnPanel1);
        statementBtnPanel1.setLayout(statementBtnPanel1Layout);
        statementBtnPanel1Layout.setHorizontalGroup(
            statementBtnPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statementBtnPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(statementBtnLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        statementBtnPanel1Layout.setVerticalGroup(
            statementBtnPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, statementBtnPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statementBtnLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addContainerGap())
        );

        profileBtnPanel1.setBackground(new java.awt.Color(153, 0, 153));
        profileBtnPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileBtnPanel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                profileBtnPanel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                profileBtnPanel1MouseExited(evt);
            }
        });

        profileBtnLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        profileBtnLabel1.setForeground(new java.awt.Color(255, 255, 255));
        profileBtnLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        profileBtnLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/white-user-icon.png"))); // NOI18N
        profileBtnLabel1.setText("Profile");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/white-indicate.png"))); // NOI18N

        javax.swing.GroupLayout profileBtnPanel1Layout = new javax.swing.GroupLayout(profileBtnPanel1);
        profileBtnPanel1.setLayout(profileBtnPanel1Layout);
        profileBtnPanel1Layout.setHorizontalGroup(
            profileBtnPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profileBtnPanel1Layout.createSequentialGroup()
                .addComponent(profileBtnLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        profileBtnPanel1Layout.setVerticalGroup(
            profileBtnPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profileBtnPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(profileBtnLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addContainerGap())
        );

        exitBtnPanel1.setBackground(new java.awt.Color(153, 0, 153));
        exitBtnPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitBtnPanel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitBtnPanel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitBtnPanel1MouseExited(evt);
            }
        });

        exitBtnLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        exitBtnLabel1.setForeground(new java.awt.Color(255, 255, 255));
        exitBtnLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitBtnLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/white-close-icon.png"))); // NOI18N
        exitBtnLabel1.setText(" Exit");

        javax.swing.GroupLayout exitBtnPanel1Layout = new javax.swing.GroupLayout(exitBtnPanel1);
        exitBtnPanel1.setLayout(exitBtnPanel1Layout);
        exitBtnPanel1Layout.setHorizontalGroup(
            exitBtnPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exitBtnPanel1Layout.createSequentialGroup()
                .addComponent(exitBtnLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        exitBtnPanel1Layout.setVerticalGroup(
            exitBtnPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exitBtnPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exitBtnLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout sideBarPanel1Layout = new javax.swing.GroupLayout(sideBarPanel1);
        sideBarPanel1.setLayout(sideBarPanel1Layout);
        sideBarPanel1Layout.setHorizontalGroup(
            sideBarPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(searchBtnPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(statementBtnPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(profileBtnPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(exitBtnPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        sideBarPanel1Layout.setVerticalGroup(
            sideBarPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarPanel1Layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(searchBtnPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(profileBtnPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(statementBtnPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(exitBtnPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        admin2_2Panel1.setBackground(new java.awt.Color(102, 0, 153));

        personalInformationLabel1.setBackground(new java.awt.Color(0, 0, 0));
        personalInformationLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 36)); // NOI18N
        personalInformationLabel1.setForeground(new java.awt.Color(255, 255, 255));
        personalInformationLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        personalInformationLabel1.setText("Personal Information");

        printButton1.setBackground(new java.awt.Color(0, 51, 102));
        printButton1.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        printButton1.setForeground(new java.awt.Color(255, 255, 255));
        printButton1.setText("Print");
        printButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        printButton1.setMaximumSize(new java.awt.Dimension(120, 40));
        printButton1.setMinimumSize(new java.awt.Dimension(120, 40));
        printButton1.setPreferredSize(new java.awt.Dimension(120, 40));
        printButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout admin2_2Panel1Layout = new javax.swing.GroupLayout(admin2_2Panel1);
        admin2_2Panel1.setLayout(admin2_2Panel1Layout);
        admin2_2Panel1Layout.setHorizontalGroup(
            admin2_2Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(personalInformationLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, admin2_2Panel1Layout.createSequentialGroup()
                .addContainerGap(234, Short.MAX_VALUE)
                .addComponent(printButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(217, 217, 217))
        );
        admin2_2Panel1Layout.setVerticalGroup(
            admin2_2Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(admin2_2Panel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(personalInformationLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 359, Short.MAX_VALUE)
                .addComponent(printButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        adminPanelLabel1.setBackground(new java.awt.Color(0, 0, 0));
        adminPanelLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 3, 36)); // NOI18N
        adminPanelLabel1.setForeground(new java.awt.Color(102, 0, 153));
        adminPanelLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        adminPanelLabel1.setText("ADMIN PANEL");

        searchAccountLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        searchAccountLabel1.setForeground(new java.awt.Color(102, 0, 153));
        searchAccountLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        searchAccountLabel1.setText("Search Account");

        javax.swing.GroupLayout admin2Panel1Layout = new javax.swing.GroupLayout(admin2Panel1);
        admin2Panel1.setLayout(admin2Panel1Layout);
        admin2Panel1Layout.setHorizontalGroup(
            admin2Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(admin2Panel1Layout.createSequentialGroup()
                .addComponent(sideBarPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(admin2Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(admin2Panel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(admin2Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, admin2Panel1Layout.createSequentialGroup()
                                .addComponent(admin2_2Panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, admin2Panel1Layout.createSequentialGroup()
                                .addComponent(adminPanelLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 965, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(admin2Panel1Layout.createSequentialGroup()
                        .addComponent(searchAccountLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        admin2Panel1Layout.setVerticalGroup(
            admin2Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sideBarPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, admin2Panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(adminPanelLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(searchAccountLabel1)
                .addGap(18, 18, 18)
                .addComponent(admin2_2Panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );

        javax.swing.GroupLayout admin2PanelLayout = new javax.swing.GroupLayout(admin2Panel);
        admin2Panel.setLayout(admin2PanelLayout);
        admin2PanelLayout.setHorizontalGroup(
            admin2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(admin2PanelLayout.createSequentialGroup()
                .addComponent(sideBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(admin2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(admin2PanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(admin2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, admin2PanelLayout.createSequentialGroup()
                                .addComponent(admin2_2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, admin2PanelLayout.createSequentialGroup()
                                .addComponent(adminPanelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 965, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(admin2PanelLayout.createSequentialGroup()
                        .addComponent(searchAccountLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(admin2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(admin2PanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(admin2Panel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1122, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        admin2PanelLayout.setVerticalGroup(
            admin2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sideBarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, admin2PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(adminPanelLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(searchAccountLabel)
                .addGap(18, 18, 18)
                .addComponent(admin2_2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
            .addGroup(admin2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(admin2PanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(admin2Panel1, javax.swing.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        admin14Panel.setBackground(new java.awt.Color(255, 255, 255));
        admin14Panel.setMinimumSize(new java.awt.Dimension(1120, 630));
        admin14Panel.setPreferredSize(new java.awt.Dimension(1120, 630));
        admin14Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sideBarPanel3.setBackground(new java.awt.Color(102, 0, 153));

        balanceBtnPanel.setBackground(new java.awt.Color(153, 0, 153));
        balanceBtnPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                balanceBtnPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                balanceBtnPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                balanceBtnPanelMouseExited(evt);
            }
        });

        balanceBtnLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        balanceBtnLabel.setForeground(new java.awt.Color(255, 255, 255));
        balanceBtnLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        balanceBtnLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/white-moneybag.png"))); // NOI18N
        balanceBtnLabel.setText("Balance");

        javax.swing.GroupLayout balanceBtnPanelLayout = new javax.swing.GroupLayout(balanceBtnPanel);
        balanceBtnPanel.setLayout(balanceBtnPanelLayout);
        balanceBtnPanelLayout.setHorizontalGroup(
            balanceBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(balanceBtnPanelLayout.createSequentialGroup()
                .addComponent(balanceBtnLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        balanceBtnPanelLayout.setVerticalGroup(
            balanceBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(balanceBtnPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(balanceBtnLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addContainerGap())
        );

        withdrawBtnPanel.setBackground(new java.awt.Color(153, 0, 153));
        withdrawBtnPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                withdrawBtnPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                withdrawBtnPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                withdrawBtnPanelMouseExited(evt);
            }
        });

        withdrawBtnLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        withdrawBtnLabel.setForeground(new java.awt.Color(255, 255, 255));
        withdrawBtnLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        withdrawBtnLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/white-moneybag.png"))); // NOI18N
        withdrawBtnLabel.setText("Withdraw");

        javax.swing.GroupLayout withdrawBtnPanelLayout = new javax.swing.GroupLayout(withdrawBtnPanel);
        withdrawBtnPanel.setLayout(withdrawBtnPanelLayout);
        withdrawBtnPanelLayout.setHorizontalGroup(
            withdrawBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(withdrawBtnPanelLayout.createSequentialGroup()
                .addComponent(withdrawBtnLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        withdrawBtnPanelLayout.setVerticalGroup(
            withdrawBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, withdrawBtnPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(withdrawBtnLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addContainerGap())
        );

        depositBtnPanel.setBackground(new java.awt.Color(153, 0, 153));
        depositBtnPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                depositBtnPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                depositBtnPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                depositBtnPanelMouseExited(evt);
            }
        });

        depositBtnLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        depositBtnLabel.setForeground(new java.awt.Color(255, 255, 255));
        depositBtnLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        depositBtnLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/white-moneybag.png"))); // NOI18N
        depositBtnLabel.setText("Deposit");

        javax.swing.GroupLayout depositBtnPanelLayout = new javax.swing.GroupLayout(depositBtnPanel);
        depositBtnPanel.setLayout(depositBtnPanelLayout);
        depositBtnPanelLayout.setHorizontalGroup(
            depositBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(depositBtnPanelLayout.createSequentialGroup()
                .addComponent(depositBtnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        depositBtnPanelLayout.setVerticalGroup(
            depositBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, depositBtnPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(depositBtnLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addContainerGap())
        );

        transferBtnPanel.setBackground(new java.awt.Color(153, 0, 153));
        transferBtnPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transferBtnPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                transferBtnPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                transferBtnPanelMouseExited(evt);
            }
        });

        transferBtnLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        transferBtnLabel.setForeground(new java.awt.Color(255, 255, 255));
        transferBtnLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        transferBtnLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/white-moneybag.png"))); // NOI18N
        transferBtnLabel.setText("Transfer");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/white-indicate.png"))); // NOI18N

        javax.swing.GroupLayout transferBtnPanelLayout = new javax.swing.GroupLayout(transferBtnPanel);
        transferBtnPanel.setLayout(transferBtnPanelLayout);
        transferBtnPanelLayout.setHorizontalGroup(
            transferBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transferBtnPanelLayout.createSequentialGroup()
                .addComponent(transferBtnLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        transferBtnPanelLayout.setVerticalGroup(
            transferBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transferBtnPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(transferBtnLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        exitBtnPanel3.setBackground(new java.awt.Color(153, 0, 153));
        exitBtnPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitBtnPanel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitBtnPanel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitBtnPanel3MouseExited(evt);
            }
        });

        exitBtnLabel3.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        exitBtnLabel3.setForeground(new java.awt.Color(255, 255, 255));
        exitBtnLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitBtnLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/white-close-icon.png"))); // NOI18N
        exitBtnLabel3.setText(" Exit");

        javax.swing.GroupLayout exitBtnPanel3Layout = new javax.swing.GroupLayout(exitBtnPanel3);
        exitBtnPanel3.setLayout(exitBtnPanel3Layout);
        exitBtnPanel3Layout.setHorizontalGroup(
            exitBtnPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exitBtnPanel3Layout.createSequentialGroup()
                .addComponent(exitBtnLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        exitBtnPanel3Layout.setVerticalGroup(
            exitBtnPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exitBtnPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exitBtnLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout sideBarPanel3Layout = new javax.swing.GroupLayout(sideBarPanel3);
        sideBarPanel3.setLayout(sideBarPanel3Layout);
        sideBarPanel3Layout.setHorizontalGroup(
            sideBarPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(balanceBtnPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(withdrawBtnPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(depositBtnPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(transferBtnPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(exitBtnPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        sideBarPanel3Layout.setVerticalGroup(
            sideBarPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sideBarPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(balanceBtnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(depositBtnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(withdrawBtnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(transferBtnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(exitBtnPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
        );

        admin14Panel.add(sideBarPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 646));

        admin14_2Panel.setBackground(new java.awt.Color(102, 0, 153));

        transferAmountLabel.setBackground(new java.awt.Color(0, 0, 0));
        transferAmountLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 36)); // NOI18N
        transferAmountLabel.setForeground(new java.awt.Color(255, 255, 255));
        transferAmountLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        transferAmountLabel.setText("Transfer Amount");

        enterAccountNumberLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        enterAccountNumberLabel.setForeground(new java.awt.Color(255, 255, 255));
        enterAccountNumberLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        enterAccountNumberLabel.setText("Enter Account Number");

        enterAccountNumberTextField.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        enterAccountNumberTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        enterAccountNumberTextField.setToolTipText("Enter Enter Account Number");

        entertransferAmountLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        entertransferAmountLabel.setForeground(new java.awt.Color(255, 255, 255));
        entertransferAmountLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        entertransferAmountLabel.setText("Enter Transfer Amount");

        enterTransferAmountTextField.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        enterTransferAmountTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        enterTransferAmountTextField.setToolTipText("Enter Enter Account Number");

        transferAmountButton.setBackground(new java.awt.Color(0, 51, 102));
        transferAmountButton.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        transferAmountButton.setForeground(new java.awt.Color(255, 255, 255));
        transferAmountButton.setText("Transfer Amount");
        transferAmountButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        transferAmountButton.setMaximumSize(new java.awt.Dimension(120, 40));
        transferAmountButton.setMinimumSize(new java.awt.Dimension(120, 40));
        transferAmountButton.setPreferredSize(new java.awt.Dimension(120, 40));
        transferAmountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferAmountButtonActionPerformed(evt);
            }
        });

        enterReceiverAccountNumberTextField.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        enterReceiverAccountNumberTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        enterReceiverAccountNumberTextField.setToolTipText("Enter Enter Account Number");

        enterReceiverAccountNumberLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        enterReceiverAccountNumberLabel.setForeground(new java.awt.Color(255, 255, 255));
        enterReceiverAccountNumberLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        enterReceiverAccountNumberLabel.setText("Enter Receiver Account Number");

        javax.swing.GroupLayout admin14_2PanelLayout = new javax.swing.GroupLayout(admin14_2Panel);
        admin14_2Panel.setLayout(admin14_2PanelLayout);
        admin14_2PanelLayout.setHorizontalGroup(
            admin14_2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(transferAmountLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, admin14_2PanelLayout.createSequentialGroup()
                .addContainerGap(290, Short.MAX_VALUE)
                .addGroup(admin14_2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(admin14_2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(enterReceiverAccountNumberTextField)
                        .addComponent(enterReceiverAccountNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(admin14_2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(enterTransferAmountTextField)
                        .addComponent(entertransferAmountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(transferAmountButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(admin14_2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(enterAccountNumberTextField)
                        .addComponent(enterAccountNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(271, 271, 271))
        );
        admin14_2PanelLayout.setVerticalGroup(
            admin14_2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(admin14_2PanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(transferAmountLabel)
                .addGap(52, 52, 52)
                .addComponent(enterAccountNumberLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(enterAccountNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(enterReceiverAccountNumberLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(enterReceiverAccountNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(entertransferAmountLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(enterTransferAmountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(transferAmountButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        admin14Panel.add(admin14_2Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 101, -1, -1));

        adminPanelLabel3.setBackground(new java.awt.Color(0, 0, 0));
        adminPanelLabel3.setFont(new java.awt.Font("Microsoft Sans Serif", 3, 36)); // NOI18N
        adminPanelLabel3.setForeground(new java.awt.Color(102, 0, 153));
        adminPanelLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        adminPanelLabel3.setText("ADMIN PANEL");
        admin14Panel.add(adminPanelLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 13, 977, -1));

        balanceDepositWithdrawTransferLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        balanceDepositWithdrawTransferLabel.setForeground(new java.awt.Color(102, 0, 153));
        balanceDepositWithdrawTransferLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        balanceDepositWithdrawTransferLabel.setText(" Balance / Deposit / Withdraw / Transfer");
        admin14Panel.add(balanceDepositWithdrawTransferLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 62, 965, -1));

        closeBtnLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/close-btn.png"))); // NOI18N
        closeBtnLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBtnLabelMouseClicked(evt);
            }
        });
        admin14Panel.add(closeBtnLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(admin14Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 1122, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(admin14Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void searchBtnPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchBtnPanelMouseClicked
        Admin1 A1= new Admin1();
        setVisible(false);
        A1.setVisible(true);
        dispose();
    }//GEN-LAST:event_searchBtnPanelMouseClicked

    private void searchBtnPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchBtnPanelMouseEntered
        JPanel btn= searchBtnPanel;
        isEntered(btn);
    }//GEN-LAST:event_searchBtnPanelMouseEntered

    private void searchBtnPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchBtnPanelMouseExited
        JPanel btn= searchBtnPanel;
        isExited(btn);
    }//GEN-LAST:event_searchBtnPanelMouseExited

    private void statementBtnPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statementBtnPanelMouseClicked
       /* Admin3 A3= new Admin3();
        setVisible(false);
        A3.setVisible(true);
        dispose();*/
    }//GEN-LAST:event_statementBtnPanelMouseClicked

    private void statementBtnPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statementBtnPanelMouseEntered
        JPanel btn= statementBtnPanel;
        isEntered(btn);
    }//GEN-LAST:event_statementBtnPanelMouseEntered

    private void statementBtnPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statementBtnPanelMouseExited
        JPanel btn= statementBtnPanel;
        isExited(btn);
    }//GEN-LAST:event_statementBtnPanelMouseExited

    private void profileBtnPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileBtnPanelMouseClicked
        /*Admin2 A2= new Admin2();
        setVisible(false);
        A2.setVisible(true);
        dispose();*/
    }//GEN-LAST:event_profileBtnPanelMouseClicked

    private void profileBtnPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileBtnPanelMouseEntered
        JPanel btn= profileBtnPanel;
        isEntered(btn);
    }//GEN-LAST:event_profileBtnPanelMouseEntered

    private void profileBtnPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileBtnPanelMouseExited
        JPanel btn= profileBtnPanel;
        isExited(btn);
    }//GEN-LAST:event_profileBtnPanelMouseExited

    private void exitBtnPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnPanelMouseClicked
        Admin4 A4= new Admin4();
        setVisible(false);
        A4.setVisible(true);
        dispose();
    }//GEN-LAST:event_exitBtnPanelMouseClicked

    private void exitBtnPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnPanelMouseEntered
        JPanel btn= exitBtnPanel;
        isEntered(btn);
    }//GEN-LAST:event_exitBtnPanelMouseEntered

    private void exitBtnPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnPanelMouseExited
        JPanel btn= exitBtnPanel;
        isExited(btn);
    }//GEN-LAST:event_exitBtnPanelMouseExited

    private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_printButtonActionPerformed

    private void searchBtnPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchBtnPanel1MouseClicked
        Admin1 A1= new Admin1();
        setVisible(false);
        A1.setVisible(true);
        dispose();
    }//GEN-LAST:event_searchBtnPanel1MouseClicked

    private void searchBtnPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchBtnPanel1MouseEntered
        JPanel btn= searchBtnPanel;
        isEntered(btn);
    }//GEN-LAST:event_searchBtnPanel1MouseEntered

    private void searchBtnPanel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchBtnPanel1MouseExited
        JPanel btn= searchBtnPanel;
        isExited(btn);
    }//GEN-LAST:event_searchBtnPanel1MouseExited

    private void statementBtnPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statementBtnPanel1MouseClicked
        /*Admin3 A3= new Admin3();
        setVisible(false);
        A3.setVisible(true);
        dispose();*/
    }//GEN-LAST:event_statementBtnPanel1MouseClicked

    private void statementBtnPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statementBtnPanel1MouseEntered
        JPanel btn= statementBtnPanel;
        isEntered(btn);
    }//GEN-LAST:event_statementBtnPanel1MouseEntered

    private void statementBtnPanel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statementBtnPanel1MouseExited
        JPanel btn= statementBtnPanel;
        isExited(btn);
    }//GEN-LAST:event_statementBtnPanel1MouseExited

    private void profileBtnPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileBtnPanel1MouseClicked
        /*Admin2 A2= new Admin2();
        setVisible(false);
        A2.setVisible(true);
        dispose();*/
    }//GEN-LAST:event_profileBtnPanel1MouseClicked

    private void profileBtnPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileBtnPanel1MouseEntered
        JPanel btn= profileBtnPanel;
        isEntered(btn);
    }//GEN-LAST:event_profileBtnPanel1MouseEntered

    private void profileBtnPanel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileBtnPanel1MouseExited
        JPanel btn= profileBtnPanel;
        isExited(btn);
    }//GEN-LAST:event_profileBtnPanel1MouseExited

    private void exitBtnPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnPanel1MouseClicked
        Admin4 A4= new Admin4();
        setVisible(false);
        A4.setVisible(true);
        dispose();
    }//GEN-LAST:event_exitBtnPanel1MouseClicked

    private void exitBtnPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnPanel1MouseEntered
        JPanel btn= exitBtnPanel;
        isEntered(btn);
    }//GEN-LAST:event_exitBtnPanel1MouseEntered

    private void exitBtnPanel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnPanel1MouseExited
        JPanel btn= exitBtnPanel;
        isExited(btn);
    }//GEN-LAST:event_exitBtnPanel1MouseExited

    private void printButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_printButton1ActionPerformed

    private void balanceBtnPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_balanceBtnPanelMouseClicked
        Admin11 A11= new Admin11();
        setVisible(false);
        A11.setVisible(true);
        dispose();
    }//GEN-LAST:event_balanceBtnPanelMouseClicked

    private void balanceBtnPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_balanceBtnPanelMouseEntered
        JPanel btn= balanceBtnPanel;
        isEntered(btn);
    }//GEN-LAST:event_balanceBtnPanelMouseEntered

    private void balanceBtnPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_balanceBtnPanelMouseExited
        JPanel btn= balanceBtnPanel;
        isExited(btn);
    }//GEN-LAST:event_balanceBtnPanelMouseExited

    private void withdrawBtnPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_withdrawBtnPanelMouseClicked
        Admin13 A13= new Admin13();
        setVisible(false);
        A13.setVisible(true);
        dispose();
    }//GEN-LAST:event_withdrawBtnPanelMouseClicked

    private void withdrawBtnPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_withdrawBtnPanelMouseEntered
        JPanel btn= withdrawBtnPanel;
        isEntered(btn);
    }//GEN-LAST:event_withdrawBtnPanelMouseEntered

    private void withdrawBtnPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_withdrawBtnPanelMouseExited
        JPanel btn= withdrawBtnPanel;
        isExited(btn);
    }//GEN-LAST:event_withdrawBtnPanelMouseExited

    private void depositBtnPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_depositBtnPanelMouseClicked
        Admin12 A12= new Admin12();
        setVisible(false);
        A12.setVisible(true);
        dispose();
    }//GEN-LAST:event_depositBtnPanelMouseClicked

    private void depositBtnPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_depositBtnPanelMouseEntered
        JPanel btn= depositBtnPanel;
        isEntered(btn);
    }//GEN-LAST:event_depositBtnPanelMouseEntered

    private void depositBtnPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_depositBtnPanelMouseExited
        JPanel btn= depositBtnPanel;
        isExited(btn);
    }//GEN-LAST:event_depositBtnPanelMouseExited

    private void transferBtnPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transferBtnPanelMouseClicked
        /*Admin14 A14= new Admin14();
        setVisible(false);
        A14.setVisible(true);
        dispose();*/
    }//GEN-LAST:event_transferBtnPanelMouseClicked

    private void transferBtnPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transferBtnPanelMouseEntered
        JPanel btn= transferBtnPanel;
        isEntered(btn);
    }//GEN-LAST:event_transferBtnPanelMouseEntered

    private void transferBtnPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transferBtnPanelMouseExited
        JPanel btn= transferBtnPanel;
        isExited(btn);
    }//GEN-LAST:event_transferBtnPanelMouseExited

    private void exitBtnPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnPanel3MouseClicked
        Admin4 A4= new Admin4();
        setVisible(false);
        A4.setVisible(true);
        dispose();
    }//GEN-LAST:event_exitBtnPanel3MouseClicked

    private void exitBtnPanel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnPanel3MouseEntered
        JPanel btn= exitBtnPanel;
        isEntered(btn);
    }//GEN-LAST:event_exitBtnPanel3MouseEntered

    private void exitBtnPanel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnPanel3MouseExited
        JPanel btn= exitBtnPanel;
        isExited(btn);
    }//GEN-LAST:event_exitBtnPanel3MouseExited
    void isEntered(JPanel btn)
    {
        btn.setBackground(new Color(0,51,102));
    }
    
    void isExited(JPanel btn)
    {
        btn.setBackground(new Color(153,0,153));
    }
    private void transferAmountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferAmountButtonActionPerformed
        // TODO add your handling code here:
        String accountNumber=enterAccountNumberTextField.getText();
        String receiveraccountNumber=enterReceiverAccountNumberTextField.getText();
        String amount=enterTransferAmountTextField.getText();
        String type1="Transfer";
        String type2="Deposit";
        Date dateAndTime=new Date();
        //String balance="";
        try{
            if(accountNumber.equals("")||
                receiveraccountNumber.equals("")||
                amount.equals(""))
            {
                if(accountNumber.equals(""))
                {
                    JOptionPane.showMessageDialog(null,"Account Number is Requied");
                }
                if(receiveraccountNumber.equals(""))
                {
                    JOptionPane.showMessageDialog(null,"Receiver Account Number is Requied");
                }
                if(amount.equals(""))
                {
                    JOptionPane.showMessageDialog(null,"Transfer Amount is Requied");
                }
            }else{
                Conn c=new Conn();
                String query4="select * from addApplication3 where accountNumber = '"+accountNumber+"'";
                ResultSet rs4=c.s.executeQuery(query4);
                
                if(rs4.next())
                {
                    String query5="select * from addApplication3 where accountNumber = '"+receiveraccountNumber+"'";
                    ResultSet rs5 = c.s.executeQuery(query5);
                    //2 resultset at a time set and operate kora jay nh
                    if(rs5.next())
                    {   String query1="insert into balance values('"+accountNumber+"', '"+dateAndTime+"', '"+type1+"', '"+amount+"')";
                        c.s.executeUpdate(query1);
                        String query2="insert into balance values('"+receiveraccountNumber+"', '"+dateAndTime+"', '"+type2+"', '"+amount+"')";
                        c.s.executeUpdate(query2);

                        JOptionPane.showMessageDialog(null,amount+" Taka Transfered Sucessfully!!!");
                        Admin11 A11= new Admin11();
                        setVisible(false);
                        A11.setVisible(true);
                        dispose();
                    }else{
                        JOptionPane.showMessageDialog(null,"Incorrect Receiver Account Number");
                    }
                }else{
                        JOptionPane.showMessageDialog(null,"Incorrect Account Number");
                    
                }
            }
        }catch(Exception e){
            System.out.println(e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_transferAmountButtonActionPerformed

    private void closeBtnLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnLabelMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeBtnLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin14.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin14.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin14.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin14.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin14().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel admin14Panel;
    private javax.swing.JPanel admin14_2Panel;
    private javax.swing.JPanel admin2Panel;
    private javax.swing.JPanel admin2Panel1;
    private javax.swing.JPanel admin2_2Panel;
    private javax.swing.JPanel admin2_2Panel1;
    private javax.swing.JLabel adminPanelLabel;
    private javax.swing.JLabel adminPanelLabel1;
    private javax.swing.JLabel adminPanelLabel3;
    private javax.swing.JLabel balanceBtnLabel;
    private javax.swing.JPanel balanceBtnPanel;
    private javax.swing.JLabel balanceDepositWithdrawTransferLabel;
    private javax.swing.JLabel closeBtnLabel;
    private javax.swing.JLabel depositBtnLabel;
    private javax.swing.JPanel depositBtnPanel;
    private javax.swing.JLabel enterAccountNumberLabel;
    private javax.swing.JTextField enterAccountNumberTextField;
    private javax.swing.JLabel enterReceiverAccountNumberLabel;
    private javax.swing.JTextField enterReceiverAccountNumberTextField;
    private javax.swing.JTextField enterTransferAmountTextField;
    private javax.swing.JLabel entertransferAmountLabel;
    private javax.swing.JLabel exitBtnLabel;
    private javax.swing.JLabel exitBtnLabel1;
    private javax.swing.JLabel exitBtnLabel3;
    private javax.swing.JPanel exitBtnPanel;
    private javax.swing.JPanel exitBtnPanel1;
    private javax.swing.JPanel exitBtnPanel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel personalInformationLabel;
    private javax.swing.JLabel personalInformationLabel1;
    private javax.swing.JButton printButton;
    private javax.swing.JButton printButton1;
    private javax.swing.JLabel profileBtnLabel;
    private javax.swing.JLabel profileBtnLabel1;
    private javax.swing.JPanel profileBtnPanel;
    private javax.swing.JPanel profileBtnPanel1;
    private javax.swing.JLabel searchAccountLabel;
    private javax.swing.JLabel searchAccountLabel1;
    private javax.swing.JLabel searchBtnLabel;
    private javax.swing.JLabel searchBtnLabel1;
    private javax.swing.JPanel searchBtnPanel;
    private javax.swing.JPanel searchBtnPanel1;
    private javax.swing.JPanel sideBarPanel;
    private javax.swing.JPanel sideBarPanel1;
    private javax.swing.JPanel sideBarPanel3;
    private javax.swing.JLabel statementBtnLabel;
    private javax.swing.JLabel statementBtnLabel1;
    private javax.swing.JPanel statementBtnPanel;
    private javax.swing.JPanel statementBtnPanel1;
    private javax.swing.JButton transferAmountButton;
    private javax.swing.JLabel transferAmountLabel;
    private javax.swing.JLabel transferBtnLabel;
    private javax.swing.JPanel transferBtnPanel;
    private javax.swing.JLabel withdrawBtnLabel;
    private javax.swing.JPanel withdrawBtnPanel;
    // End of variables declaration//GEN-END:variables
}
