
import java.awt.Color;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hp
 */
public class Admin11 extends javax.swing.JFrame {

    /**
     * Creates new form Admin11
     */
    public Admin11() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        admin11Panel = new javax.swing.JPanel();
        sideBarPanel = new javax.swing.JPanel();
        balanceBtnPanel = new javax.swing.JPanel();
        balanceBtnLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        withdrawBtnPanel = new javax.swing.JPanel();
        withdrawBtnLabel = new javax.swing.JLabel();
        depositBtnPanel = new javax.swing.JPanel();
        depositBtnLabel = new javax.swing.JLabel();
        transferBtnPanel = new javax.swing.JPanel();
        transferBtnLabel = new javax.swing.JLabel();
        exitBtnPanel = new javax.swing.JPanel();
        exitBtnLabel = new javax.swing.JLabel();
        admin11_2Panel = new javax.swing.JPanel();
        balanceCheckLabel = new javax.swing.JLabel();
        enterAccountNumberLabel = new javax.swing.JLabel();
        enterAccountNumberTextField = new javax.swing.JTextField();
        BalanceLabel = new javax.swing.JLabel();
        balanceCheckButton = new javax.swing.JButton();
        balancePanel = new javax.swing.JPanel();
        balanceLabel = new javax.swing.JLabel();
        adminPanelLabel = new javax.swing.JLabel();
        balanceDepositWithdrawTransferLabel = new javax.swing.JLabel();
        closeBtnLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        admin11Panel.setBackground(new java.awt.Color(255, 255, 255));
        admin11Panel.setPreferredSize(new java.awt.Dimension(1120, 630));
        admin11Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sideBarPanel.setBackground(new java.awt.Color(102, 0, 153));

        balanceBtnPanel.setBackground(new java.awt.Color(153, 0, 153));
        balanceBtnPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                balanceBtnPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                balanceBtnPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                balanceBtnPanelMouseExited(evt);
            }
        });

        balanceBtnLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        balanceBtnLabel.setForeground(new java.awt.Color(255, 255, 255));
        balanceBtnLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        balanceBtnLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/white-moneybag.png"))); // NOI18N
        balanceBtnLabel.setText("Balance");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/white-indicate.png"))); // NOI18N

        javax.swing.GroupLayout balanceBtnPanelLayout = new javax.swing.GroupLayout(balanceBtnPanel);
        balanceBtnPanel.setLayout(balanceBtnPanelLayout);
        balanceBtnPanelLayout.setHorizontalGroup(
            balanceBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(balanceBtnPanelLayout.createSequentialGroup()
                .addComponent(balanceBtnLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        balanceBtnPanelLayout.setVerticalGroup(
            balanceBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(balanceBtnPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(balanceBtnLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        withdrawBtnPanel.setBackground(new java.awt.Color(153, 0, 153));
        withdrawBtnPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                withdrawBtnPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                withdrawBtnPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                withdrawBtnPanelMouseExited(evt);
            }
        });

        withdrawBtnLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        withdrawBtnLabel.setForeground(new java.awt.Color(255, 255, 255));
        withdrawBtnLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        withdrawBtnLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/white-moneybag.png"))); // NOI18N
        withdrawBtnLabel.setText("Withdraw");

        javax.swing.GroupLayout withdrawBtnPanelLayout = new javax.swing.GroupLayout(withdrawBtnPanel);
        withdrawBtnPanel.setLayout(withdrawBtnPanelLayout);
        withdrawBtnPanelLayout.setHorizontalGroup(
            withdrawBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(withdrawBtnPanelLayout.createSequentialGroup()
                .addComponent(withdrawBtnLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        withdrawBtnPanelLayout.setVerticalGroup(
            withdrawBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, withdrawBtnPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(withdrawBtnLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addContainerGap())
        );

        depositBtnPanel.setBackground(new java.awt.Color(153, 0, 153));
        depositBtnPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                depositBtnPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                depositBtnPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                depositBtnPanelMouseExited(evt);
            }
        });

        depositBtnLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        depositBtnLabel.setForeground(new java.awt.Color(255, 255, 255));
        depositBtnLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        depositBtnLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/white-moneybag.png"))); // NOI18N
        depositBtnLabel.setText("Deposit");

        javax.swing.GroupLayout depositBtnPanelLayout = new javax.swing.GroupLayout(depositBtnPanel);
        depositBtnPanel.setLayout(depositBtnPanelLayout);
        depositBtnPanelLayout.setHorizontalGroup(
            depositBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(depositBtnPanelLayout.createSequentialGroup()
                .addComponent(depositBtnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        depositBtnPanelLayout.setVerticalGroup(
            depositBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, depositBtnPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(depositBtnLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addContainerGap())
        );

        transferBtnPanel.setBackground(new java.awt.Color(153, 0, 153));
        transferBtnPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transferBtnPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                transferBtnPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                transferBtnPanelMouseExited(evt);
            }
        });

        transferBtnLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        transferBtnLabel.setForeground(new java.awt.Color(255, 255, 255));
        transferBtnLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        transferBtnLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/white-moneybag.png"))); // NOI18N
        transferBtnLabel.setText("Transfer");

        javax.swing.GroupLayout transferBtnPanelLayout = new javax.swing.GroupLayout(transferBtnPanel);
        transferBtnPanel.setLayout(transferBtnPanelLayout);
        transferBtnPanelLayout.setHorizontalGroup(
            transferBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transferBtnPanelLayout.createSequentialGroup()
                .addComponent(transferBtnLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        transferBtnPanelLayout.setVerticalGroup(
            transferBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transferBtnPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(transferBtnLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addContainerGap())
        );

        exitBtnPanel.setBackground(new java.awt.Color(153, 0, 153));
        exitBtnPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitBtnPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitBtnPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitBtnPanelMouseExited(evt);
            }
        });

        exitBtnLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        exitBtnLabel.setForeground(new java.awt.Color(255, 255, 255));
        exitBtnLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitBtnLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/white-close-icon.png"))); // NOI18N
        exitBtnLabel.setText(" Exit");

        javax.swing.GroupLayout exitBtnPanelLayout = new javax.swing.GroupLayout(exitBtnPanel);
        exitBtnPanel.setLayout(exitBtnPanelLayout);
        exitBtnPanelLayout.setHorizontalGroup(
            exitBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exitBtnPanelLayout.createSequentialGroup()
                .addComponent(exitBtnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        exitBtnPanelLayout.setVerticalGroup(
            exitBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exitBtnPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exitBtnLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout sideBarPanelLayout = new javax.swing.GroupLayout(sideBarPanel);
        sideBarPanel.setLayout(sideBarPanelLayout);
        sideBarPanelLayout.setHorizontalGroup(
            sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(balanceBtnPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(withdrawBtnPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(depositBtnPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(transferBtnPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(exitBtnPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        sideBarPanelLayout.setVerticalGroup(
            sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sideBarPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(balanceBtnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(depositBtnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(withdrawBtnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(transferBtnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(exitBtnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
        );

        admin11Panel.add(sideBarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 646));

        admin11_2Panel.setBackground(new java.awt.Color(102, 0, 153));

        balanceCheckLabel.setBackground(new java.awt.Color(0, 0, 0));
        balanceCheckLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 36)); // NOI18N
        balanceCheckLabel.setForeground(new java.awt.Color(255, 255, 255));
        balanceCheckLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        balanceCheckLabel.setText("Balance Check");

        enterAccountNumberLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        enterAccountNumberLabel.setForeground(new java.awt.Color(255, 255, 255));
        enterAccountNumberLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        enterAccountNumberLabel.setText("Enter Account Number");

        enterAccountNumberTextField.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        enterAccountNumberTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        enterAccountNumberTextField.setToolTipText("Enter Enter Account Number");

        BalanceLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        BalanceLabel.setForeground(new java.awt.Color(255, 255, 255));
        BalanceLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BalanceLabel.setText("Balance");

        balanceCheckButton.setBackground(new java.awt.Color(0, 51, 102));
        balanceCheckButton.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        balanceCheckButton.setForeground(new java.awt.Color(255, 255, 255));
        balanceCheckButton.setText("Balance Check");
        balanceCheckButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        balanceCheckButton.setMaximumSize(new java.awt.Dimension(120, 40));
        balanceCheckButton.setMinimumSize(new java.awt.Dimension(120, 40));
        balanceCheckButton.setPreferredSize(new java.awt.Dimension(120, 40));
        balanceCheckButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balanceCheckButtonActionPerformed(evt);
            }
        });

        balancePanel.setBackground(new java.awt.Color(255, 255, 255));

        balanceLabel.setBackground(new java.awt.Color(255, 255, 255));
        balanceLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 16)); // NOI18N
        balanceLabel.setForeground(new java.awt.Color(51, 153, 0));
        balanceLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout balancePanelLayout = new javax.swing.GroupLayout(balancePanel);
        balancePanel.setLayout(balancePanelLayout);
        balancePanelLayout.setHorizontalGroup(
            balancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(balanceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        balancePanelLayout.setVerticalGroup(
            balancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(balanceLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout admin11_2PanelLayout = new javax.swing.GroupLayout(admin11_2Panel);
        admin11_2Panel.setLayout(admin11_2PanelLayout);
        admin11_2PanelLayout.setHorizontalGroup(
            admin11_2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(balanceCheckLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, admin11_2PanelLayout.createSequentialGroup()
                .addContainerGap(290, Short.MAX_VALUE)
                .addGroup(admin11_2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BalanceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                    .addComponent(enterAccountNumberTextField)
                    .addComponent(enterAccountNumberLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                    .addComponent(balanceCheckButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(balancePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(271, 271, 271))
        );
        admin11_2PanelLayout.setVerticalGroup(
            admin11_2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(admin11_2PanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(balanceCheckLabel)
                .addGap(93, 93, 93)
                .addComponent(enterAccountNumberLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(enterAccountNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(balanceCheckButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(BalanceLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(balancePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        admin11Panel.add(admin11_2Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 101, -1, -1));

        adminPanelLabel.setBackground(new java.awt.Color(0, 0, 0));
        adminPanelLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 3, 36)); // NOI18N
        adminPanelLabel.setForeground(new java.awt.Color(102, 0, 153));
        adminPanelLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        adminPanelLabel.setText("ADMIN PANEL");
        admin11Panel.add(adminPanelLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 13, 970, -1));

        balanceDepositWithdrawTransferLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        balanceDepositWithdrawTransferLabel.setForeground(new java.awt.Color(102, 0, 153));
        balanceDepositWithdrawTransferLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        balanceDepositWithdrawTransferLabel.setText(" Balance / Deposit / Withdraw / Transfer");
        admin11Panel.add(balanceDepositWithdrawTransferLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 62, 965, -1));

        closeBtnLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/close-btn.png"))); // NOI18N
        closeBtnLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBtnLabelMouseClicked(evt);
            }
        });
        admin11Panel.add(closeBtnLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(admin11Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 1122, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(admin11Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void balanceBtnPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_balanceBtnPanelMouseClicked
        Admin11 A11= new Admin11();
        setVisible(false);
        A11.setVisible(true);
        dispose();
    }//GEN-LAST:event_balanceBtnPanelMouseClicked

    private void balanceBtnPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_balanceBtnPanelMouseEntered
        JPanel btn= balanceBtnPanel;
        isEntered(btn);
    }//GEN-LAST:event_balanceBtnPanelMouseEntered

    private void balanceBtnPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_balanceBtnPanelMouseExited
        JPanel btn= balanceBtnPanel;
        isExited(btn);
    }//GEN-LAST:event_balanceBtnPanelMouseExited

    private void withdrawBtnPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_withdrawBtnPanelMouseClicked
        Admin13 A13= new Admin13();
        setVisible(false);
        A13.setVisible(true);
        dispose();
    }//GEN-LAST:event_withdrawBtnPanelMouseClicked

    private void withdrawBtnPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_withdrawBtnPanelMouseEntered
        JPanel btn= withdrawBtnPanel;
        isEntered(btn);
    }//GEN-LAST:event_withdrawBtnPanelMouseEntered

    private void withdrawBtnPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_withdrawBtnPanelMouseExited
        JPanel btn= withdrawBtnPanel;
        isExited(btn);
    }//GEN-LAST:event_withdrawBtnPanelMouseExited

    private void depositBtnPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_depositBtnPanelMouseClicked
        Admin12 A12= new Admin12();
        setVisible(false);
        A12.setVisible(true);
        dispose();
    }//GEN-LAST:event_depositBtnPanelMouseClicked

    private void depositBtnPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_depositBtnPanelMouseEntered
        JPanel btn= depositBtnPanel;
        isEntered(btn);
    }//GEN-LAST:event_depositBtnPanelMouseEntered

    private void depositBtnPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_depositBtnPanelMouseExited
        JPanel btn= depositBtnPanel;
        isExited(btn);
    }//GEN-LAST:event_depositBtnPanelMouseExited

    private void transferBtnPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transferBtnPanelMouseClicked
        Admin14 A14= new Admin14();
        setVisible(false);
        A14.setVisible(true);
        dispose();
    }//GEN-LAST:event_transferBtnPanelMouseClicked

    private void transferBtnPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transferBtnPanelMouseEntered
        JPanel btn= transferBtnPanel;
        isEntered(btn);
    }//GEN-LAST:event_transferBtnPanelMouseEntered

    private void transferBtnPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transferBtnPanelMouseExited
        JPanel btn= transferBtnPanel;
        isExited(btn);
    }//GEN-LAST:event_transferBtnPanelMouseExited

    private void exitBtnPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnPanelMouseClicked
        Admin4 A4= new Admin4();
        setVisible(false);
        A4.setVisible(true);
        dispose();
    }//GEN-LAST:event_exitBtnPanelMouseClicked

    private void exitBtnPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnPanelMouseEntered
        JPanel btn= exitBtnPanel;
        isEntered(btn);
    }//GEN-LAST:event_exitBtnPanelMouseEntered

    private void exitBtnPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnPanelMouseExited
        JPanel btn= exitBtnPanel;
        isExited(btn);
    }//GEN-LAST:event_exitBtnPanelMouseExited
    void isEntered(JPanel btn)
    {
        btn.setBackground(new Color(0,51,102));
    }
    
    void isExited(JPanel btn)
    {
        btn.setBackground(new Color(153,0,153));
    }
    private void balanceCheckButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balanceCheckButtonActionPerformed
        // TODO add your handling code here:
        String accountNumber=enterAccountNumberTextField.getText();
        balanceLabel.setText("");
        //String type="Deposit";
        //Date dateAndTime=new Date();
        //String balance="";
        try{
            if(accountNumber.equals(""))
            {
                if(accountNumber.equals(""))
                {
                    JOptionPane.showMessageDialog(null,"Account Number is Requied");
                }
                
            }else{
                Conn c=new Conn();
                String query="select * from balance where accountNumber = '"+accountNumber+"'";
                //c.s.executeUpdate(query);
                
                ResultSet rs = c.s.executeQuery(query);
                int balance=0;
                int count=0;
                    while(rs.next())
                    {
                        if(rs.getString("type").equals("Deposit"))
                        {
                            balance+=Integer.parseInt(rs.getString("amount"));
                        }else{
                            balance-=Integer.parseInt(rs.getString("amount"));
                        }count++;
                    }
                    if(count==0){
                        JOptionPane.showMessageDialog(null,"Incorrect Account Number");
                    }else{
                        balanceLabel.setText(balanceLabel.getText()+balance);
                    }
                    
                    
                }
                
            }
        catch(Exception e){
            System.out.println(e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_balanceCheckButtonActionPerformed

    private void closeBtnLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnLabelMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeBtnLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin11().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BalanceLabel;
    private javax.swing.JPanel admin11Panel;
    private javax.swing.JPanel admin11_2Panel;
    private javax.swing.JLabel adminPanelLabel;
    private javax.swing.JLabel balanceBtnLabel;
    private javax.swing.JPanel balanceBtnPanel;
    private javax.swing.JButton balanceCheckButton;
    private javax.swing.JLabel balanceCheckLabel;
    private javax.swing.JLabel balanceDepositWithdrawTransferLabel;
    private javax.swing.JLabel balanceLabel;
    private javax.swing.JPanel balancePanel;
    private javax.swing.JLabel closeBtnLabel;
    private javax.swing.JLabel depositBtnLabel;
    private javax.swing.JPanel depositBtnPanel;
    private javax.swing.JLabel enterAccountNumberLabel;
    private javax.swing.JTextField enterAccountNumberTextField;
    private javax.swing.JLabel exitBtnLabel;
    private javax.swing.JPanel exitBtnPanel;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel sideBarPanel;
    private javax.swing.JLabel transferBtnLabel;
    private javax.swing.JPanel transferBtnPanel;
    private javax.swing.JLabel withdrawBtnLabel;
    private javax.swing.JPanel withdrawBtnPanel;
    // End of variables declaration//GEN-END:variables
}
