
import java.awt.Color;
import java.awt.Font;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hp
 */
public class Admin16 extends javax.swing.JFrame {

    /**
     * Creates new form Admin16
     */
    String accountNumber;
    public Admin16() throws SQLException {
        initComponents();
        transactionTable.getTableHeader().setFont(new Font("Segoe UI",Font.BOLD,16));
        transactionTable.getTableHeader().setOpaque(false);
        transactionTable.getTableHeader().setBackground(new Color(102,0,153));
        transactionTable.getTableHeader().setForeground(new Color(255,255,255));
        transactionTable.setRowHeight(25);
        Conn c=new Conn();
        String query="select * from Message";
        
        //c.s.executeUpdate(query);
                
        ResultSet rs = c.s.executeQuery(query);
        
        
        
        while(rs.next())
        {
            String a=rs.getString("AccountNumber");
            String n=rs.getString("Name");
            String m=rs.getString("Message");
            String tbData[]={a,n,m};
            DefaultTableModel  tb1Model=(DefaultTableModel)transactionTable.getModel();
            tb1Model.addRow(tbData);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        password3Panel = new javax.swing.JPanel();
        password3_2Panel = new javax.swing.JPanel();
        forgotPasswordLabel = new javax.swing.JLabel();
        logoLabel = new javax.swing.JLabel();
        closeBtnLabel = new javax.swing.JLabel();
        closeBtnLabel1 = new javax.swing.JLabel();
        accountTextField = new javax.swing.JTextField();
        searchLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        messageTextArea = new javax.swing.JTextArea();
        messageTextField = new javax.swing.JTextField();
        sendMessageLabel = new javax.swing.JLabel();
        forgotPasswordLabel2 = new javax.swing.JLabel();
        forgotPasswordLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        transactionTable = new javax.swing.JTable();
        adminPanelLabel = new javax.swing.JLabel();
        balanceDepositWithdrawTransferLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        password3Panel.setBackground(new java.awt.Color(102, 0, 153));
        password3Panel.setPreferredSize(new java.awt.Dimension(1120, 630));

        password3_2Panel.setBackground(new java.awt.Color(255, 255, 255));
        password3_2Panel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        password3_2Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        forgotPasswordLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        forgotPasswordLabel.setForeground(new java.awt.Color(102, 0, 153));
        forgotPasswordLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        forgotPasswordLabel.setText("Write Reply");
        password3_2Panel.add(forgotPasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 450, 100, 30));

        logoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/verified-mail.png"))); // NOI18N
        password3_2Panel.add(logoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 1021, -1));

        closeBtnLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/goback.png"))); // NOI18N
        closeBtnLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBtnLabelMouseClicked(evt);
            }
        });
        password3_2Panel.add(closeBtnLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        closeBtnLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/close-btn.png"))); // NOI18N
        closeBtnLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBtnLabel1MouseClicked(evt);
            }
        });
        password3_2Panel.add(closeBtnLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 10, 30, -1));

        accountTextField.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
        accountTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountTextFieldActionPerformed(evt);
            }
        });
        password3_2Panel.add(accountTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 200, 370, 40));

        searchLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/goback.png"))); // NOI18N
        searchLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchLabelMouseClicked(evt);
            }
        });
        password3_2Panel.add(searchLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 200, -1, 40));

        messageTextArea.setColumns(20);
        messageTextArea.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
        messageTextArea.setRows(5);
        jScrollPane1.setViewportView(messageTextArea);

        password3_2Panel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 270, 410, 180));

        messageTextField.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
        messageTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                messageTextFieldActionPerformed(evt);
            }
        });
        password3_2Panel.add(messageTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 480, 370, 40));

        sendMessageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/goback.png"))); // NOI18N
        sendMessageLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sendMessageLabelMouseClicked(evt);
            }
        });
        password3_2Panel.add(sendMessageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 480, -1, 40));

        forgotPasswordLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        forgotPasswordLabel2.setForeground(new java.awt.Color(102, 0, 153));
        forgotPasswordLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        forgotPasswordLabel2.setText("Search Account");
        password3_2Panel.add(forgotPasswordLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 170, 130, 30));

        forgotPasswordLabel3.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        forgotPasswordLabel3.setForeground(new java.awt.Color(102, 0, 153));
        forgotPasswordLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        forgotPasswordLabel3.setText("All Message");
        password3_2Panel.add(forgotPasswordLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, 100, 30));

        transactionTable.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 15)); // NOI18N
        transactionTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Account Number", "Name", "Message"
            }
        ));
        transactionTable.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(transactionTable);

        password3_2Panel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, 339));

        adminPanelLabel.setBackground(new java.awt.Color(0, 0, 0));
        adminPanelLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 3, 36)); // NOI18N
        adminPanelLabel.setForeground(new java.awt.Color(102, 0, 153));
        adminPanelLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        adminPanelLabel.setText("ADMIN PANEL");
        password3_2Panel.add(adminPanelLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 970, -1));

        balanceDepositWithdrawTransferLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        balanceDepositWithdrawTransferLabel.setForeground(new java.awt.Color(102, 0, 153));
        balanceDepositWithdrawTransferLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        balanceDepositWithdrawTransferLabel.setText("Chat With Customers");
        password3_2Panel.add(balanceDepositWithdrawTransferLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 50, 950, -1));

        javax.swing.GroupLayout password3PanelLayout = new javax.swing.GroupLayout(password3Panel);
        password3Panel.setLayout(password3PanelLayout);
        password3PanelLayout.setHorizontalGroup(
            password3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, password3PanelLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(password3_2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 1048, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        password3PanelLayout.setVerticalGroup(
            password3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(password3PanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(password3_2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        getContentPane().add(password3Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeBtnLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnLabelMouseClicked
            Admin4 A4 = new Admin4();
            setVisible(false);
            A4.setVisible(true);
            dispose();

    }//GEN-LAST:event_closeBtnLabelMouseClicked

    private void closeBtnLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnLabel1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeBtnLabel1MouseClicked

    private void accountTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accountTextFieldActionPerformed

    private void searchLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchLabelMouseClicked
        // TODO add your handling code here:
        accountNumber=accountTextField.getText();
        
        try{
            if(accountNumber.equals(""))
            {
                if(accountNumber.equals(""))
                {
                    JOptionPane.showMessageDialog(null,"Account Number is Requied");
                }
                
            }else{
                Conn c=new Conn();
                String query="select * from Message where accountNumber = '"+accountNumber+"'";
                //c.s.executeUpdate(query);
                
                ResultSet rs = c.s.executeQuery(query);
                int count=0;
                messageTextArea.setText("");
                    while(rs.next())
                    {
                        count++;
                        String name=rs.getString("Name");
                        String message=rs.getString("Message");
                //System.out.println("Asik\nHossain");
                messageTextArea.setText(messageTextArea.getText()+"\n "+name+" : "+message+"\n");
                
               // m=m+name+" : "+message+"\n";count++;
                    }
                    if(count==0){
                        JOptionPane.showMessageDialog(null,"Incorrect Account Number");
                    }
                    
                    
                }
                
            }
        catch(Exception e){
            System.out.println(e);
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_searchLabelMouseClicked

    private void messageTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_messageTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_messageTextFieldActionPerformed

    private void sendMessageLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendMessageLabelMouseClicked
        

            String message=messageTextField.getText();
            String name="Bank";
            Conn c=new Conn();

            try{
                if(message.equals(""))
                {
                    if(message.equals(""))
                    {
                        JOptionPane.showMessageDialog(null,"Write Any Reply For Send");
                    }
                }else{
                    //Conn c=new Conn();
                    String query1="insert into Message values('"+accountNumber+"', '"+name+"', '"+message+"')";
                    c.s.executeUpdate(query1);
                    //JOptionPane.showMessageDialog(null,"Thank You For Reply");
                    messageTextField.setText("");
                    
                    
                    
                    
                    String query="select * from Message where accountNumber = '"+accountNumber+"'";
                //c.s.executeUpdate(query);
                
                ResultSet rs = c.s.executeQuery(query);
                //int count=0;
                messageTextArea.setText("");
                    while(rs.next())
                    {
                        //count++;
                        String name1=rs.getString("Name");
                        String message2=rs.getString("Message");
                //System.out.println("Asik\nHossain");
                messageTextArea.setText(messageTextArea.getText()+"\n "+name1+" : "+message2+"\n");
                
               // m=m+name+" : "+message+"\n";count++;
                    }
                    
                    
                    
                    
                    transactionTable.getTableHeader().setFont(new Font("Segoe UI",Font.BOLD,16));
                    transactionTable.getTableHeader().setOpaque(false);
                    transactionTable.getTableHeader().setBackground(new Color(102,0,153));
                    transactionTable.getTableHeader().setForeground(new Color(255,255,255));
                    transactionTable.setRowHeight(25);
                    String query2="select * from Message";

                    //c.s.executeUpdate(query);

                    ResultSet rs2 = c.s.executeQuery(query2);



                    while(rs2.next())
                    {
                        String a=rs2.getString("AccountNumber");
                        String n=rs2.getString("Name");
                        String m=rs2.getString("Message");
                        String tbData[]={a,n,m};
                        DefaultTableModel  tb1Model=(DefaultTableModel)transactionTable.getModel();
                        tb1Model.addRow(tbData);
                    }


                            }
                        }catch(Exception e){
                            System.out.println(e);
                        }
            // TODO add your handling code here:
        
    }//GEN-LAST:event_sendMessageLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin16.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin16.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin16.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin16.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Admin16().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Admin16.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accountTextField;
    private javax.swing.JLabel adminPanelLabel;
    private javax.swing.JLabel balanceDepositWithdrawTransferLabel;
    private javax.swing.JLabel closeBtnLabel;
    private javax.swing.JLabel closeBtnLabel1;
    private javax.swing.JLabel forgotPasswordLabel;
    private javax.swing.JLabel forgotPasswordLabel2;
    private javax.swing.JLabel forgotPasswordLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JTextArea messageTextArea;
    private javax.swing.JTextField messageTextField;
    private javax.swing.JPanel password3Panel;
    private javax.swing.JPanel password3_2Panel;
    private javax.swing.JLabel searchLabel;
    private javax.swing.JLabel sendMessageLabel;
    private javax.swing.JTable transactionTable;
    // End of variables declaration//GEN-END:variables
}
