
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hp
 */
public class Admin2 extends javax.swing.JFrame {

    /**
     * Creates new form Admin2
     */
    String accountNumber;
    public Admin2(String accountNumber) throws SQLException {
        this.accountNumber=accountNumber;
        initComponents();
        Conn c=new Conn();

        int count=1;
        
        
        if(count>=0)
        {
            String query1="select * from addApplication1 where accountNumber = '"+accountNumber+"'";
                
            ResultSet rs1 = c.s.executeQuery(query1);
            if(rs1.next())
            {
                String fName=rs1.getString("firstName");
                String LName=rs1.getString("lastName");
                String FatherName=rs1.getString("fathersName");
                String dob=rs1.getString("dateOfBirth");
                String gender=rs1.getString("gender");
                String ms=rs1.getString("maritalStatus");
                String pNum=rs1.getString("phoneNumber");
                String email=rs1.getString("emailAddress");
                FirstNameLabel2.setText(FirstNameLabel2.getText()+fName);
                LastNameLabel2.setText(LastNameLabel2.getText()+LName);
                FathersNameLabel2.setText(FathersNameLabel2.getText()+FatherName);
                dateOfBirthLabel2.setText(dateOfBirthLabel2.getText()+dob);
                genderLabel2.setText(genderLabel2.getText()+gender);
                MeritalStatusLabel2.setText(MeritalStatusLabel2.getText()+ms);
                PhoneNumberLabel2.setText(PhoneNumberLabel2.getText()+pNum);
                EmailAddressLabel2.setText(EmailAddressLabel2.getText()+email);
                
                
                
                
                
                
            }
            
        }
        if(count>=0)
        {
            String query1="select * from addApplication2_1 where accountNumber = '"+accountNumber+"'";
                
            ResultSet rs1 = c.s.executeQuery(query1);
            if(rs1.next())
            {
                String address=rs1.getString("presentAddress");
                String paddress=rs1.getString("permanentAddress");
                String city=rs1.getString("city");
                String pcode=rs1.getString("postCode");
                String religion=rs1.getString("religion");
                String n=rs1.getString("nationality");
                String edu=rs1.getString("educationQualification");
                String o=rs1.getString("occupation");
                PresentAddressLabel2.setText(PresentAddressLabel2.getText()+address);
                PermanentAddressLabel2.setText(PermanentAddressLabel2.getText()+paddress);
                CityLabel2.setText(CityLabel2.getText()+city);
                postCodeLabel.setText(PostCodeLabel2.getText()+pcode);
                ReligionLabel2.setText(ReligionLabel2.getText()+religion);
                nationalLabel.setText(NationalityLabel2.getText()+n);
                EducationQualificationLabel2.setText(EducationQualificationLabel2.getText()+edu);
                OccupationLabel2.setText(OccupationLabel2.getText()+o);
                
                
                
                
                
                
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        admin2Panel = new javax.swing.JPanel();
        sideBarPanel = new javax.swing.JPanel();
        searchBtnPanel = new javax.swing.JPanel();
        searchBtnLabel = new javax.swing.JLabel();
        statementBtnPanel = new javax.swing.JPanel();
        statementBtnLabel = new javax.swing.JLabel();
        profileBtnPanel = new javax.swing.JPanel();
        profileBtnLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        exitBtnPanel = new javax.swing.JPanel();
        exitBtnLabel = new javax.swing.JLabel();
        admin2_2Panel = new javax.swing.JPanel();
        personalInformationLabel = new javax.swing.JLabel();
        printButton = new javax.swing.JButton();
        editProfileButton = new javax.swing.JButton();
        FirstNameLabel = new javax.swing.JLabel();
        FathersNameLabel = new javax.swing.JLabel();
        genderLabel = new javax.swing.JLabel();
        PhoneNumberLabel = new javax.swing.JLabel();
        PresentAddressLabel = new javax.swing.JLabel();
        CityLabel = new javax.swing.JLabel();
        ReligionLabel = new javax.swing.JLabel();
        EducationQualificationLabel = new javax.swing.JLabel();
        LastNameLabel = new javax.swing.JLabel();
        dateOfBirthLabel = new javax.swing.JLabel();
        MeritalStatusLabel = new javax.swing.JLabel();
        EmailAddressLabel = new javax.swing.JLabel();
        PermanentAddressLabel = new javax.swing.JLabel();
        PostCodeLabel = new javax.swing.JLabel();
        NationalityLabel = new javax.swing.JLabel();
        OccupationLabel = new javax.swing.JLabel();
        FathersNameLabel2 = new javax.swing.JLabel();
        FirstNameLabel2 = new javax.swing.JLabel();
        genderLabel2 = new javax.swing.JLabel();
        PhoneNumberLabel2 = new javax.swing.JLabel();
        PresentAddressLabel2 = new javax.swing.JLabel();
        CityLabel2 = new javax.swing.JLabel();
        ReligionLabel2 = new javax.swing.JLabel();
        EducationQualificationLabel2 = new javax.swing.JLabel();
        LastNameLabel2 = new javax.swing.JLabel();
        dateOfBirthLabel2 = new javax.swing.JLabel();
        MeritalStatusLabel2 = new javax.swing.JLabel();
        EmailAddressLabel2 = new javax.swing.JLabel();
        PermanentAddressLabel2 = new javax.swing.JLabel();
        PostCodeLabel2 = new javax.swing.JLabel();
        NationalityLabel2 = new javax.swing.JLabel();
        OccupationLabel2 = new javax.swing.JLabel();
        postCodeLabel = new javax.swing.JLabel();
        nationalLabel = new javax.swing.JLabel();
        adminPanelLabel = new javax.swing.JLabel();
        searchAccountLabel = new javax.swing.JLabel();
        closeBtnLabel = new javax.swing.JLabel();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        admin2Panel.setBackground(new java.awt.Color(255, 255, 255));
        admin2Panel.setMinimumSize(new java.awt.Dimension(1120, 630));
        admin2Panel.setPreferredSize(new java.awt.Dimension(1120, 630));
        admin2Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sideBarPanel.setBackground(new java.awt.Color(102, 0, 153));

        searchBtnPanel.setBackground(new java.awt.Color(153, 0, 153));
        searchBtnPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchBtnPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchBtnPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchBtnPanelMouseExited(evt);
            }
        });

        searchBtnLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        searchBtnLabel.setForeground(new java.awt.Color(255, 255, 255));
        searchBtnLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        searchBtnLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/white-search-person.png"))); // NOI18N
        searchBtnLabel.setText(" Search");

        javax.swing.GroupLayout searchBtnPanelLayout = new javax.swing.GroupLayout(searchBtnPanel);
        searchBtnPanel.setLayout(searchBtnPanelLayout);
        searchBtnPanelLayout.setHorizontalGroup(
            searchBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchBtnPanelLayout.createSequentialGroup()
                .addComponent(searchBtnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        searchBtnPanelLayout.setVerticalGroup(
            searchBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchBtnPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchBtnLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addContainerGap())
        );

        statementBtnPanel.setBackground(new java.awt.Color(153, 0, 153));
        statementBtnPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                statementBtnPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                statementBtnPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                statementBtnPanelMouseExited(evt);
            }
        });

        statementBtnLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        statementBtnLabel.setForeground(new java.awt.Color(255, 255, 255));
        statementBtnLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        statementBtnLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/white-moneybag.png"))); // NOI18N
        statementBtnLabel.setText(" Statement");

        javax.swing.GroupLayout statementBtnPanelLayout = new javax.swing.GroupLayout(statementBtnPanel);
        statementBtnPanel.setLayout(statementBtnPanelLayout);
        statementBtnPanelLayout.setHorizontalGroup(
            statementBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statementBtnPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(statementBtnLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        statementBtnPanelLayout.setVerticalGroup(
            statementBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, statementBtnPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statementBtnLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addContainerGap())
        );

        profileBtnPanel.setBackground(new java.awt.Color(153, 0, 153));
        profileBtnPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileBtnPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                profileBtnPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                profileBtnPanelMouseExited(evt);
            }
        });

        profileBtnLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        profileBtnLabel.setForeground(new java.awt.Color(255, 255, 255));
        profileBtnLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        profileBtnLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/white-user-icon.png"))); // NOI18N
        profileBtnLabel.setText("Profile");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/white-indicate.png"))); // NOI18N

        javax.swing.GroupLayout profileBtnPanelLayout = new javax.swing.GroupLayout(profileBtnPanel);
        profileBtnPanel.setLayout(profileBtnPanelLayout);
        profileBtnPanelLayout.setHorizontalGroup(
            profileBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profileBtnPanelLayout.createSequentialGroup()
                .addComponent(profileBtnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        profileBtnPanelLayout.setVerticalGroup(
            profileBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profileBtnPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(profileBtnLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addContainerGap())
        );

        exitBtnPanel.setBackground(new java.awt.Color(153, 0, 153));
        exitBtnPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitBtnPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitBtnPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitBtnPanelMouseExited(evt);
            }
        });

        exitBtnLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        exitBtnLabel.setForeground(new java.awt.Color(255, 255, 255));
        exitBtnLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitBtnLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/white-close-icon.png"))); // NOI18N
        exitBtnLabel.setText(" Exit");

        javax.swing.GroupLayout exitBtnPanelLayout = new javax.swing.GroupLayout(exitBtnPanel);
        exitBtnPanel.setLayout(exitBtnPanelLayout);
        exitBtnPanelLayout.setHorizontalGroup(
            exitBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exitBtnPanelLayout.createSequentialGroup()
                .addComponent(exitBtnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        exitBtnPanelLayout.setVerticalGroup(
            exitBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exitBtnPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exitBtnLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout sideBarPanelLayout = new javax.swing.GroupLayout(sideBarPanel);
        sideBarPanel.setLayout(sideBarPanelLayout);
        sideBarPanelLayout.setHorizontalGroup(
            sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(searchBtnPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(statementBtnPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(profileBtnPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(exitBtnPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        sideBarPanelLayout.setVerticalGroup(
            sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarPanelLayout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(searchBtnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(profileBtnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(statementBtnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(exitBtnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        admin2Panel.add(sideBarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 654));

        admin2_2Panel.setBackground(new java.awt.Color(102, 0, 153));
        admin2_2Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        personalInformationLabel.setBackground(new java.awt.Color(0, 0, 0));
        personalInformationLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 36)); // NOI18N
        personalInformationLabel.setForeground(new java.awt.Color(255, 255, 255));
        personalInformationLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        personalInformationLabel.setText("Personal Information");
        admin2_2Panel.add(personalInformationLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 25, 948, -1));

        printButton.setBackground(new java.awt.Color(0, 51, 102));
        printButton.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        printButton.setForeground(new java.awt.Color(255, 255, 255));
        printButton.setText("Print");
        printButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        printButton.setMaximumSize(new java.awt.Dimension(120, 40));
        printButton.setMinimumSize(new java.awt.Dimension(120, 40));
        printButton.setPreferredSize(new java.awt.Dimension(120, 40));
        printButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButtonActionPerformed(evt);
            }
        });
        admin2_2Panel.add(printButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, 340, -1));

        editProfileButton.setBackground(new java.awt.Color(0, 51, 102));
        editProfileButton.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        editProfileButton.setForeground(new java.awt.Color(255, 255, 255));
        editProfileButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/white-user-icon.png"))); // NOI18N
        editProfileButton.setText("Edit Profile");
        editProfileButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editProfileButton.setMaximumSize(new java.awt.Dimension(120, 40));
        editProfileButton.setMinimumSize(new java.awt.Dimension(120, 40));
        editProfileButton.setPreferredSize(new java.awt.Dimension(120, 40));
        editProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editProfileButtonActionPerformed(evt);
            }
        });
        admin2_2Panel.add(editProfileButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 430, 340, -1));

        FirstNameLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        FirstNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        FirstNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        FirstNameLabel.setText("First Name :");
        admin2_2Panel.add(FirstNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        FathersNameLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        FathersNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        FathersNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        FathersNameLabel.setText("Father's Name :");
        admin2_2Panel.add(FathersNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 141, 110, -1));

        genderLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        genderLabel.setForeground(new java.awt.Color(255, 255, 255));
        genderLabel.setText("Gender :");
        admin2_2Panel.add(genderLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 175, -1, -1));

        PhoneNumberLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        PhoneNumberLabel.setForeground(new java.awt.Color(255, 255, 255));
        PhoneNumberLabel.setText("Phone Number :");
        admin2_2Panel.add(PhoneNumberLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 215, -1, -1));

        PresentAddressLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        PresentAddressLabel.setForeground(new java.awt.Color(255, 255, 255));
        PresentAddressLabel.setText("Present Address :");
        admin2_2Panel.add(PresentAddressLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 255, -1, -1));

        CityLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        CityLabel.setForeground(new java.awt.Color(255, 255, 255));
        CityLabel.setText("City :");
        admin2_2Panel.add(CityLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 293, -1, -1));

        ReligionLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        ReligionLabel.setForeground(new java.awt.Color(255, 255, 255));
        ReligionLabel.setText(" Religion :");
        admin2_2Panel.add(ReligionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 323, -1, 30));

        EducationQualificationLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        EducationQualificationLabel.setForeground(new java.awt.Color(255, 255, 255));
        EducationQualificationLabel.setText("Education Qualification :");
        admin2_2Panel.add(EducationQualificationLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 360, 160, 27));

        LastNameLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        LastNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        LastNameLabel.setText("Last Name :");
        admin2_2Panel.add(LastNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 110, -1, 20));

        dateOfBirthLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        dateOfBirthLabel.setForeground(new java.awt.Color(255, 255, 255));
        dateOfBirthLabel.setText("Date of Birth :");
        admin2_2Panel.add(dateOfBirthLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, -1, 32));

        MeritalStatusLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        MeritalStatusLabel.setForeground(new java.awt.Color(255, 255, 255));
        MeritalStatusLabel.setText("Merital Status :");
        admin2_2Panel.add(MeritalStatusLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 180, 100, -1));

        EmailAddressLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        EmailAddressLabel.setForeground(new java.awt.Color(255, 255, 255));
        EmailAddressLabel.setText("Email Address :");
        admin2_2Panel.add(EmailAddressLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 220, -1, -1));

        PermanentAddressLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        PermanentAddressLabel.setForeground(new java.awt.Color(255, 255, 255));
        PermanentAddressLabel.setText("Permanent Address :");
        admin2_2Panel.add(PermanentAddressLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, 140, 30));

        PostCodeLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        PostCodeLabel.setForeground(new java.awt.Color(255, 255, 255));
        PostCodeLabel.setText("Post Code :");
        admin2_2Panel.add(PostCodeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 290, -1, 20));

        NationalityLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        NationalityLabel.setForeground(new java.awt.Color(255, 255, 255));
        NationalityLabel.setText("Nationality :");
        admin2_2Panel.add(NationalityLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 320, -1, 30));

        OccupationLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        OccupationLabel.setForeground(new java.awt.Color(255, 255, 255));
        OccupationLabel.setText("Occupation :");
        admin2_2Panel.add(OccupationLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 360, 80, -1));

        FathersNameLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        FathersNameLabel2.setForeground(new java.awt.Color(255, 255, 255));
        admin2_2Panel.add(FathersNameLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 284, 40));

        FirstNameLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        FirstNameLabel2.setForeground(new java.awt.Color(255, 255, 255));
        admin2_2Panel.add(FirstNameLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 98, 284, 36));

        genderLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        genderLabel2.setForeground(new java.awt.Color(255, 255, 255));
        admin2_2Panel.add(genderLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 284, 30));

        PhoneNumberLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        PhoneNumberLabel2.setForeground(new java.awt.Color(255, 255, 255));
        admin2_2Panel.add(PhoneNumberLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 209, 284, 30));

        PresentAddressLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        PresentAddressLabel2.setForeground(new java.awt.Color(255, 255, 255));
        admin2_2Panel.add(PresentAddressLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 284, 27));

        CityLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        CityLabel2.setForeground(new java.awt.Color(255, 255, 255));
        admin2_2Panel.add(CityLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 284, 284, 34));

        ReligionLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        ReligionLabel2.setForeground(new java.awt.Color(255, 255, 255));
        admin2_2Panel.add(ReligionLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 325, 284, 28));

        EducationQualificationLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        EducationQualificationLabel2.setForeground(new java.awt.Color(255, 255, 255));
        admin2_2Panel.add(EducationQualificationLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 284, 33));

        LastNameLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        LastNameLabel2.setForeground(new java.awt.Color(255, 255, 255));
        admin2_2Panel.add(LastNameLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 100, 284, 36));

        dateOfBirthLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        dateOfBirthLabel2.setForeground(new java.awt.Color(255, 255, 255));
        admin2_2Panel.add(dateOfBirthLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 140, 284, 30));

        MeritalStatusLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        MeritalStatusLabel2.setForeground(new java.awt.Color(255, 255, 255));
        admin2_2Panel.add(MeritalStatusLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 170, 284, 40));

        EmailAddressLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        EmailAddressLabel2.setForeground(new java.awt.Color(255, 255, 255));
        admin2_2Panel.add(EmailAddressLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 210, 284, 40));

        PermanentAddressLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        PermanentAddressLabel2.setForeground(new java.awt.Color(255, 255, 255));
        admin2_2Panel.add(PermanentAddressLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 250, 284, 35));

        PostCodeLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        PostCodeLabel2.setForeground(new java.awt.Color(255, 255, 255));
        admin2_2Panel.add(PostCodeLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(887, 308, -1, 28));

        NationalityLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        NationalityLabel2.setForeground(new java.awt.Color(255, 255, 255));
        admin2_2Panel.add(NationalityLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(887, 343, -1, 34));

        OccupationLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        OccupationLabel2.setForeground(new java.awt.Color(255, 255, 255));
        admin2_2Panel.add(OccupationLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 350, 284, 33));

        postCodeLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        postCodeLabel.setForeground(new java.awt.Color(255, 255, 255));
        admin2_2Panel.add(postCodeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 290, 284, 20));

        nationalLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        nationalLabel.setForeground(new java.awt.Color(255, 255, 255));
        admin2_2Panel.add(nationalLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 320, 284, 30));

        admin2Panel.add(admin2_2Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 101, 930, 510));

        adminPanelLabel.setBackground(new java.awt.Color(0, 0, 0));
        adminPanelLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 3, 36)); // NOI18N
        adminPanelLabel.setForeground(new java.awt.Color(102, 0, 153));
        adminPanelLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        adminPanelLabel.setText("ADMIN PANEL");
        admin2Panel.add(adminPanelLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 13, 990, -1));

        searchAccountLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        searchAccountLabel.setForeground(new java.awt.Color(102, 0, 153));
        searchAccountLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        searchAccountLabel.setText("Search Account");
        admin2Panel.add(searchAccountLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 62, 977, -1));

        closeBtnLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/close-btn.png"))); // NOI18N
        closeBtnLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBtnLabelMouseClicked(evt);
            }
        });
        admin2Panel.add(closeBtnLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(admin2Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 1164, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(admin2Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 654, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void searchBtnPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchBtnPanelMouseClicked
        Admin1 A1= new Admin1();
        setVisible(false);
        A1.setVisible(true);
        dispose();
    }//GEN-LAST:event_searchBtnPanelMouseClicked

    private void searchBtnPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchBtnPanelMouseEntered
        JPanel btn= searchBtnPanel;
        isEntered(btn);
    }//GEN-LAST:event_searchBtnPanelMouseEntered

    private void searchBtnPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchBtnPanelMouseExited
        JPanel btn= searchBtnPanel;
        isExited(btn);
    }//GEN-LAST:event_searchBtnPanelMouseExited

    private void statementBtnPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statementBtnPanelMouseClicked
        Admin3 A3;
        try {
            A3 = new Admin3(accountNumber);
            setVisible(false);
            A3.setVisible(true);
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(Admin2.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_statementBtnPanelMouseClicked

    private void statementBtnPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statementBtnPanelMouseEntered
        JPanel btn= statementBtnPanel;
        isEntered(btn);
    }//GEN-LAST:event_statementBtnPanelMouseEntered

    private void statementBtnPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statementBtnPanelMouseExited
        JPanel btn= statementBtnPanel;
        isExited(btn);
    }//GEN-LAST:event_statementBtnPanelMouseExited

    private void profileBtnPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileBtnPanelMouseClicked
        /*Admin2 A2= new Admin2();
        setVisible(false);
        A2.setVisible(true);
        dispose();*/
    }//GEN-LAST:event_profileBtnPanelMouseClicked

    private void profileBtnPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileBtnPanelMouseEntered
        JPanel btn= profileBtnPanel;
        isEntered(btn);
    }//GEN-LAST:event_profileBtnPanelMouseEntered

    private void profileBtnPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileBtnPanelMouseExited
        JPanel btn= profileBtnPanel;
        isExited(btn);
    }//GEN-LAST:event_profileBtnPanelMouseExited

    private void exitBtnPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnPanelMouseClicked
        Admin4 A4= new Admin4();
        setVisible(false);
        A4.setVisible(true);
        dispose();
    }//GEN-LAST:event_exitBtnPanelMouseClicked

    private void exitBtnPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnPanelMouseEntered
        JPanel btn= exitBtnPanel;
        isEntered(btn);
    }//GEN-LAST:event_exitBtnPanelMouseEntered

    private void exitBtnPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnPanelMouseExited
        JPanel btn= exitBtnPanel;
        isExited(btn);
    }//GEN-LAST:event_exitBtnPanelMouseExited

    private void closeBtnLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnLabelMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeBtnLabelMouseClicked

    private void editProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editProfileButtonActionPerformed
        Admin15 A15;
        try {
            A15 = new Admin15(accountNumber);
            setVisible(false);
            A15.setVisible(true);
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(Admin2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_editProfileButtonActionPerformed

    private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_printButtonActionPerformed
    void isEntered(JPanel btn)
    {
        btn.setBackground(new Color(0,51,102));
    }
    
    void isExited(JPanel btn)
    {
        btn.setBackground(new Color(153,0,153));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Admin2("").setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Admin2.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CityLabel;
    private javax.swing.JLabel CityLabel2;
    private javax.swing.JLabel EducationQualificationLabel;
    private javax.swing.JLabel EducationQualificationLabel2;
    private javax.swing.JLabel EmailAddressLabel;
    private javax.swing.JLabel EmailAddressLabel2;
    private javax.swing.JLabel FathersNameLabel;
    private javax.swing.JLabel FathersNameLabel2;
    private javax.swing.JLabel FirstNameLabel;
    private javax.swing.JLabel FirstNameLabel2;
    private javax.swing.JLabel LastNameLabel;
    private javax.swing.JLabel LastNameLabel2;
    private javax.swing.JLabel MeritalStatusLabel;
    private javax.swing.JLabel MeritalStatusLabel2;
    private javax.swing.JLabel NationalityLabel;
    private javax.swing.JLabel NationalityLabel2;
    private javax.swing.JLabel OccupationLabel;
    private javax.swing.JLabel OccupationLabel2;
    private javax.swing.JLabel PermanentAddressLabel;
    private javax.swing.JLabel PermanentAddressLabel2;
    private javax.swing.JLabel PhoneNumberLabel;
    private javax.swing.JLabel PhoneNumberLabel2;
    private javax.swing.JLabel PostCodeLabel;
    private javax.swing.JLabel PostCodeLabel2;
    private javax.swing.JLabel PresentAddressLabel;
    private javax.swing.JLabel PresentAddressLabel2;
    private javax.swing.JLabel ReligionLabel;
    private javax.swing.JLabel ReligionLabel2;
    private javax.swing.JPanel admin2Panel;
    private javax.swing.JPanel admin2_2Panel;
    private javax.swing.JLabel adminPanelLabel;
    private javax.swing.JLabel closeBtnLabel;
    private javax.swing.JLabel dateOfBirthLabel;
    private javax.swing.JLabel dateOfBirthLabel2;
    private javax.swing.JButton editProfileButton;
    private javax.swing.JLabel exitBtnLabel;
    private javax.swing.JPanel exitBtnPanel;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JLabel genderLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel nationalLabel;
    private javax.swing.JLabel personalInformationLabel;
    private javax.swing.JLabel postCodeLabel;
    private javax.swing.JButton printButton;
    private javax.swing.JLabel profileBtnLabel;
    private javax.swing.JPanel profileBtnPanel;
    private javax.swing.JLabel searchAccountLabel;
    private javax.swing.JLabel searchBtnLabel;
    private javax.swing.JPanel searchBtnPanel;
    private javax.swing.JPanel sideBarPanel;
    private javax.swing.JLabel statementBtnLabel;
    private javax.swing.JPanel statementBtnPanel;
    // End of variables declaration//GEN-END:variables
}
