
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hp
 */
public class Cards extends javax.swing.JFrame {

    /**
     * Creates new form Cards
     */
    String accountNumber;
    public Cards(String accountNumber) throws SQLException {
        this.accountNumber=accountNumber;
        initComponents();
        Conn c=new Conn();
        String query="select * from balance where accountNumber = '"+accountNumber+"'";
        
        //c.s.executeUpdate(query);
                
        ResultSet rs = c.s.executeQuery(query);
        
        int balance=0;
        int count=0;
        while(rs.next())
        {
            if(rs.getString("type").equals("Deposit"))
            {
                balance+=Integer.parseInt(rs.getString("amount"));
            }else{
                balance-=Integer.parseInt(rs.getString("amount"));
            }count++;
        }
        System.out.println(balance);
        balanceLabel2.setText(balanceLabel2.getText()+"Taka "+balance);
        double balance2=0;
        balance2=(balance/105.64);
        DecimalFormat df= new DecimalFormat("#.###");
        balanceLabel12.setText(balanceLabel12.getText()+"$ "+df.format(balance2));
        
        if(balance2>=0)
        {
            String query1="select * from addApplication3 where accountNumber = '"+accountNumber+"'";
            ResultSet rs1 = c.s.executeQuery(query1);
            if(rs1.next())
            {
                String credit=rs1.getString("creditCardNumber");
                String debit=rs1.getString("debitCardNumber");
                cardNumberLabel12.setText(cardNumberLabel12.getText()+credit);
                cardNumberLabel2.setText(cardNumberLabel2.getText()+debit);
                cardLabel2.setText(cardLabel2.getText()+credit);
                cardLabel1.setText(cardLabel1.getText()+debit);
            }
            
        }
        if(balance2>=0)
        {
            String query1="select * from addApplication1 where accountNumber = '"+accountNumber+"'";
                
            ResultSet rs1 = c.s.executeQuery(query1);
            if(rs1.next())
            {
                String fName=rs1.getString("firstName");
                String LName=rs1.getString("lastName");
                nameLabel2.setText(nameLabel2.getText()+"\n"+fName+" "+LName);
                nameLabel1.setText(nameLabel1.getText()+"\n"+fName+" "+LName);
            }
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        sideBarPanel = new javax.swing.JPanel();
        homeBtnPanel = new javax.swing.JPanel();
        homeBtnLabel = new javax.swing.JLabel();
        transferBtnPanel = new javax.swing.JPanel();
        transferBtnLabel = new javax.swing.JLabel();
        accountBtnPanel = new javax.swing.JPanel();
        accountBtnLabel = new javax.swing.JLabel();
        cardsBtnPanel = new javax.swing.JPanel();
        cardsBtnLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        profileBtnPanel = new javax.swing.JPanel();
        profileBtnLabel = new javax.swing.JLabel();
        logoutBtnPanel = new javax.swing.JPanel();
        logoutBtnLabel = new javax.swing.JLabel();
        debitCardPanel = new javax.swing.JPanel();
        cardpanel1 = new javax.swing.JPanel();
        logoLabel1 = new javax.swing.JLabel();
        creditCardLabel1 = new javax.swing.JLabel();
        cardLabel1 = new javax.swing.JLabel();
        logoLabel3 = new javax.swing.JLabel();
        nameLabel1 = new javax.swing.JLabel();
        cardDLabel1 = new javax.swing.JLabel();
        creditCardTypeLabel2 = new javax.swing.JLabel();
        cardNumberLabel1 = new javax.swing.JLabel();
        cVVNumberLabel2 = new javax.swing.JLabel();
        cardIssuedDateLabel2 = new javax.swing.JLabel();
        balanceLabel = new javax.swing.JLabel();
        cardExpiryDateLabel2 = new javax.swing.JLabel();
        interestRateLabel2 = new javax.swing.JLabel();
        cardIssuedDateLabel1 = new javax.swing.JLabel();
        cardExpiryDateLabel1 = new javax.swing.JLabel();
        balanceLabel2 = new javax.swing.JLabel();
        interestRateLabel1 = new javax.swing.JLabel();
        creditCardTypeLabel1 = new javax.swing.JLabel();
        cVVNumberLabel1 = new javax.swing.JLabel();
        cardNumberLabel2 = new javax.swing.JLabel();
        debitPinPanel = new javax.swing.JPanel();
        enterNewPinPasswordField1 = new javax.swing.JPasswordField();
        reEnterPinPasswordField1 = new javax.swing.JPasswordField();
        changePinButton1 = new javax.swing.JButton();
        enterNewPinLabel1 = new javax.swing.JLabel();
        reEnterPinLabel1 = new javax.swing.JLabel();
        headingLabel1 = new javax.swing.JLabel();
        creditCardPanel = new javax.swing.JPanel();
        creditCardTypeLabel4 = new javax.swing.JLabel();
        cardNumberLabel11 = new javax.swing.JLabel();
        cVVNumberLabel4 = new javax.swing.JLabel();
        cardIssuedDateLabel4 = new javax.swing.JLabel();
        balanceLabel11 = new javax.swing.JLabel();
        cardExpiryDateLabel4 = new javax.swing.JLabel();
        interestRateLabel4 = new javax.swing.JLabel();
        cardIssuedDateLabel3 = new javax.swing.JLabel();
        cardExpiryDateLabel3 = new javax.swing.JLabel();
        balanceLabel12 = new javax.swing.JLabel();
        interestRateLabel3 = new javax.swing.JLabel();
        creditCardTypeLabel3 = new javax.swing.JLabel();
        cVVNumberLabel3 = new javax.swing.JLabel();
        cardNumberLabel12 = new javax.swing.JLabel();
        cardpanel2 = new javax.swing.JPanel();
        logoLabel2 = new javax.swing.JLabel();
        creditCardLabel2 = new javax.swing.JLabel();
        cardLabel2 = new javax.swing.JLabel();
        logoLabel4 = new javax.swing.JLabel();
        nameLabel2 = new javax.swing.JLabel();
        cardDLabel2 = new javax.swing.JLabel();
        creditCardDetailsLabel = new javax.swing.JLabel();
        changeDebitCardPinCardLabel = new javax.swing.JLabel();
        debitCardDetailsLabel = new javax.swing.JLabel();
        changeCreditCardPinCardLabel = new javax.swing.JLabel();
        debitPinPanel1 = new javax.swing.JPanel();
        enterNewPinPasswordField2 = new javax.swing.JPasswordField();
        reEnterPinPasswordField2 = new javax.swing.JPasswordField();
        changePinButton2 = new javax.swing.JButton();
        enterNewPinLabel2 = new javax.swing.JLabel();
        reEnterPinLabel2 = new javax.swing.JLabel();
        closeBtnLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        backgroundPanel.setBackground(new java.awt.Color(255, 255, 255));
        backgroundPanel.setMinimumSize(new java.awt.Dimension(1120, 630));
        backgroundPanel.setPreferredSize(new java.awt.Dimension(1120, 630));
        backgroundPanel.setRequestFocusEnabled(false);
        backgroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sideBarPanel.setBackground(new java.awt.Color(0, 51, 255));

        homeBtnPanel.setBackground(new java.awt.Color(0, 0, 255));
        homeBtnPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeBtnPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeBtnPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeBtnPanelMouseExited(evt);
            }
        });

        homeBtnLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        homeBtnLabel.setForeground(new java.awt.Color(255, 255, 255));
        homeBtnLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homeBtnLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/white-home.png"))); // NOI18N
        homeBtnLabel.setText(" Home");

        javax.swing.GroupLayout homeBtnPanelLayout = new javax.swing.GroupLayout(homeBtnPanel);
        homeBtnPanel.setLayout(homeBtnPanelLayout);
        homeBtnPanelLayout.setHorizontalGroup(
            homeBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeBtnPanelLayout.createSequentialGroup()
                .addComponent(homeBtnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        homeBtnPanelLayout.setVerticalGroup(
            homeBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homeBtnPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homeBtnLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addContainerGap())
        );

        transferBtnPanel.setBackground(new java.awt.Color(0, 0, 255));
        transferBtnPanel.setPreferredSize(new java.awt.Dimension(118, 65));
        transferBtnPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transferBtnPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                transferBtnPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                transferBtnPanelMouseExited(evt);
            }
        });

        transferBtnLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        transferBtnLabel.setForeground(new java.awt.Color(255, 255, 255));
        transferBtnLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        transferBtnLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/transfer-icon.png"))); // NOI18N
        transferBtnLabel.setText(" Transfer");

        javax.swing.GroupLayout transferBtnPanelLayout = new javax.swing.GroupLayout(transferBtnPanel);
        transferBtnPanel.setLayout(transferBtnPanelLayout);
        transferBtnPanelLayout.setHorizontalGroup(
            transferBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(transferBtnLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        transferBtnPanelLayout.setVerticalGroup(
            transferBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transferBtnPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(transferBtnLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addContainerGap())
        );

        accountBtnPanel.setBackground(new java.awt.Color(0, 0, 255));
        accountBtnPanel.setPreferredSize(new java.awt.Dimension(118, 65));
        accountBtnPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accountBtnPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                accountBtnPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                accountBtnPanelMouseExited(evt);
            }
        });

        accountBtnLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        accountBtnLabel.setForeground(new java.awt.Color(255, 255, 255));
        accountBtnLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        accountBtnLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/white-moneybag.png"))); // NOI18N
        accountBtnLabel.setText(" Account");

        javax.swing.GroupLayout accountBtnPanelLayout = new javax.swing.GroupLayout(accountBtnPanel);
        accountBtnPanel.setLayout(accountBtnPanelLayout);
        accountBtnPanelLayout.setHorizontalGroup(
            accountBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(accountBtnLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        accountBtnPanelLayout.setVerticalGroup(
            accountBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, accountBtnPanelLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(accountBtnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        cardsBtnPanel.setBackground(new java.awt.Color(0, 0, 255));
        cardsBtnPanel.setPreferredSize(new java.awt.Dimension(118, 65));
        cardsBtnPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cardsBtnPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cardsBtnPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cardsBtnPanelMouseExited(evt);
            }
        });

        cardsBtnLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        cardsBtnLabel.setForeground(new java.awt.Color(255, 255, 255));
        cardsBtnLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cardsBtnLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/white-card.png"))); // NOI18N
        cardsBtnLabel.setText(" Cards");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/white-indicate.png"))); // NOI18N

        javax.swing.GroupLayout cardsBtnPanelLayout = new javax.swing.GroupLayout(cardsBtnPanel);
        cardsBtnPanel.setLayout(cardsBtnPanelLayout);
        cardsBtnPanelLayout.setHorizontalGroup(
            cardsBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardsBtnPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cardsBtnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        cardsBtnPanelLayout.setVerticalGroup(
            cardsBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
            .addGroup(cardsBtnPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cardsBtnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        profileBtnPanel.setBackground(new java.awt.Color(0, 0, 255));
        profileBtnPanel.setPreferredSize(new java.awt.Dimension(118, 65));
        profileBtnPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileBtnPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                profileBtnPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                profileBtnPanelMouseExited(evt);
            }
        });

        profileBtnLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        profileBtnLabel.setForeground(new java.awt.Color(255, 255, 255));
        profileBtnLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        profileBtnLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/white-user-icon.png"))); // NOI18N
        profileBtnLabel.setText(" Profile");

        javax.swing.GroupLayout profileBtnPanelLayout = new javax.swing.GroupLayout(profileBtnPanel);
        profileBtnPanel.setLayout(profileBtnPanelLayout);
        profileBtnPanelLayout.setHorizontalGroup(
            profileBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profileBtnPanelLayout.createSequentialGroup()
                .addComponent(profileBtnLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        profileBtnPanelLayout.setVerticalGroup(
            profileBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profileBtnPanelLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(profileBtnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        logoutBtnPanel.setBackground(new java.awt.Color(0, 0, 255));
        logoutBtnPanel.setPreferredSize(new java.awt.Dimension(118, 65));
        logoutBtnPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutBtnPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutBtnPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutBtnPanelMouseExited(evt);
            }
        });

        logoutBtnLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        logoutBtnLabel.setForeground(new java.awt.Color(255, 255, 255));
        logoutBtnLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoutBtnLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/white-logout-logo.png"))); // NOI18N
        logoutBtnLabel.setText(" Logout");

        javax.swing.GroupLayout logoutBtnPanelLayout = new javax.swing.GroupLayout(logoutBtnPanel);
        logoutBtnPanel.setLayout(logoutBtnPanelLayout);
        logoutBtnPanelLayout.setHorizontalGroup(
            logoutBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoutBtnPanelLayout.createSequentialGroup()
                .addComponent(logoutBtnLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        logoutBtnPanelLayout.setVerticalGroup(
            logoutBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoutBtnPanelLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(logoutBtnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout sideBarPanelLayout = new javax.swing.GroupLayout(sideBarPanel);
        sideBarPanel.setLayout(sideBarPanelLayout);
        sideBarPanelLayout.setHorizontalGroup(
            sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homeBtnPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(transferBtnPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
            .addComponent(accountBtnPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
            .addComponent(cardsBtnPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
            .addComponent(profileBtnPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
            .addComponent(logoutBtnPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        sideBarPanelLayout.setVerticalGroup(
            sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarPanelLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(homeBtnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(transferBtnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(accountBtnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(cardsBtnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(profileBtnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(logoutBtnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        backgroundPanel.add(sideBarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        debitCardPanel.setBackground(new java.awt.Color(255, 255, 255));
        debitCardPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        cardpanel1.setBackground(new java.awt.Color(255, 255, 255));
        cardpanel1.setForeground(new java.awt.Color(255, 255, 255));
        cardpanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoLabel1.setBackground(new java.awt.Color(255, 255, 255));
        logoLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        logoLabel1.setForeground(new java.awt.Color(255, 255, 255));
        logoLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/mastercard-icon.png"))); // NOI18N
        cardpanel1.add(logoLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        creditCardLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 16)); // NOI18N
        creditCardLabel1.setForeground(new java.awt.Color(255, 255, 255));
        creditCardLabel1.setText("Debit Card");
        cardpanel1.add(creditCardLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        cardLabel1.setBackground(new java.awt.Color(255, 255, 255));
        cardLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 15)); // NOI18N
        cardLabel1.setForeground(new java.awt.Color(255, 255, 255));
        cardpanel1.add(cardLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 260, 30));

        logoLabel3.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        logoLabel3.setForeground(new java.awt.Color(255, 255, 255));
        logoLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/silver-card-chip.png"))); // NOI18N
        cardpanel1.add(logoLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 250, -1));

        nameLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 15)); // NOI18N
        nameLabel1.setForeground(new java.awt.Color(255, 255, 255));
        cardpanel1.add(nameLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 260, 30));

        cardDLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/new card.png"))); // NOI18N
        cardpanel1.add(cardDLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, -1));

        creditCardTypeLabel2.setBackground(new java.awt.Color(255, 255, 255));
        creditCardTypeLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        creditCardTypeLabel2.setForeground(new java.awt.Color(102, 102, 102));
        creditCardTypeLabel2.setText("Credit Card Type :");

        cardNumberLabel1.setBackground(new java.awt.Color(255, 255, 255));
        cardNumberLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        cardNumberLabel1.setForeground(new java.awt.Color(102, 102, 102));
        cardNumberLabel1.setText("Card Number :");

        cVVNumberLabel2.setBackground(new java.awt.Color(255, 255, 255));
        cVVNumberLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        cVVNumberLabel2.setForeground(new java.awt.Color(102, 102, 102));
        cVVNumberLabel2.setText("CVV Number :");

        cardIssuedDateLabel2.setBackground(new java.awt.Color(255, 255, 255));
        cardIssuedDateLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        cardIssuedDateLabel2.setForeground(new java.awt.Color(102, 102, 102));
        cardIssuedDateLabel2.setText("Card Issued Date :");

        balanceLabel.setBackground(new java.awt.Color(255, 255, 255));
        balanceLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        balanceLabel.setForeground(new java.awt.Color(102, 102, 102));
        balanceLabel.setText("Balance :");

        cardExpiryDateLabel2.setBackground(new java.awt.Color(255, 255, 255));
        cardExpiryDateLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        cardExpiryDateLabel2.setForeground(new java.awt.Color(102, 102, 102));
        cardExpiryDateLabel2.setText("Card Expiry Date :");

        interestRateLabel2.setBackground(new java.awt.Color(255, 255, 255));
        interestRateLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        interestRateLabel2.setForeground(new java.awt.Color(102, 102, 102));
        interestRateLabel2.setText("Interest Rate :");

        cardIssuedDateLabel1.setBackground(new java.awt.Color(255, 255, 255));
        cardIssuedDateLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        cardIssuedDateLabel1.setText("01-02-2023");

        cardExpiryDateLabel1.setBackground(new java.awt.Color(255, 255, 255));
        cardExpiryDateLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        cardExpiryDateLabel1.setText("01-02-2028");

        balanceLabel2.setBackground(new java.awt.Color(255, 255, 255));
        balanceLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N

        interestRateLabel1.setBackground(new java.awt.Color(255, 255, 255));
        interestRateLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        interestRateLabel1.setText("0%");

        creditCardTypeLabel1.setBackground(new java.awt.Color(255, 255, 255));
        creditCardTypeLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        creditCardTypeLabel1.setText("Silver");

        cVVNumberLabel1.setBackground(new java.awt.Color(255, 255, 255));
        cVVNumberLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        cVVNumberLabel1.setText("876");

        cardNumberLabel2.setBackground(new java.awt.Color(255, 255, 255));
        cardNumberLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N

        javax.swing.GroupLayout debitCardPanelLayout = new javax.swing.GroupLayout(debitCardPanel);
        debitCardPanel.setLayout(debitCardPanelLayout);
        debitCardPanelLayout.setHorizontalGroup(
            debitCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(debitCardPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(debitCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(debitCardPanelLayout.createSequentialGroup()
                        .addComponent(cardExpiryDateLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cardExpiryDateLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(debitCardPanelLayout.createSequentialGroup()
                        .addComponent(balanceLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(balanceLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(debitCardPanelLayout.createSequentialGroup()
                        .addComponent(interestRateLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(interestRateLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(debitCardPanelLayout.createSequentialGroup()
                        .addGroup(debitCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cVVNumberLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cardNumberLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(debitCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cVVNumberLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cardNumberLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(debitCardPanelLayout.createSequentialGroup()
                        .addGroup(debitCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(debitCardPanelLayout.createSequentialGroup()
                                .addComponent(cardIssuedDateLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cardIssuedDateLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cardpanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(debitCardPanelLayout.createSequentialGroup()
                                .addComponent(creditCardTypeLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(creditCardTypeLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        debitCardPanelLayout.setVerticalGroup(
            debitCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(debitCardPanelLayout.createSequentialGroup()
                .addComponent(cardpanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(debitCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(creditCardTypeLabel2)
                    .addComponent(creditCardTypeLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(debitCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cardNumberLabel1)
                    .addComponent(cardNumberLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(debitCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cVVNumberLabel2)
                    .addComponent(cVVNumberLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(debitCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cardIssuedDateLabel2)
                    .addComponent(cardIssuedDateLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(debitCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cardExpiryDateLabel2)
                    .addComponent(cardExpiryDateLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(debitCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(balanceLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(balanceLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(debitCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(interestRateLabel2)
                    .addComponent(interestRateLabel1))
                .addGap(38, 38, 38))
        );

        backgroundPanel.add(debitCardPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 114, -1, -1));

        debitPinPanel.setBackground(new java.awt.Color(255, 255, 255));
        debitPinPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        enterNewPinPasswordField1.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        enterNewPinPasswordField1.setToolTipText("Please Enter New Debit Card Pin");

        reEnterPinPasswordField1.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        reEnterPinPasswordField1.setToolTipText("Please Re-Enter New Debit Card Pin");

        changePinButton1.setBackground(new java.awt.Color(0, 51, 102));
        changePinButton1.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 22)); // NOI18N
        changePinButton1.setForeground(new java.awt.Color(255, 255, 255));
        changePinButton1.setText("Change Pin");
        changePinButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePinButton1ActionPerformed(evt);
            }
        });

        enterNewPinLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        enterNewPinLabel1.setText("Enter New Pin");

        reEnterPinLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        reEnterPinLabel1.setText("Re Enter Pin");

        javax.swing.GroupLayout debitPinPanelLayout = new javax.swing.GroupLayout(debitPinPanel);
        debitPinPanel.setLayout(debitPinPanelLayout);
        debitPinPanelLayout.setHorizontalGroup(
            debitPinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(debitPinPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(debitPinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enterNewPinPasswordField1)
                    .addComponent(reEnterPinPasswordField1)
                    .addComponent(changePinButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(debitPinPanelLayout.createSequentialGroup()
                        .addGroup(debitPinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(enterNewPinLabel1)
                            .addComponent(reEnterPinLabel1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        debitPinPanelLayout.setVerticalGroup(
            debitPinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(debitPinPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(enterNewPinLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enterNewPinPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reEnterPinLabel1)
                .addGap(9, 9, 9)
                .addComponent(reEnterPinPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(changePinButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        backgroundPanel.add(debitPinPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(824, 114, 286, -1));

        headingLabel1.setBackground(new java.awt.Color(0, 0, 0));
        headingLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 3, 36)); // NOI18N
        headingLabel1.setForeground(new java.awt.Color(0, 51, 255));
        headingLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headingLabel1.setText("CARDS");
        backgroundPanel.add(headingLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 22, 981, -1));

        creditCardPanel.setBackground(new java.awt.Color(255, 255, 255));
        creditCardPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        creditCardTypeLabel4.setBackground(new java.awt.Color(255, 255, 255));
        creditCardTypeLabel4.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        creditCardTypeLabel4.setForeground(new java.awt.Color(102, 102, 102));
        creditCardTypeLabel4.setText("Credit Card Type :");

        cardNumberLabel11.setBackground(new java.awt.Color(255, 255, 255));
        cardNumberLabel11.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        cardNumberLabel11.setForeground(new java.awt.Color(102, 102, 102));
        cardNumberLabel11.setText("Card Number :");

        cVVNumberLabel4.setBackground(new java.awt.Color(255, 255, 255));
        cVVNumberLabel4.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        cVVNumberLabel4.setForeground(new java.awt.Color(102, 102, 102));
        cVVNumberLabel4.setText("CVV Number :");

        cardIssuedDateLabel4.setBackground(new java.awt.Color(255, 255, 255));
        cardIssuedDateLabel4.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        cardIssuedDateLabel4.setForeground(new java.awt.Color(102, 102, 102));
        cardIssuedDateLabel4.setText("Card Issued Date :");

        balanceLabel11.setBackground(new java.awt.Color(255, 255, 255));
        balanceLabel11.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        balanceLabel11.setForeground(new java.awt.Color(102, 102, 102));
        balanceLabel11.setText("Balance :");

        cardExpiryDateLabel4.setBackground(new java.awt.Color(255, 255, 255));
        cardExpiryDateLabel4.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        cardExpiryDateLabel4.setForeground(new java.awt.Color(102, 102, 102));
        cardExpiryDateLabel4.setText("Card Expiry Date :");

        interestRateLabel4.setBackground(new java.awt.Color(255, 255, 255));
        interestRateLabel4.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        interestRateLabel4.setForeground(new java.awt.Color(102, 102, 102));
        interestRateLabel4.setText("Interest Rate :");

        cardIssuedDateLabel3.setBackground(new java.awt.Color(255, 255, 255));
        cardIssuedDateLabel3.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        cardIssuedDateLabel3.setText("01-02-2023");

        cardExpiryDateLabel3.setBackground(new java.awt.Color(255, 255, 255));
        cardExpiryDateLabel3.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        cardExpiryDateLabel3.setText("01-02-2028");

        balanceLabel12.setBackground(new java.awt.Color(255, 255, 255));
        balanceLabel12.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N

        interestRateLabel3.setBackground(new java.awt.Color(255, 255, 255));
        interestRateLabel3.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        interestRateLabel3.setText("1.5%");

        creditCardTypeLabel3.setBackground(new java.awt.Color(255, 255, 255));
        creditCardTypeLabel3.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        creditCardTypeLabel3.setText("Gold");

        cVVNumberLabel3.setBackground(new java.awt.Color(255, 255, 255));
        cVVNumberLabel3.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        cVVNumberLabel3.setText("567");

        cardNumberLabel12.setBackground(new java.awt.Color(255, 255, 255));
        cardNumberLabel12.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N

        cardpanel2.setBackground(new java.awt.Color(255, 255, 255));
        cardpanel2.setForeground(new java.awt.Color(255, 255, 255));
        cardpanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoLabel2.setBackground(new java.awt.Color(255, 255, 255));
        logoLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        logoLabel2.setForeground(new java.awt.Color(255, 255, 255));
        logoLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/visa-icon.png"))); // NOI18N
        cardpanel2.add(logoLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        creditCardLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 16)); // NOI18N
        creditCardLabel2.setForeground(new java.awt.Color(255, 255, 255));
        creditCardLabel2.setText("Credit Card");
        cardpanel2.add(creditCardLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        cardLabel2.setBackground(new java.awt.Color(255, 255, 255));
        cardLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 15)); // NOI18N
        cardLabel2.setForeground(new java.awt.Color(255, 255, 255));
        cardpanel2.add(cardLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 260, 30));

        logoLabel4.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        logoLabel4.setForeground(new java.awt.Color(255, 255, 255));
        logoLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/gold-card-chip.png"))); // NOI18N
        cardpanel2.add(logoLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 250, -1));

        nameLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 15)); // NOI18N
        nameLabel2.setForeground(new java.awt.Color(255, 255, 255));
        cardpanel2.add(nameLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 260, 30));

        cardDLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/card-sky-blue.png"))); // NOI18N
        cardpanel2.add(cardDLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, -1));

        javax.swing.GroupLayout creditCardPanelLayout = new javax.swing.GroupLayout(creditCardPanel);
        creditCardPanel.setLayout(creditCardPanelLayout);
        creditCardPanelLayout.setHorizontalGroup(
            creditCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(creditCardPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(creditCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(creditCardPanelLayout.createSequentialGroup()
                        .addGroup(creditCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(creditCardPanelLayout.createSequentialGroup()
                                .addComponent(cardExpiryDateLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cardExpiryDateLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(creditCardPanelLayout.createSequentialGroup()
                                .addComponent(balanceLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(balanceLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(creditCardPanelLayout.createSequentialGroup()
                                .addComponent(interestRateLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(interestRateLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(creditCardPanelLayout.createSequentialGroup()
                                .addGroup(creditCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(cVVNumberLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cardNumberLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(creditCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cVVNumberLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cardNumberLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(creditCardPanelLayout.createSequentialGroup()
                                .addGroup(creditCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(creditCardPanelLayout.createSequentialGroup()
                                        .addComponent(cardIssuedDateLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cardIssuedDateLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(creditCardPanelLayout.createSequentialGroup()
                                        .addComponent(creditCardTypeLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(creditCardTypeLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(creditCardPanelLayout.createSequentialGroup()
                        .addComponent(cardpanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        creditCardPanelLayout.setVerticalGroup(
            creditCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(creditCardPanelLayout.createSequentialGroup()
                .addComponent(cardpanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(creditCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(creditCardTypeLabel4)
                    .addComponent(creditCardTypeLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(creditCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cardNumberLabel11)
                    .addComponent(cardNumberLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(creditCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cVVNumberLabel4)
                    .addComponent(cVVNumberLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(creditCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cardIssuedDateLabel4)
                    .addComponent(cardIssuedDateLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(creditCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cardExpiryDateLabel4)
                    .addComponent(cardExpiryDateLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(creditCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(balanceLabel11)
                    .addComponent(balanceLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(creditCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(interestRateLabel4)
                    .addComponent(interestRateLabel3))
                .addGap(38, 38, 38))
        );

        backgroundPanel.add(creditCardPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 114, -1, -1));

        creditCardDetailsLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 16)); // NOI18N
        creditCardDetailsLabel.setForeground(new java.awt.Color(0, 51, 255));
        creditCardDetailsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        creditCardDetailsLabel.setText("Credit Card Details");
        backgroundPanel.add(creditCardDetailsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 88, 306, -1));

        changeDebitCardPinCardLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 16)); // NOI18N
        changeDebitCardPinCardLabel.setForeground(new java.awt.Color(0, 51, 255));
        changeDebitCardPinCardLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        changeDebitCardPinCardLabel.setText("Change Debit Card Pin");
        backgroundPanel.add(changeDebitCardPinCardLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(824, 88, 286, -1));

        debitCardDetailsLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 16)); // NOI18N
        debitCardDetailsLabel.setForeground(new java.awt.Color(0, 51, 255));
        debitCardDetailsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        debitCardDetailsLabel.setText("Debit Card Details");
        backgroundPanel.add(debitCardDetailsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 88, 328, -1));

        changeCreditCardPinCardLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 16)); // NOI18N
        changeCreditCardPinCardLabel.setForeground(new java.awt.Color(0, 51, 255));
        changeCreditCardPinCardLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        changeCreditCardPinCardLabel.setText("Change Credit Card Pin");
        backgroundPanel.add(changeCreditCardPinCardLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(824, 331, 286, -1));

        debitPinPanel1.setBackground(new java.awt.Color(255, 255, 255));
        debitPinPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        enterNewPinPasswordField2.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        enterNewPinPasswordField2.setToolTipText("Please Enter New Credit Card Pin");

        reEnterPinPasswordField2.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        reEnterPinPasswordField2.setToolTipText("Please Re-Enter New Credit Card Pin");

        changePinButton2.setBackground(new java.awt.Color(0, 51, 102));
        changePinButton2.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 22)); // NOI18N
        changePinButton2.setForeground(new java.awt.Color(255, 255, 255));
        changePinButton2.setText("Change Pin");
        changePinButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePinButton2ActionPerformed(evt);
            }
        });

        enterNewPinLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        enterNewPinLabel2.setText("Enter New Pin");

        reEnterPinLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        reEnterPinLabel2.setText("Re Enter Pin");

        javax.swing.GroupLayout debitPinPanel1Layout = new javax.swing.GroupLayout(debitPinPanel1);
        debitPinPanel1.setLayout(debitPinPanel1Layout);
        debitPinPanel1Layout.setHorizontalGroup(
            debitPinPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(debitPinPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(debitPinPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enterNewPinPasswordField2)
                    .addComponent(reEnterPinPasswordField2)
                    .addComponent(changePinButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(debitPinPanel1Layout.createSequentialGroup()
                        .addGroup(debitPinPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(enterNewPinLabel2)
                            .addComponent(reEnterPinLabel2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        debitPinPanel1Layout.setVerticalGroup(
            debitPinPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(debitPinPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(enterNewPinLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enterNewPinPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reEnterPinLabel2)
                .addGap(9, 9, 9)
                .addComponent(reEnterPinPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(changePinButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        backgroundPanel.add(debitPinPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(824, 355, 286, -1));

        closeBtnLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/close-btn.png"))); // NOI18N
        closeBtnLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBtnLabelMouseClicked(evt);
            }
        });
        backgroundPanel.add(closeBtnLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1134, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void homeBtnPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBtnPanelMouseClicked
        Home H;
        try {
            H = new Home(accountNumber);
            setVisible(false);
            H.setVisible(true);
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(Cards.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_homeBtnPanelMouseClicked

    private void homeBtnPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBtnPanelMouseEntered
        JPanel btn= homeBtnPanel;
        isEntered(btn);
    }//GEN-LAST:event_homeBtnPanelMouseEntered

    private void homeBtnPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBtnPanelMouseExited
        JPanel btn= homeBtnPanel;
        isExited(btn);
    }//GEN-LAST:event_homeBtnPanelMouseExited

    private void transferBtnPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transferBtnPanelMouseClicked
        Transfer TF;
        try {
            TF = new Transfer(accountNumber);
            setVisible(false);
            TF.setVisible(true);
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(Cards.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_transferBtnPanelMouseClicked

    private void transferBtnPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transferBtnPanelMouseEntered
        JPanel btn= transferBtnPanel;
        isEntered(btn);
    }//GEN-LAST:event_transferBtnPanelMouseEntered

    private void transferBtnPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transferBtnPanelMouseExited
        JPanel btn= transferBtnPanel;
        isExited(btn);
    }//GEN-LAST:event_transferBtnPanelMouseExited

    private void accountBtnPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountBtnPanelMouseClicked
        Account A;
        try {
            A = new Account(accountNumber);
            setVisible(false);
            A.setVisible(true);
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(Cards.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_accountBtnPanelMouseClicked

    private void accountBtnPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountBtnPanelMouseEntered
        JPanel btn= accountBtnPanel;
        isEntered(btn);
    }//GEN-LAST:event_accountBtnPanelMouseEntered

    private void accountBtnPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountBtnPanelMouseExited
        JPanel btn= accountBtnPanel;
        isExited(btn);
    }//GEN-LAST:event_accountBtnPanelMouseExited

    private void cardsBtnPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cardsBtnPanelMouseClicked
        /*Cards CD= new Cards();
        setVisible(false);
        CD.setVisible(true);
        dispose();*/
    }//GEN-LAST:event_cardsBtnPanelMouseClicked

    private void cardsBtnPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cardsBtnPanelMouseEntered
        JPanel btn= cardsBtnPanel;
        isEntered(btn);
    }//GEN-LAST:event_cardsBtnPanelMouseEntered

    private void cardsBtnPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cardsBtnPanelMouseExited
        JPanel btn= cardsBtnPanel;
        isExited(btn);
    }//GEN-LAST:event_cardsBtnPanelMouseExited

    private void profileBtnPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileBtnPanelMouseClicked
        Profile P;
        try {
            P = new Profile(accountNumber);
            setVisible(false);
            P.setVisible(true);
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(Cards.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_profileBtnPanelMouseClicked

    private void profileBtnPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileBtnPanelMouseEntered
        JPanel btn= profileBtnPanel;
        isEntered(btn);
    }//GEN-LAST:event_profileBtnPanelMouseEntered

    private void profileBtnPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileBtnPanelMouseExited
        JPanel btn= profileBtnPanel;
        isExited(btn);
    }//GEN-LAST:event_profileBtnPanelMouseExited

    private void logoutBtnPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnPanelMouseClicked
        Login L= new Login();
        setVisible(false);
        L.setVisible(true);
        dispose();
    }//GEN-LAST:event_logoutBtnPanelMouseClicked

    private void logoutBtnPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnPanelMouseEntered
        JPanel btn= logoutBtnPanel;
        isEntered(btn);
    }//GEN-LAST:event_logoutBtnPanelMouseEntered

    private void logoutBtnPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnPanelMouseExited
        JPanel btn= logoutBtnPanel;
        isExited(btn);
    }//GEN-LAST:event_logoutBtnPanelMouseExited

    private void changePinButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePinButton1ActionPerformed
        String password1=enterNewPinPasswordField1.getText();
        String password2=reEnterPinPasswordField1.getText();
        
        
        try{
            if(password1.equals("") || password2.equals(""))
            {
                if(password1.equals(""))
                {
                    JOptionPane.showMessageDialog(null,"New Debit Card Pin is Requied");
                }
                
                if(password2.equals(""))
                {
                    JOptionPane.showMessageDialog(null,"Re-Enter New Debit Card Pin is Requied");
                }
            }else{
                Conn c=new Conn();
                String query1="select * from addApplication3 where accountNumber = '"+accountNumber+"'";
                //c.s.executeUpdate(query);
                
                ResultSet rs1 = c.s.executeQuery(query1);
                if(rs1.next())
                {
                    //String password=rs1.getString("userPassword");
                    
                    //if(password.equals(password1))
                    //{
                        
                        if(password1.equals(password2))
                        {
                            //String query="delete from createAccount1 where accountNumber = '"+accountNumber+"'";
                            //c.s.executeUpdate(query);

                    
                            String query="update addApplication3 set debitCardPin = '"+password1+"' where  accountNumber = '"+accountNumber+"'";
                            c.s.executeUpdate(query);
                            JOptionPane.showMessageDialog(null,"Debit Card Pin Changed Sucessfully !!!");
                            enterNewPinPasswordField1.setText("");
                            reEnterPinPasswordField1.setText("");
                            
                        }else{
                            
                            JOptionPane.showMessageDialog(null,"Both New Debit Card Pin Are Not Same");
                }
                        
                  //}
                }/*else{
                    JOptionPane.showMessageDialog(null,"Incorrect Present Password");
                }*/}
            }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_changePinButton1ActionPerformed

    private void changePinButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePinButton2ActionPerformed
        String password1=enterNewPinPasswordField2.getText();
        String password2=reEnterPinPasswordField2.getText();
        
        
        try{
            if(password1.equals("") || password2.equals(""))
            {
                if(password1.equals(""))
                {
                    JOptionPane.showMessageDialog(null,"New Credit Card Pin is Requied");
                }
                
                if(password2.equals(""))
                {
                    JOptionPane.showMessageDialog(null,"Re-Enter New Credit Card Pin is Requied");
                }
            }else{
                Conn c=new Conn();
                String query1="select * from addApplication3 where accountNumber = '"+accountNumber+"'";
                //c.s.executeUpdate(query);
                
                ResultSet rs1 = c.s.executeQuery(query1);
                if(rs1.next())
                {
                    //String password=rs1.getString("userPassword");
                    
                    //if(password.equals(password1))
                    //{
                        
                        if(password1.equals(password2))
                        {
                            //String query="delete from createAccount1 where accountNumber = '"+accountNumber+"'";
                            //c.s.executeUpdate(query);

                    
                            String query="update addApplication3 set creditCardPin = '"+password1+"' where  accountNumber = '"+accountNumber+"'";
                            c.s.executeUpdate(query);
                            JOptionPane.showMessageDialog(null,"Credit Card Pin Changed Sucessfully !!!");
                            enterNewPinPasswordField2.setText("");
                            reEnterPinPasswordField2.setText("");
                            
                        }else{
                            
                            JOptionPane.showMessageDialog(null,"Both New Credit Card Pin Are Not Same");
                }
                        
                  //}
                }/*else{
                    JOptionPane.showMessageDialog(null,"Incorrect Present Password");
                }*/}
            }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_changePinButton2ActionPerformed

    private void closeBtnLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnLabelMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeBtnLabelMouseClicked
    void isEntered(JPanel btn)
    {
        btn.setBackground(new Color(0,0,204));
    }
    
    void isExited(JPanel btn)
    {
        btn.setBackground(new Color(0,0,255));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Cards("").setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Cards.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountBtnLabel;
    private javax.swing.JPanel accountBtnPanel;
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JLabel balanceLabel;
    private javax.swing.JLabel balanceLabel11;
    private javax.swing.JLabel balanceLabel12;
    private javax.swing.JLabel balanceLabel2;
    private javax.swing.JLabel cVVNumberLabel1;
    private javax.swing.JLabel cVVNumberLabel2;
    private javax.swing.JLabel cVVNumberLabel3;
    private javax.swing.JLabel cVVNumberLabel4;
    private javax.swing.JLabel cardDLabel1;
    private javax.swing.JLabel cardDLabel2;
    private javax.swing.JLabel cardExpiryDateLabel1;
    private javax.swing.JLabel cardExpiryDateLabel2;
    private javax.swing.JLabel cardExpiryDateLabel3;
    private javax.swing.JLabel cardExpiryDateLabel4;
    private javax.swing.JLabel cardIssuedDateLabel1;
    private javax.swing.JLabel cardIssuedDateLabel2;
    private javax.swing.JLabel cardIssuedDateLabel3;
    private javax.swing.JLabel cardIssuedDateLabel4;
    private javax.swing.JLabel cardLabel1;
    private javax.swing.JLabel cardLabel2;
    private javax.swing.JLabel cardNumberLabel1;
    private javax.swing.JLabel cardNumberLabel11;
    private javax.swing.JLabel cardNumberLabel12;
    private javax.swing.JLabel cardNumberLabel2;
    private javax.swing.JPanel cardpanel1;
    private javax.swing.JPanel cardpanel2;
    private javax.swing.JLabel cardsBtnLabel;
    private javax.swing.JPanel cardsBtnPanel;
    private javax.swing.JLabel changeCreditCardPinCardLabel;
    private javax.swing.JLabel changeDebitCardPinCardLabel;
    private javax.swing.JButton changePinButton1;
    private javax.swing.JButton changePinButton2;
    private javax.swing.JLabel closeBtnLabel;
    private javax.swing.JLabel creditCardDetailsLabel;
    private javax.swing.JLabel creditCardLabel1;
    private javax.swing.JLabel creditCardLabel2;
    private javax.swing.JPanel creditCardPanel;
    private javax.swing.JLabel creditCardTypeLabel1;
    private javax.swing.JLabel creditCardTypeLabel2;
    private javax.swing.JLabel creditCardTypeLabel3;
    private javax.swing.JLabel creditCardTypeLabel4;
    private javax.swing.JLabel debitCardDetailsLabel;
    private javax.swing.JPanel debitCardPanel;
    private javax.swing.JPanel debitPinPanel;
    private javax.swing.JPanel debitPinPanel1;
    private javax.swing.JLabel enterNewPinLabel1;
    private javax.swing.JLabel enterNewPinLabel2;
    private javax.swing.JPasswordField enterNewPinPasswordField1;
    private javax.swing.JPasswordField enterNewPinPasswordField2;
    private javax.swing.JLabel headingLabel1;
    private javax.swing.JLabel homeBtnLabel;
    private javax.swing.JPanel homeBtnPanel;
    private javax.swing.JLabel interestRateLabel1;
    private javax.swing.JLabel interestRateLabel2;
    private javax.swing.JLabel interestRateLabel3;
    private javax.swing.JLabel interestRateLabel4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel logoLabel1;
    private javax.swing.JLabel logoLabel2;
    private javax.swing.JLabel logoLabel3;
    private javax.swing.JLabel logoLabel4;
    private javax.swing.JLabel logoutBtnLabel;
    private javax.swing.JPanel logoutBtnPanel;
    private javax.swing.JLabel nameLabel1;
    private javax.swing.JLabel nameLabel2;
    private javax.swing.JLabel profileBtnLabel;
    private javax.swing.JPanel profileBtnPanel;
    private javax.swing.JLabel reEnterPinLabel1;
    private javax.swing.JLabel reEnterPinLabel2;
    private javax.swing.JPasswordField reEnterPinPasswordField1;
    private javax.swing.JPasswordField reEnterPinPasswordField2;
    private javax.swing.JPanel sideBarPanel;
    private javax.swing.JLabel transferBtnLabel;
    private javax.swing.JPanel transferBtnPanel;
    // End of variables declaration//GEN-END:variables
}
