
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hp
 */
public class createAccount4 extends javax.swing.JFrame {

    /**
     * Creates new form createAccount4
     */
    String accountNumber;
    public createAccount4(String accountNumber) {
        this.accountNumber=accountNumber;
        initComponents();
        accountNumberLabel2.setText(accountNumberLabel2.getText()+accountNumber);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createAccount4Panel = new javax.swing.JPanel();
        createAccount4_2Panel = new javax.swing.JPanel();
        verifyLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        accountNumberLabel = new javax.swing.JLabel();
        createUsernameLabel = new javax.swing.JLabel();
        createUsernameTextField = new javax.swing.JTextField();
        createPasswordLabel = new javax.swing.JLabel();
        reEnterPasswordLabel = new javax.swing.JLabel();
        createYourAccountButton = new javax.swing.JButton();
        reEnterPasswordField = new javax.swing.JPasswordField();
        createPasswordField = new javax.swing.JPasswordField();
        accountNumberPanel = new javax.swing.JPanel();
        accountNumberLabel2 = new javax.swing.JLabel();
        closeBtnLabel = new javax.swing.JLabel();
        closeBtnLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        createAccount4Panel.setBackground(new java.awt.Color(0, 51, 255));
        createAccount4Panel.setPreferredSize(new java.awt.Dimension(1120, 630));

        createAccount4_2Panel.setBackground(new java.awt.Color(255, 255, 255));
        createAccount4_2Panel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        createAccount4_2Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        verifyLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        verifyLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/add profile.png"))); // NOI18N
        createAccount4_2Panel.add(verifyLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 15, 1040, -1));

        jLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Create Account");
        createAccount4_2Panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 128, 1045, -1));

        accountNumberLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        accountNumberLabel.setText("Account Number");
        createAccount4_2Panel.add(accountNumberLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 196, -1, -1));

        createUsernameLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        createUsernameLabel.setText("Create Username");
        createAccount4_2Panel.add(createUsernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 263, -1, -1));

        createUsernameTextField.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        createUsernameTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        createUsernameTextField.setToolTipText("Please Create Username");
        createUsernameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createUsernameTextFieldActionPerformed(evt);
            }
        });
        createAccount4_2Panel.add(createUsernameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 287, 300, 30));

        createPasswordLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        createPasswordLabel.setText("Create Password");
        createAccount4_2Panel.add(createPasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 337, -1, -1));

        reEnterPasswordLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        reEnterPasswordLabel.setText("Re Enter Password");
        createAccount4_2Panel.add(reEnterPasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 408, -1, -1));

        createYourAccountButton.setBackground(new java.awt.Color(0, 51, 102));
        createYourAccountButton.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        createYourAccountButton.setForeground(new java.awt.Color(255, 255, 255));
        createYourAccountButton.setText("Create Your Account");
        createYourAccountButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createYourAccountButton.setMaximumSize(new java.awt.Dimension(120, 40));
        createYourAccountButton.setMinimumSize(new java.awt.Dimension(120, 40));
        createYourAccountButton.setPreferredSize(new java.awt.Dimension(120, 40));
        createYourAccountButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createYourAccountButtonMouseClicked(evt);
            }
        });
        createYourAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createYourAccountButtonActionPerformed(evt);
            }
        });
        createAccount4_2Panel.add(createYourAccountButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 493, 300, -1));

        reEnterPasswordField.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        reEnterPasswordField.setToolTipText("Please Re Enter Password");
        reEnterPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reEnterPasswordFieldActionPerformed(evt);
            }
        });
        createAccount4_2Panel.add(reEnterPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 431, 300, 30));

        createPasswordField.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        createPasswordField.setToolTipText("Please Create Password");
        createPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createPasswordFieldActionPerformed(evt);
            }
        });
        createAccount4_2Panel.add(createPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 360, 300, 30));

        accountNumberPanel.setBackground(new java.awt.Color(255, 255, 255));
        accountNumberPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        accountNumberLabel2.setBackground(new java.awt.Color(255, 255, 255));
        accountNumberLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        accountNumberLabel2.setForeground(new java.awt.Color(102, 102, 102));
        accountNumberLabel2.setText(" ");

        javax.swing.GroupLayout accountNumberPanelLayout = new javax.swing.GroupLayout(accountNumberPanel);
        accountNumberPanel.setLayout(accountNumberPanelLayout);
        accountNumberPanelLayout.setHorizontalGroup(
            accountNumberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountNumberPanelLayout.createSequentialGroup()
                .addComponent(accountNumberLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        accountNumberPanelLayout.setVerticalGroup(
            accountNumberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(accountNumberLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
        );

        createAccount4_2Panel.add(accountNumberPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 219, 300, -1));

        closeBtnLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/goback.png"))); // NOI18N
        closeBtnLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBtnLabelMouseClicked(evt);
            }
        });
        createAccount4_2Panel.add(closeBtnLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        closeBtnLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/close-btn.png"))); // NOI18N
        closeBtnLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBtnLabel1MouseClicked(evt);
            }
        });
        createAccount4_2Panel.add(closeBtnLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 10, 30, -1));

        javax.swing.GroupLayout createAccount4PanelLayout = new javax.swing.GroupLayout(createAccount4Panel);
        createAccount4Panel.setLayout(createAccount4PanelLayout);
        createAccount4PanelLayout.setHorizontalGroup(
            createAccount4PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createAccount4PanelLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(createAccount4_2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        createAccount4PanelLayout.setVerticalGroup(
            createAccount4PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createAccount4PanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(createAccount4_2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(createAccount4Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 1121, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(createAccount4Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void createUsernameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createUsernameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createUsernameTextFieldActionPerformed

    private void createYourAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createYourAccountButtonActionPerformed
        // TODO add your handling code here:
        String createUsername=createUsernameTextField.getText();
        String createPassword=createPasswordField.getText();
        String reEnterPassword=reEnterPasswordField.getText();    
        
        try{
            if(createUsername.equals("")||
                createPassword.equals("")||
                reEnterPassword.equals(""))
            {
                if(createUsername.equals(""))
                {
                     JOptionPane.showMessageDialog(null,"Create Username is Requied");     
                }
                if(createPassword.equals(""))
                {
                     JOptionPane.showMessageDialog(null,"Create Password is Requied");     
                }
                if(reEnterPassword.equals(""))
                {
                     JOptionPane.showMessageDialog(null,"Re-Enter Password is Requied");     
                }
                
            }else{
                if(createPassword.equals(reEnterPassword))
                {
                    Conn c=new Conn();
                    String query="insert into createAccount1 values('"+accountNumber+"', '"+createUsername+"', '"+createPassword+"')";
                    c.s.executeUpdate(query);
                
                    createAccount5 AC5= new createAccount5();
                    setVisible(false);
                    AC5.setVisible(true);
                    dispose();      
                }else
                {
                    JOptionPane.showMessageDialog(null,"Both Password Are Not Same");
                }
            }
        }catch(Exception e){
            System.out.println(e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_createYourAccountButtonActionPerformed

    private void createYourAccountButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createYourAccountButtonMouseClicked
        createAccount5 AC5= new createAccount5();
        setVisible(false);
        AC5.setVisible(true);
        dispose();
    }//GEN-LAST:event_createYourAccountButtonMouseClicked

    private void reEnterPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reEnterPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reEnterPasswordFieldActionPerformed

    private void createPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createPasswordFieldActionPerformed

    private void closeBtnLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnLabelMouseClicked
        Login L=new Login();
        setVisible(false);
        L.setVisible(true);
        dispose();
    }//GEN-LAST:event_closeBtnLabelMouseClicked

    private void closeBtnLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnLabel1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeBtnLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(createAccount4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(createAccount4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(createAccount4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(createAccount4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new createAccount4("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountNumberLabel;
    private javax.swing.JLabel accountNumberLabel2;
    private javax.swing.JPanel accountNumberPanel;
    private javax.swing.JLabel closeBtnLabel;
    private javax.swing.JLabel closeBtnLabel1;
    private javax.swing.JPanel createAccount4Panel;
    private javax.swing.JPanel createAccount4_2Panel;
    private javax.swing.JPasswordField createPasswordField;
    private javax.swing.JLabel createPasswordLabel;
    private javax.swing.JLabel createUsernameLabel;
    private javax.swing.JTextField createUsernameTextField;
    private javax.swing.JButton createYourAccountButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField reEnterPasswordField;
    private javax.swing.JLabel reEnterPasswordLabel;
    private javax.swing.JLabel verifyLabel;
    // End of variables declaration//GEN-END:variables
}
