
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hp
 */
public class Edit extends javax.swing.JFrame {

    /**
     * Creates new form Edit
     */
    String accountNumber;
    public Edit(String accountNumber) throws SQLException {
        this.accountNumber=accountNumber;
        initComponents();
        Conn c=new Conn();

        int count=1;
        
        if(count>=0)
        {  
            String query1="select * from createAccount1 where accountNumber = '"+accountNumber+"'";
            ResultSet rs1 = c.s.executeQuery(query1);
            if(rs1.next())
            {
                String uname=rs1.getString("username");
                usernameTextField.setText(usernameTextField.getText()+uname);
            }
        }
   
        
        /*if(count>=0)
        {
            String query1="select * from addApplication3 where accountNumber = '"+accountNumber+"'";
            ResultSet rs1 = c.s.executeQuery(query1);
            if(rs1.next())
            {
                
                String address=rs1.getString("accountType");
                accountTypeLabel2.setText(accountTypeLabel2.getText()+address);
            }
                
            
            
        }*/
        if(count>=0)
        {
            String query1="select * from addApplication1 where accountNumber = '"+accountNumber+"'";
                
            ResultSet rs1 = c.s.executeQuery(query1);
            if(rs1.next())
            {
                String fName=rs1.getString("firstName");
                String LName=rs1.getString("lastName");
                String FatherName=rs1.getString("fathersName");
                String dob=rs1.getString("dateOfBirth");
                String gender=rs1.getString("gender");
                String ms=rs1.getString("maritalStatus");
                String pNum=rs1.getString("phoneNumber");
                String email=rs1.getString("emailAddress");
                FirstNameTextField.setText(FirstNameTextField.getText()+fName);
                LastNameTextField.setText(LastNameTextField.getText()+LName);
                FathersNameTextField.setText(FathersNameTextField.getText()+FatherName);
                dateOfBirthTextField.setText(dateOfBirthTextField.getText()+dob);
                genderTextField.setText(genderTextField.getText()+gender);
                MeritalStatusTextField.setText(MeritalStatusTextField.getText()+ms);
                PhoneNumberTextField.setText(PhoneNumberTextField.getText()+pNum);
                EmailAddressTextField.setText(EmailAddressTextField.getText()+email);
                
                
                
                
                
                
            }
            
        }
        if(count>=0)
        {
            String query1="select * from addApplication2_1 where accountNumber = '"+accountNumber+"'";
                
            ResultSet rs1 = c.s.executeQuery(query1);
            if(rs1.next())
            {
                String address=rs1.getString("presentAddress");
                String paddress=rs1.getString("permanentAddress");
                String city=rs1.getString("city");
                String pcode=rs1.getString("postCode");
                String religion=rs1.getString("religion");
                String n=rs1.getString("nationality");
                String edu=rs1.getString("educationQualification");
                String o=rs1.getString("occupation");
                PresentAddressField.setText(PresentAddressField.getText()+address);
                PermanentAddressTextField.setText(PermanentAddressTextField.getText()+paddress);
                CityField.setText(CityField.getText()+city);
                PostCodeTextField.setText(PostCodeTextField.getText()+pcode);
                ReligionTextField.setText(ReligionTextField.getText()+religion);
                NationalityTextField.setText(NationalityTextField.getText()+n);
                EducationQualificationTextField.setText(EducationQualificationTextField.getText()+edu);
                OccupationTextField.setText(OccupationTextField.getText()+o);
                
                
                
                
                
                
            }
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        editPanel = new javax.swing.JPanel();
        editPanel2 = new javax.swing.JPanel();
        addApplicationAdditionalDetailsLabel = new javax.swing.JLabel();
        FirstNameLabel = new javax.swing.JLabel();
        FirstNameTextField = new javax.swing.JTextField();
        upateButton = new javax.swing.JButton();
        LastNameTextField = new javax.swing.JTextField();
        FathersNameLabel = new javax.swing.JLabel();
        FathersNameTextField = new javax.swing.JTextField();
        dateOfBirthTextField = new javax.swing.JTextField();
        genderLabel = new javax.swing.JLabel();
        genderTextField = new javax.swing.JTextField();
        LastNameLabel = new javax.swing.JLabel();
        MeritalStatusTextField = new javax.swing.JTextField();
        PhoneNumberLabel = new javax.swing.JLabel();
        PhoneNumberTextField = new javax.swing.JTextField();
        EmailAddressLabel = new javax.swing.JLabel();
        EmailAddressTextField = new javax.swing.JTextField();
        PresentAddressField = new javax.swing.JTextField();
        PresentAddressLabel = new javax.swing.JLabel();
        PermanentAddressTextField = new javax.swing.JTextField();
        PermanentAddressLabel = new javax.swing.JLabel();
        PostCodeLabel = new javax.swing.JLabel();
        CityLabel = new javax.swing.JLabel();
        PostCodeTextField = new javax.swing.JTextField();
        CityField = new javax.swing.JTextField();
        EducationQualificationLabel = new javax.swing.JLabel();
        NationalityTextField = new javax.swing.JTextField();
        NationalityLabel = new javax.swing.JLabel();
        ReligionTextField = new javax.swing.JTextField();
        ReligionLabel = new javax.swing.JLabel();
        EducationQualificationTextField = new javax.swing.JTextField();
        OccupationTextField = new javax.swing.JTextField();
        OccupationLabel = new javax.swing.JLabel();
        UsernameLabel = new javax.swing.JLabel();
        usernameTextField = new javax.swing.JTextField();
        MeritalStatusLabel = new javax.swing.JLabel();
        dateOfBirthLabel = new javax.swing.JLabel();
        goBackBtnLabel = new javax.swing.JLabel();
        closeBtnLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        editPanel.setBackground(new java.awt.Color(0, 51, 255));
        editPanel.setPreferredSize(new java.awt.Dimension(1120, 630));

        editPanel2.setBackground(new java.awt.Color(255, 255, 255));
        editPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        editPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addApplicationAdditionalDetailsLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 36)); // NOI18N
        addApplicationAdditionalDetailsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addApplicationAdditionalDetailsLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/male-profile.png"))); // NOI18N
        addApplicationAdditionalDetailsLabel.setText("Edit Your Account Details");
        editPanel2.add(addApplicationAdditionalDetailsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1040, 86));

        FirstNameLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        FirstNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        FirstNameLabel.setText("First Name :");
        editPanel2.add(FirstNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 183, 110, -1));

        FirstNameTextField.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        FirstNameTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        FirstNameTextField.setToolTipText("Please Enter Present Address");
        FirstNameTextField.setPreferredSize(new java.awt.Dimension(6, 30));
        FirstNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstNameTextFieldActionPerformed(evt);
            }
        });
        editPanel2.add(FirstNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 176, 300, -1));

        upateButton.setBackground(new java.awt.Color(0, 51, 102));
        upateButton.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        upateButton.setForeground(new java.awt.Color(255, 255, 255));
        upateButton.setText("Update");
        upateButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        upateButton.setMaximumSize(new java.awt.Dimension(120, 40));
        upateButton.setMinimumSize(new java.awt.Dimension(120, 40));
        upateButton.setPreferredSize(new java.awt.Dimension(120, 40));
        upateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upateButtonActionPerformed(evt);
            }
        });
        editPanel2.add(upateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 500, 300, -1));

        LastNameTextField.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        LastNameTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        LastNameTextField.setToolTipText("Please Enter Present Address");
        LastNameTextField.setPreferredSize(new java.awt.Dimension(6, 30));
        LastNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastNameTextFieldActionPerformed(evt);
            }
        });
        editPanel2.add(LastNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(668, 176, 300, -1));

        FathersNameLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        FathersNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        FathersNameLabel.setText("Father's Name :");
        editPanel2.add(FathersNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 220, 110, -1));

        FathersNameTextField.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        FathersNameTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        FathersNameTextField.setToolTipText("Please Enter Present Address");
        FathersNameTextField.setPreferredSize(new java.awt.Dimension(6, 30));
        FathersNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FathersNameTextFieldActionPerformed(evt);
            }
        });
        editPanel2.add(FathersNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 213, 300, -1));

        dateOfBirthTextField.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        dateOfBirthTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        dateOfBirthTextField.setToolTipText("Please Enter Present Address");
        dateOfBirthTextField.setPreferredSize(new java.awt.Dimension(6, 30));
        dateOfBirthTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateOfBirthTextFieldActionPerformed(evt);
            }
        });
        editPanel2.add(dateOfBirthTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(668, 213, 300, -1));

        genderLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        genderLabel.setText("Gender :");
        editPanel2.add(genderLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 257, -1, -1));

        genderTextField.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        genderTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        genderTextField.setToolTipText("Please Enter Present Address");
        genderTextField.setPreferredSize(new java.awt.Dimension(6, 30));
        genderTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderTextFieldActionPerformed(evt);
            }
        });
        editPanel2.add(genderTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 250, 300, -1));

        LastNameLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        LastNameLabel.setText("Last Name :");
        editPanel2.add(LastNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 180, -1, 20));

        MeritalStatusTextField.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        MeritalStatusTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        MeritalStatusTextField.setToolTipText("Please Enter Present Address");
        MeritalStatusTextField.setPreferredSize(new java.awt.Dimension(6, 30));
        MeritalStatusTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MeritalStatusTextFieldActionPerformed(evt);
            }
        });
        editPanel2.add(MeritalStatusTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(668, 250, 300, -1));

        PhoneNumberLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        PhoneNumberLabel.setText("Phone Number :");
        editPanel2.add(PhoneNumberLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 294, -1, -1));

        PhoneNumberTextField.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        PhoneNumberTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        PhoneNumberTextField.setToolTipText("Please Enter Present Address");
        PhoneNumberTextField.setPreferredSize(new java.awt.Dimension(6, 30));
        PhoneNumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhoneNumberTextFieldActionPerformed(evt);
            }
        });
        editPanel2.add(PhoneNumberTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 287, 300, -1));

        EmailAddressLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        EmailAddressLabel.setText("Email Address :");
        editPanel2.add(EmailAddressLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(551, 294, -1, -1));

        EmailAddressTextField.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        EmailAddressTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        EmailAddressTextField.setToolTipText("Please Enter Present Address");
        EmailAddressTextField.setPreferredSize(new java.awt.Dimension(6, 30));
        EmailAddressTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailAddressTextFieldActionPerformed(evt);
            }
        });
        editPanel2.add(EmailAddressTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(668, 287, 300, -1));

        PresentAddressField.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        PresentAddressField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        PresentAddressField.setToolTipText("Please Enter Present Address");
        PresentAddressField.setPreferredSize(new java.awt.Dimension(6, 30));
        PresentAddressField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PresentAddressFieldActionPerformed(evt);
            }
        });
        editPanel2.add(PresentAddressField, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 324, 300, -1));

        PresentAddressLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        PresentAddressLabel.setText("Present Address :");
        editPanel2.add(PresentAddressLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 331, -1, -1));

        PermanentAddressTextField.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        PermanentAddressTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        PermanentAddressTextField.setToolTipText("Please Enter Present Address");
        PermanentAddressTextField.setPreferredSize(new java.awt.Dimension(6, 30));
        PermanentAddressTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PermanentAddressTextFieldActionPerformed(evt);
            }
        });
        editPanel2.add(PermanentAddressTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(668, 324, 300, -1));

        PermanentAddressLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        PermanentAddressLabel.setText("Permanent Address :");
        editPanel2.add(PermanentAddressLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 330, -1, -1));

        PostCodeLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        PostCodeLabel.setText("Post Code :");
        editPanel2.add(PostCodeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(551, 368, -1, -1));

        CityLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        CityLabel.setText("City :");
        editPanel2.add(CityLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 368, -1, -1));

        PostCodeTextField.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        PostCodeTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        PostCodeTextField.setToolTipText("Please Enter Present Address");
        PostCodeTextField.setPreferredSize(new java.awt.Dimension(6, 30));
        PostCodeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PostCodeTextFieldActionPerformed(evt);
            }
        });
        editPanel2.add(PostCodeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(668, 361, 300, -1));

        CityField.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        CityField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        CityField.setToolTipText("Please Enter Present Address");
        CityField.setPreferredSize(new java.awt.Dimension(6, 30));
        CityField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CityFieldActionPerformed(evt);
            }
        });
        editPanel2.add(CityField, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 361, 300, -1));

        EducationQualificationLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        EducationQualificationLabel.setText("Education Qualification :");
        editPanel2.add(EducationQualificationLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 160, 20));

        NationalityTextField.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        NationalityTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        NationalityTextField.setToolTipText("Please Enter Present Address");
        NationalityTextField.setPreferredSize(new java.awt.Dimension(6, 30));
        NationalityTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NationalityTextFieldActionPerformed(evt);
            }
        });
        editPanel2.add(NationalityTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(668, 398, 300, -1));

        NationalityLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        NationalityLabel.setText("Nationality :");
        editPanel2.add(NationalityLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(551, 405, -1, -1));

        ReligionTextField.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        ReligionTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        ReligionTextField.setToolTipText("Please Enter Present Address");
        ReligionTextField.setPreferredSize(new java.awt.Dimension(6, 30));
        ReligionTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReligionTextFieldActionPerformed(evt);
            }
        });
        editPanel2.add(ReligionTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 398, 300, -1));

        ReligionLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        ReligionLabel.setText(" Religion :");
        editPanel2.add(ReligionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 80, 30));

        EducationQualificationTextField.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        EducationQualificationTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        EducationQualificationTextField.setToolTipText("Please Enter Present Address");
        EducationQualificationTextField.setPreferredSize(new java.awt.Dimension(6, 30));
        EducationQualificationTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EducationQualificationTextFieldActionPerformed(evt);
            }
        });
        editPanel2.add(EducationQualificationTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 435, 300, -1));

        OccupationTextField.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        OccupationTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        OccupationTextField.setToolTipText("Please Enter Present Address");
        OccupationTextField.setPreferredSize(new java.awt.Dimension(6, 30));
        OccupationTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OccupationTextFieldActionPerformed(evt);
            }
        });
        editPanel2.add(OccupationTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(668, 435, 300, -1));

        OccupationLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        OccupationLabel.setText("Occupation :");
        editPanel2.add(OccupationLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(551, 442, -1, -1));

        UsernameLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        UsernameLabel.setText("Username :");
        editPanel2.add(UsernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 135, -1, -1));

        usernameTextField.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        usernameTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        usernameTextField.setToolTipText("Please Enter Present Address");
        usernameTextField.setPreferredSize(new java.awt.Dimension(6, 30));
        usernameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTextFieldActionPerformed(evt);
            }
        });
        editPanel2.add(usernameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 128, 300, -1));

        MeritalStatusLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        MeritalStatusLabel.setText("Merital Status :");
        editPanel2.add(MeritalStatusLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(551, 257, -1, -1));

        dateOfBirthLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        dateOfBirthLabel.setText("Date of Birth :");
        editPanel2.add(dateOfBirthLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 220, -1, -1));

        goBackBtnLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/goback.png"))); // NOI18N
        goBackBtnLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                goBackBtnLabelMouseClicked(evt);
            }
        });
        editPanel2.add(goBackBtnLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        closeBtnLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/close-btn.png"))); // NOI18N
        closeBtnLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBtnLabel1MouseClicked(evt);
            }
        });
        editPanel2.add(closeBtnLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 10, 30, -1));

        javax.swing.GroupLayout editPanelLayout = new javax.swing.GroupLayout(editPanel);
        editPanel.setLayout(editPanelLayout);
        editPanelLayout.setHorizontalGroup(
            editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(editPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1048, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        editPanelLayout.setVerticalGroup(
            editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(editPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(editPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(editPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void upateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upateButtonActionPerformed
        // TODO add your handling code here:
                Conn c=new Conn();
                //int count=0;
        
                String uname=usernameTextField.getText();
                String query1="update createAccount1 set username = '"+uname+"' where  accountNumber = '"+accountNumber+"'";
                try {
                    c.s.executeUpdate(query1);
                    //count++;
                } catch (SQLException ex) {
                    Logger.getLogger(Edit.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                String fName=FirstNameTextField.getText();
                String LName=LastNameTextField.getText();
                String FatherName=FathersNameTextField.getText();
                String dob=dateOfBirthTextField.getText();
                String gender=genderTextField.getText();
                String ms=MeritalStatusTextField.getText();
                String pNum=PhoneNumberTextField.getText();
                String email=EmailAddressTextField.getText();
                String query2="update addApplication1 set firstName = '"+fName
                        +"', lastName = '"+LName
                        +"', fathersName = '"+FatherName
                        +"', dateOfBirth = '"+dob
                        +"', gender = '"+gender
                        +"', maritalStatus = '"+ms
                        +"', phoneNumber = '"+pNum
                        +"', emailAddress = '"+email+
                        "' where  accountNumber = '"+accountNumber+"'";
                try {
                    c.s.executeUpdate(query2);
                    //count++;
                } catch (SQLException ex) {
                    Logger.getLogger(Edit.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                String address=PresentAddressField.getText();
                String paddress=PermanentAddressTextField.getText();
                String city=CityField.getText();
                String pcode=PostCodeTextField.getText();
                String religion=ReligionTextField.getText();
                String n=NationalityTextField.getText();
                String edu=EducationQualificationTextField.getText();
                String o=OccupationTextField.getText();
                String query3="update addApplication2_1 set presentAddress = '"+address
                        +"', permanentAddress = '"+paddress
                        +"', city = '"+city
                        +"', postCode = '"+pcode
                        +"', religion = '"+religion
                        +"', nationality = '"+n
                        +"', educationQualification = '"+edu
                        +"', occupation = '"+o+
                        "' where  accountNumber = '"+accountNumber+"'";
                try {
                    c.s.executeUpdate(query3);
                    //count++;
                } catch (SQLException ex) {
                    Logger.getLogger(Edit.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                //if(count>=0)
                //{
                    JOptionPane.showMessageDialog(null,"Acount Details Update Succesfully");
                //}else
                //{
                   // JOptionPane.showMessageDialog(null,"No New Data For update");
                //}
                
        // TODO add your handling code here:
    }//GEN-LAST:event_upateButtonActionPerformed

    private void FirstNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstNameTextFieldActionPerformed

    private void LastNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LastNameTextFieldActionPerformed

    private void FathersNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FathersNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FathersNameTextFieldActionPerformed

    private void PhoneNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhoneNumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhoneNumberTextFieldActionPerformed

    private void EmailAddressTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailAddressTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailAddressTextFieldActionPerformed

    private void PresentAddressFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PresentAddressFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PresentAddressFieldActionPerformed

    private void usernameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTextFieldActionPerformed

    private void MeritalStatusTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MeritalStatusTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MeritalStatusTextFieldActionPerformed

    private void genderTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderTextFieldActionPerformed

    private void PermanentAddressTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PermanentAddressTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PermanentAddressTextFieldActionPerformed

    private void PostCodeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PostCodeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PostCodeTextFieldActionPerformed

    private void CityFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CityFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CityFieldActionPerformed

    private void ReligionTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReligionTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReligionTextFieldActionPerformed

    private void NationalityTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NationalityTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NationalityTextFieldActionPerformed

    private void OccupationTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OccupationTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OccupationTextFieldActionPerformed

    private void EducationQualificationTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EducationQualificationTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EducationQualificationTextFieldActionPerformed

    private void dateOfBirthTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateOfBirthTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateOfBirthTextFieldActionPerformed

    private void goBackBtnLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goBackBtnLabelMouseClicked
            AccountSettings AS=new AccountSettings(accountNumber);
            setVisible(false);
            AS.setVisible(true);
            dispose();

    }//GEN-LAST:event_goBackBtnLabelMouseClicked

    private void closeBtnLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnLabel1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeBtnLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Edit("").setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Edit.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CityField;
    private javax.swing.JLabel CityLabel;
    private javax.swing.JLabel EducationQualificationLabel;
    private javax.swing.JTextField EducationQualificationTextField;
    private javax.swing.JLabel EmailAddressLabel;
    private javax.swing.JTextField EmailAddressTextField;
    private javax.swing.JLabel FathersNameLabel;
    private javax.swing.JTextField FathersNameTextField;
    private javax.swing.JLabel FirstNameLabel;
    private javax.swing.JTextField FirstNameTextField;
    private javax.swing.JLabel LastNameLabel;
    private javax.swing.JTextField LastNameTextField;
    private javax.swing.JLabel MeritalStatusLabel;
    private javax.swing.JTextField MeritalStatusTextField;
    private javax.swing.JLabel NationalityLabel;
    private javax.swing.JTextField NationalityTextField;
    private javax.swing.JLabel OccupationLabel;
    private javax.swing.JTextField OccupationTextField;
    private javax.swing.JLabel PermanentAddressLabel;
    private javax.swing.JTextField PermanentAddressTextField;
    private javax.swing.JLabel PhoneNumberLabel;
    private javax.swing.JTextField PhoneNumberTextField;
    private javax.swing.JLabel PostCodeLabel;
    private javax.swing.JTextField PostCodeTextField;
    private javax.swing.JTextField PresentAddressField;
    private javax.swing.JLabel PresentAddressLabel;
    private javax.swing.JLabel ReligionLabel;
    private javax.swing.JTextField ReligionTextField;
    private javax.swing.JLabel UsernameLabel;
    private javax.swing.JLabel addApplicationAdditionalDetailsLabel;
    private javax.swing.JLabel closeBtnLabel1;
    private javax.swing.JLabel dateOfBirthLabel;
    private javax.swing.JTextField dateOfBirthTextField;
    private javax.swing.JPanel editPanel;
    private javax.swing.JPanel editPanel2;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JTextField genderTextField;
    private javax.swing.JLabel goBackBtnLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton upateButton;
    private javax.swing.JTextField usernameTextField;
    // End of variables declaration//GEN-END:variables
}
