
import java.awt.Color;
import java.awt.Font;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hp
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    String accountNumber;
    public Home(String accountNumber) throws SQLException {
        this.accountNumber=accountNumber;
        initComponents();
        transactionTable.getTableHeader().setFont(new Font("Segoe UI",Font.BOLD,16));
        transactionTable.getTableHeader().setOpaque(false);
        transactionTable.getTableHeader().setBackground(new Color(0,51,102));
        transactionTable.getTableHeader().setForeground(new Color(255,255,255));
        transactionTable.setRowHeight(25);
        accountLabel.setText(accountLabel.getText()+accountNumber);
        Conn c=new Conn();
        String query="select * from balance where accountNumber = '"+accountNumber+"'";
        
        //c.s.executeUpdate(query);
                
        ResultSet rs = c.s.executeQuery(query);
        
        
        int balance=0;
        int count=0;
        while(rs.next())
        {
            if(rs.getString("type").equals("Deposit"))
            {
                balance+=Integer.parseInt(rs.getString("amount"));
            }else{
                balance-=Integer.parseInt(rs.getString("amount"));
            }count++;
            String Type=rs.getString("type");
            String DT=rs.getString("amount");
            String amount=rs.getString("dateAndTime");
            String tbData[]={Type,DT,amount};
            DefaultTableModel  tb1Model=(DefaultTableModel)transactionTable.getModel();
            tb1Model.addRow(tbData);
        }
        System.out.println(balance);
        takaLabel.setText(takaLabel.getText()+balance);
        double balance2=0;
        balance2=(balance/105.64);
        DecimalFormat df= new DecimalFormat("#.###");
        takaLabel1.setText(takaLabel1.getText()+df.format(balance2));
        
        if(balance2>=0)
        {
            String query1="select * from addApplication3 where accountNumber = '"+accountNumber+"'";
            ResultSet rs1 = c.s.executeQuery(query1);
            if(rs1.next())
            {
                String accountNumber1=rs1.getString("creditCardNumber");
                accountLabel1.setText(accountLabel1.getText()+accountNumber1);
            }
            
        }
        if(balance2>=0)
        {
            String query1="select * from addApplication1 where accountNumber = '"+accountNumber+"'";
            ResultSet rs1 = c.s.executeQuery(query1);
            if(rs1.next())
            {
                String accountNumber1=rs1.getString("firstName");
                helloLabel.setText("Hello, "+helloLabel.getText()+accountNumber1+" !");
            }
            
        }
        
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        sideBarPanel = new javax.swing.JPanel();
        homeBtnPanel = new javax.swing.JPanel();
        homeBtnLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        transferBtnPanel = new javax.swing.JPanel();
        transferBtnLabel = new javax.swing.JLabel();
        accountBtnPanel = new javax.swing.JPanel();
        accountBtnLabel = new javax.swing.JLabel();
        cardsBtnPanel = new javax.swing.JPanel();
        cardsBtnLabel = new javax.swing.JLabel();
        profileBtnPanel = new javax.swing.JPanel();
        profileBtnLabel = new javax.swing.JLabel();
        logoutBtnPanel = new javax.swing.JPanel();
        logoutBtnLabel = new javax.swing.JLabel();
        transactionPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        transactionTable = new javax.swing.JTable();
        allLastTLabel = new javax.swing.JLabel();
        balancepanel1 = new javax.swing.JPanel();
        skyBankLabel = new javax.swing.JLabel();
        availableBalanceLabel = new javax.swing.JLabel();
        accountLabel = new javax.swing.JLabel();
        takaLabel = new javax.swing.JLabel();
        balanceLabel1 = new javax.swing.JLabel();
        skyCardPanel = new javax.swing.JPanel();
        shopWithUsLabel = new javax.swing.JLabel();
        buyLabel = new javax.swing.JLabel();
        buy2Label = new javax.swing.JLabel();
        skyCardLabel = new javax.swing.JLabel();
        shopLabel = new javax.swing.JLabel();
        skyCardLabe1 = new javax.swing.JLabel();
        skyShoppingLabel = new javax.swing.JLabel();
        headingLabel1 = new javax.swing.JLabel();
        balancepanel2 = new javax.swing.JPanel();
        skyBankLabel1 = new javax.swing.JLabel();
        availableBalanceLabel1 = new javax.swing.JLabel();
        accountLabel1 = new javax.swing.JLabel();
        takaLabel1 = new javax.swing.JLabel();
        balanceLabel2 = new javax.swing.JLabel();
        helloLabel = new javax.swing.JLabel();
        welcomeLabel = new javax.swing.JLabel();
        closeBtnLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        backgroundPanel.setBackground(new java.awt.Color(255, 255, 255));
        backgroundPanel.setMinimumSize(new java.awt.Dimension(1120, 630));
        backgroundPanel.setPreferredSize(new java.awt.Dimension(1120, 630));
        backgroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sideBarPanel.setBackground(new java.awt.Color(0, 51, 255));

        homeBtnPanel.setBackground(new java.awt.Color(0, 0, 255));
        homeBtnPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeBtnPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeBtnPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeBtnPanelMouseExited(evt);
            }
        });

        homeBtnLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        homeBtnLabel.setForeground(new java.awt.Color(255, 255, 255));
        homeBtnLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homeBtnLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/white-home.png"))); // NOI18N
        homeBtnLabel.setText(" Home");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/white-indicate.png"))); // NOI18N

        javax.swing.GroupLayout homeBtnPanelLayout = new javax.swing.GroupLayout(homeBtnPanel);
        homeBtnPanel.setLayout(homeBtnPanelLayout);
        homeBtnPanelLayout.setHorizontalGroup(
            homeBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeBtnPanelLayout.createSequentialGroup()
                .addComponent(homeBtnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        homeBtnPanelLayout.setVerticalGroup(
            homeBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homeBtnPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homeBtnLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addContainerGap())
        );

        transferBtnPanel.setBackground(new java.awt.Color(0, 0, 255));
        transferBtnPanel.setPreferredSize(new java.awt.Dimension(118, 65));
        transferBtnPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transferBtnPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                transferBtnPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                transferBtnPanelMouseExited(evt);
            }
        });

        transferBtnLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        transferBtnLabel.setForeground(new java.awt.Color(255, 255, 255));
        transferBtnLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        transferBtnLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/transfer-icon.png"))); // NOI18N
        transferBtnLabel.setText(" Transfer");

        javax.swing.GroupLayout transferBtnPanelLayout = new javax.swing.GroupLayout(transferBtnPanel);
        transferBtnPanel.setLayout(transferBtnPanelLayout);
        transferBtnPanelLayout.setHorizontalGroup(
            transferBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(transferBtnLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        transferBtnPanelLayout.setVerticalGroup(
            transferBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transferBtnPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(transferBtnLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addContainerGap())
        );

        accountBtnPanel.setBackground(new java.awt.Color(0, 0, 255));
        accountBtnPanel.setPreferredSize(new java.awt.Dimension(118, 65));
        accountBtnPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accountBtnPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                accountBtnPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                accountBtnPanelMouseExited(evt);
            }
        });

        accountBtnLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        accountBtnLabel.setForeground(new java.awt.Color(255, 255, 255));
        accountBtnLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        accountBtnLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/white-moneybag.png"))); // NOI18N
        accountBtnLabel.setText(" Account");

        javax.swing.GroupLayout accountBtnPanelLayout = new javax.swing.GroupLayout(accountBtnPanel);
        accountBtnPanel.setLayout(accountBtnPanelLayout);
        accountBtnPanelLayout.setHorizontalGroup(
            accountBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(accountBtnLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        accountBtnPanelLayout.setVerticalGroup(
            accountBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, accountBtnPanelLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(accountBtnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        cardsBtnPanel.setBackground(new java.awt.Color(0, 0, 255));
        cardsBtnPanel.setPreferredSize(new java.awt.Dimension(118, 65));
        cardsBtnPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cardsBtnPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cardsBtnPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cardsBtnPanelMouseExited(evt);
            }
        });

        cardsBtnLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        cardsBtnLabel.setForeground(new java.awt.Color(255, 255, 255));
        cardsBtnLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cardsBtnLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/white-card.png"))); // NOI18N
        cardsBtnLabel.setText(" Cards");

        javax.swing.GroupLayout cardsBtnPanelLayout = new javax.swing.GroupLayout(cardsBtnPanel);
        cardsBtnPanel.setLayout(cardsBtnPanelLayout);
        cardsBtnPanelLayout.setHorizontalGroup(
            cardsBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardsBtnPanelLayout.createSequentialGroup()
                .addComponent(cardsBtnLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        cardsBtnPanelLayout.setVerticalGroup(
            cardsBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardsBtnPanelLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(cardsBtnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        profileBtnPanel.setBackground(new java.awt.Color(0, 0, 255));
        profileBtnPanel.setPreferredSize(new java.awt.Dimension(118, 65));
        profileBtnPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileBtnPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                profileBtnPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                profileBtnPanelMouseExited(evt);
            }
        });

        profileBtnLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        profileBtnLabel.setForeground(new java.awt.Color(255, 255, 255));
        profileBtnLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        profileBtnLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/white-user-icon.png"))); // NOI18N
        profileBtnLabel.setText(" Profile");

        javax.swing.GroupLayout profileBtnPanelLayout = new javax.swing.GroupLayout(profileBtnPanel);
        profileBtnPanel.setLayout(profileBtnPanelLayout);
        profileBtnPanelLayout.setHorizontalGroup(
            profileBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profileBtnPanelLayout.createSequentialGroup()
                .addComponent(profileBtnLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        profileBtnPanelLayout.setVerticalGroup(
            profileBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profileBtnPanelLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(profileBtnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        logoutBtnPanel.setBackground(new java.awt.Color(0, 0, 255));
        logoutBtnPanel.setPreferredSize(new java.awt.Dimension(118, 65));
        logoutBtnPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutBtnPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutBtnPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutBtnPanelMouseExited(evt);
            }
        });

        logoutBtnLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        logoutBtnLabel.setForeground(new java.awt.Color(255, 255, 255));
        logoutBtnLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoutBtnLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/white-logout-logo.png"))); // NOI18N
        logoutBtnLabel.setText(" Logout");

        javax.swing.GroupLayout logoutBtnPanelLayout = new javax.swing.GroupLayout(logoutBtnPanel);
        logoutBtnPanel.setLayout(logoutBtnPanelLayout);
        logoutBtnPanelLayout.setHorizontalGroup(
            logoutBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoutBtnPanelLayout.createSequentialGroup()
                .addComponent(logoutBtnLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        logoutBtnPanelLayout.setVerticalGroup(
            logoutBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoutBtnPanelLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(logoutBtnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout sideBarPanelLayout = new javax.swing.GroupLayout(sideBarPanel);
        sideBarPanel.setLayout(sideBarPanelLayout);
        sideBarPanelLayout.setHorizontalGroup(
            sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homeBtnPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(transferBtnPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
            .addComponent(accountBtnPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
            .addComponent(cardsBtnPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
            .addComponent(profileBtnPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
            .addComponent(logoutBtnPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        sideBarPanelLayout.setVerticalGroup(
            sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarPanelLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(homeBtnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(transferBtnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(accountBtnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(cardsBtnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(profileBtnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(logoutBtnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        backgroundPanel.add(sideBarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 643));

        transactionPanel.setBackground(new java.awt.Color(255, 255, 255));
        transactionPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        transactionTable.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 15)); // NOI18N
        transactionTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Type", "Amount", "Date & Time"
            }
        ));
        transactionTable.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(transactionTable);

        allLastTLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 21)); // NOI18N
        allLastTLabel.setForeground(new java.awt.Color(0, 51, 255));
        allLastTLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        allLastTLabel.setText("All Last Transaction");

        javax.swing.GroupLayout transactionPanelLayout = new javax.swing.GroupLayout(transactionPanel);
        transactionPanel.setLayout(transactionPanelLayout);
        transactionPanelLayout.setHorizontalGroup(
            transactionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transactionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(transactionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
                    .addComponent(allLastTLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        transactionPanelLayout.setVerticalGroup(
            transactionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, transactionPanelLayout.createSequentialGroup()
                .addComponent(allLastTLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        backgroundPanel.add(transactionPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, -1, -1));

        balancepanel1.setBackground(new java.awt.Color(255, 255, 255));
        balancepanel1.setForeground(new java.awt.Color(255, 255, 255));
        balancepanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        skyBankLabel.setBackground(new java.awt.Color(255, 255, 255));
        skyBankLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        skyBankLabel.setForeground(new java.awt.Color(255, 255, 255));
        skyBankLabel.setText("Sky Bank");
        balancepanel1.add(skyBankLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, -1, -1));

        availableBalanceLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        availableBalanceLabel.setForeground(new java.awt.Color(255, 255, 255));
        availableBalanceLabel.setText("Available Balance");
        balancepanel1.add(availableBalanceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        accountLabel.setBackground(new java.awt.Color(255, 255, 255));
        accountLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        accountLabel.setForeground(new java.awt.Color(255, 255, 255));
        accountLabel.setText("Account #   ");
        balancepanel1.add(accountLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        takaLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        takaLabel.setForeground(new java.awt.Color(255, 255, 255));
        takaLabel.setText("Taka   ");
        balancepanel1.add(takaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 250, -1));

        balanceLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/card-sky-blue.png"))); // NOI18N
        balancepanel1.add(balanceLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, -1));

        backgroundPanel.add(balancepanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 132, -1, 191));

        skyCardPanel.setBackground(new java.awt.Color(255, 255, 255));
        skyCardPanel.setPreferredSize(new java.awt.Dimension(420, 220));
        skyCardPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        shopWithUsLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        shopWithUsLabel.setForeground(new java.awt.Color(255, 255, 255));
        shopWithUsLabel.setText("Shop With Us");
        skyCardPanel.add(shopWithUsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        buyLabel.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 13)); // NOI18N
        buyLabel.setForeground(new java.awt.Color(255, 255, 255));
        buyLabel.setText("Buy Products From Our Store And");
        skyCardPanel.add(buyLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        buy2Label.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 13)); // NOI18N
        buy2Label.setForeground(new java.awt.Color(255, 255, 255));
        buy2Label.setText("Get Cashback upto Rs 1000");
        skyCardPanel.add(buy2Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        skyCardLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        skyCardLabel.setText("Sky Card");
        skyCardPanel.add(skyCardLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(689, 30, -1, -1));

        shopLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/shoping.png"))); // NOI18N
        skyCardPanel.add(shopLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 95, 258));

        skyCardLabe1.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        skyCardLabe1.setForeground(new java.awt.Color(255, 255, 255));
        skyCardLabe1.setText("Sky Card");
        skyCardPanel.add(skyCardLabe1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, -1, -1));

        skyShoppingLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/pinkblue1.png"))); // NOI18N
        skyCardPanel.add(skyShoppingLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, -1));

        backgroundPanel.add(skyCardPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(597, 386, -1, 232));

        headingLabel1.setBackground(new java.awt.Color(0, 0, 0));
        headingLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 3, 36)); // NOI18N
        headingLabel1.setForeground(new java.awt.Color(0, 51, 255));
        headingLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headingLabel1.setText("HOME");
        backgroundPanel.add(headingLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 13, 965, -1));

        balancepanel2.setBackground(new java.awt.Color(255, 255, 255));
        balancepanel2.setForeground(new java.awt.Color(255, 255, 255));
        balancepanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        skyBankLabel1.setBackground(new java.awt.Color(255, 255, 255));
        skyBankLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        skyBankLabel1.setForeground(new java.awt.Color(255, 255, 255));
        skyBankLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/visa-icon.png"))); // NOI18N
        balancepanel2.add(skyBankLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, -1, -1));

        availableBalanceLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        availableBalanceLabel1.setForeground(new java.awt.Color(255, 255, 255));
        availableBalanceLabel1.setText("Credit Card Balance");
        balancepanel2.add(availableBalanceLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        accountLabel1.setBackground(new java.awt.Color(255, 255, 255));
        accountLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        accountLabel1.setForeground(new java.awt.Color(255, 255, 255));
        balancepanel2.add(accountLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 240, 20));

        takaLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        takaLabel1.setForeground(new java.awt.Color(255, 255, 255));
        takaLabel1.setText("$   ");
        balancepanel2.add(takaLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 250, -1));

        balanceLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/card.png"))); // NOI18N
        balancepanel2.add(balanceLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, -1));

        backgroundPanel.add(balancepanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 386, -1, 191));

        helloLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        helloLabel.setForeground(new java.awt.Color(0, 51, 255));
        backgroundPanel.add(helloLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 280, 40));

        welcomeLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 2, 14)); // NOI18N
        welcomeLabel.setForeground(new java.awt.Color(102, 102, 102));
        welcomeLabel.setText("Welcome to Sky Bank");
        backgroundPanel.add(welcomeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, -1, -1));

        closeBtnLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/close-btn.png"))); // NOI18N
        closeBtnLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBtnLabelMouseClicked(evt);
            }
        });
        backgroundPanel.add(closeBtnLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void homeBtnPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBtnPanelMouseEntered
        JPanel btn= homeBtnPanel;
        isEntered(btn);
    }//GEN-LAST:event_homeBtnPanelMouseEntered

    private void homeBtnPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBtnPanelMouseExited
        JPanel btn= homeBtnPanel;
        isExited(btn);
    }//GEN-LAST:event_homeBtnPanelMouseExited

    private void transferBtnPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transferBtnPanelMouseEntered
        JPanel btn= transferBtnPanel;
        isEntered(btn);
    }//GEN-LAST:event_transferBtnPanelMouseEntered

    private void transferBtnPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transferBtnPanelMouseExited
        JPanel btn= transferBtnPanel;
        isExited(btn);
    }//GEN-LAST:event_transferBtnPanelMouseExited

    private void transferBtnPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transferBtnPanelMouseClicked
        Transfer TF;
        try {
            TF = new Transfer(accountNumber);
            setVisible(false);
            TF.setVisible(true);
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_transferBtnPanelMouseClicked

    private void accountBtnPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountBtnPanelMouseEntered
        JPanel btn= accountBtnPanel;
        isEntered(btn);
    }//GEN-LAST:event_accountBtnPanelMouseEntered

    private void accountBtnPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountBtnPanelMouseClicked
        Account A;
        try {
            A = new Account(accountNumber);
            setVisible(false);
            A.setVisible(true);
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_accountBtnPanelMouseClicked

    private void accountBtnPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountBtnPanelMouseExited
        JPanel btn= accountBtnPanel;
        isExited(btn);
    }//GEN-LAST:event_accountBtnPanelMouseExited

    private void homeBtnPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBtnPanelMouseClicked
        /*Home H= new Home();
        setVisible(false);
        H.setVisible(true);
        dispose();*/
    }//GEN-LAST:event_homeBtnPanelMouseClicked

    private void cardsBtnPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cardsBtnPanelMouseEntered
        JPanel btn= cardsBtnPanel;
        isEntered(btn);
    }//GEN-LAST:event_cardsBtnPanelMouseEntered

    private void cardsBtnPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cardsBtnPanelMouseExited
        JPanel btn= cardsBtnPanel;
        isExited(btn);
    }//GEN-LAST:event_cardsBtnPanelMouseExited

    private void cardsBtnPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cardsBtnPanelMouseClicked
        Cards CD;
        try {
            CD = new Cards(accountNumber);
            setVisible(false);
            CD.setVisible(true);
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_cardsBtnPanelMouseClicked

    private void profileBtnPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileBtnPanelMouseEntered
        JPanel btn= profileBtnPanel;
        isEntered(btn);
    }//GEN-LAST:event_profileBtnPanelMouseEntered

    private void profileBtnPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileBtnPanelMouseExited
        JPanel btn= profileBtnPanel;
        isExited(btn);
    }//GEN-LAST:event_profileBtnPanelMouseExited

    private void profileBtnPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileBtnPanelMouseClicked
        Profile P;
        try {
            P = new Profile(accountNumber);
            setVisible(false);
            P.setVisible(true);
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_profileBtnPanelMouseClicked

    private void logoutBtnPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnPanelMouseEntered
        JPanel btn= logoutBtnPanel;
        isEntered(btn);
    }//GEN-LAST:event_logoutBtnPanelMouseEntered

    private void logoutBtnPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnPanelMouseExited
        JPanel btn= logoutBtnPanel;
        isExited(btn);
    }//GEN-LAST:event_logoutBtnPanelMouseExited

    private void logoutBtnPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnPanelMouseClicked
        Login L= new Login();
        setVisible(false);
        L.setVisible(true);
        dispose();
    }//GEN-LAST:event_logoutBtnPanelMouseClicked

    private void closeBtnLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnLabelMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeBtnLabelMouseClicked
    void isEntered(JPanel btn)
    {
        btn.setBackground(new Color(0,0,204));
    }
    
    void isExited(JPanel btn)
    {
        btn.setBackground(new Color(0,0,255));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Home("").setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountBtnLabel;
    private javax.swing.JPanel accountBtnPanel;
    private javax.swing.JLabel accountLabel;
    private javax.swing.JLabel accountLabel1;
    private javax.swing.JLabel allLastTLabel;
    private javax.swing.JLabel availableBalanceLabel;
    private javax.swing.JLabel availableBalanceLabel1;
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JLabel balanceLabel1;
    private javax.swing.JLabel balanceLabel2;
    private javax.swing.JPanel balancepanel1;
    private javax.swing.JPanel balancepanel2;
    private javax.swing.JLabel buy2Label;
    private javax.swing.JLabel buyLabel;
    private javax.swing.JLabel cardsBtnLabel;
    private javax.swing.JPanel cardsBtnPanel;
    private javax.swing.JLabel closeBtnLabel;
    private javax.swing.JLabel headingLabel1;
    private javax.swing.JLabel helloLabel;
    private javax.swing.JLabel homeBtnLabel;
    private javax.swing.JPanel homeBtnPanel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logoutBtnLabel;
    private javax.swing.JPanel logoutBtnPanel;
    private javax.swing.JLabel profileBtnLabel;
    private javax.swing.JPanel profileBtnPanel;
    private javax.swing.JLabel shopLabel;
    private javax.swing.JLabel shopWithUsLabel;
    private javax.swing.JPanel sideBarPanel;
    private javax.swing.JLabel skyBankLabel;
    private javax.swing.JLabel skyBankLabel1;
    private javax.swing.JLabel skyCardLabe1;
    private javax.swing.JLabel skyCardLabel;
    private javax.swing.JPanel skyCardPanel;
    private javax.swing.JLabel skyShoppingLabel;
    private javax.swing.JLabel takaLabel;
    private javax.swing.JLabel takaLabel1;
    private javax.swing.JPanel transactionPanel;
    private javax.swing.JTable transactionTable;
    private javax.swing.JLabel transferBtnLabel;
    private javax.swing.JPanel transferBtnPanel;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
