
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hp
 */
public class Message extends javax.swing.JFrame {

    /**
     * Creates new form Message
     */
    String accountNumber;
    public Message(String accountNumber) {
        this.accountNumber=accountNumber;
        initComponents();
   
        
            Conn c=new Conn();
                
            String query1="select * from message where accountNumber = '"+accountNumber+"'";
           // String m="";
                
            ResultSet rs1;
        try {
            rs1 = c.s.executeQuery(query1);
            while(rs1.next())
            {
                String name=rs1.getString("Name");
                String message=rs1.getString("Message");
                //System.out.println("Asik\nHossain");
                messageTextArea.setText(messageTextArea.getText()+"\n "+name+" : "+message+"\n");
               // m=m+name+" : "+message+"\n";
                
                
            }
           // messageLabel.setText(m);
        } catch (SQLException ex) {
            Logger.getLogger(Message.class.getName()).log(Level.SEVERE, null, ex);
        }
            
                    
                    
                    
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        password3Panel = new javax.swing.JPanel();
        password3_2Panel = new javax.swing.JPanel();
        forgotPasswordLabel = new javax.swing.JLabel();
        logoLabel = new javax.swing.JLabel();
        closeBtnLabel = new javax.swing.JLabel();
        closeBtnLabel1 = new javax.swing.JLabel();
        messageTextField = new javax.swing.JTextField();
        sendMessageLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        messageTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        password3Panel.setBackground(new java.awt.Color(0, 51, 255));
        password3Panel.setPreferredSize(new java.awt.Dimension(1120, 630));

        password3_2Panel.setBackground(new java.awt.Color(255, 255, 255));
        password3_2Panel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        password3_2Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        forgotPasswordLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        forgotPasswordLabel.setForeground(new java.awt.Color(0, 51, 255));
        forgotPasswordLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        forgotPasswordLabel.setText("Chat With Sky Bank");
        password3_2Panel.add(forgotPasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 40, 1030, -1));

        logoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/verified-mail.png"))); // NOI18N
        password3_2Panel.add(logoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 55, 1021, -1));

        closeBtnLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/goback.png"))); // NOI18N
        closeBtnLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBtnLabelMouseClicked(evt);
            }
        });
        password3_2Panel.add(closeBtnLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        closeBtnLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/close-btn.png"))); // NOI18N
        closeBtnLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBtnLabel1MouseClicked(evt);
            }
        });
        password3_2Panel.add(closeBtnLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 10, 30, -1));

        messageTextField.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
        messageTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                messageTextFieldActionPerformed(evt);
            }
        });
        password3_2Panel.add(messageTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, 830, 40));

        sendMessageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/goback.png"))); // NOI18N
        sendMessageLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sendMessageLabelMouseClicked(evt);
            }
        });
        password3_2Panel.add(sendMessageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 430, -1, 40));

        messageTextArea.setColumns(20);
        messageTextArea.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
        messageTextArea.setRows(5);
        jScrollPane1.setViewportView(messageTextArea);

        password3_2Panel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 870, 210));

        javax.swing.GroupLayout password3PanelLayout = new javax.swing.GroupLayout(password3Panel);
        password3Panel.setLayout(password3PanelLayout);
        password3PanelLayout.setHorizontalGroup(
            password3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, password3PanelLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(password3_2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 1048, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        password3PanelLayout.setVerticalGroup(
            password3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(password3PanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(password3_2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(password3Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(password3Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeBtnLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnLabelMouseClicked
        Account A;
        try {
            A = new Account(accountNumber);
            setVisible(false);
            A.setVisible(true);
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(Message.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_closeBtnLabelMouseClicked

    private void closeBtnLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnLabel1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeBtnLabel1MouseClicked

    private void sendMessageLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendMessageLabelMouseClicked

        try{                                              
            
            String accountN=accountNumber;
            String message=messageTextField.getText();
            String name="";
            Conn c=new Conn();
            String query="select * from addApplication1 where accountNumber = '"+accountNumber+"'";
            
            ResultSet rs = c.s.executeQuery(query);
            if(rs.next())
            {
                name=rs.getString("firstName");
                
            }
            
            
            
            try{
                if(message.equals(""))
                {
                    if(message.equals(""))
                    {
                        JOptionPane.showMessageDialog(null,"Write Any Query For Send");
                    }
                }else{
                    //Conn c=new Conn();
                    String query1="insert into Message values('"+accountNumber+"', '"+name+"', '"+message+"')";
                    c.s.executeUpdate(query1);
                    
                    Message M= new Message(accountNumber);
                    setVisible(false);
                    M.setVisible(true);
                    dispose();
                }
            }catch(Exception e){
                System.out.println(e);
            }
            // TODO add your handling code here:
        }catch(SQLException ex){
            Logger.getLogger(Message.class.getName()).log(Level.SEVERE, null,ex);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_sendMessageLabelMouseClicked

    private void messageTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_messageTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_messageTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Message.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Message.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Message.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Message.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Message("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel closeBtnLabel;
    private javax.swing.JLabel closeBtnLabel1;
    private javax.swing.JLabel forgotPasswordLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JTextArea messageTextArea;
    private javax.swing.JTextField messageTextField;
    private javax.swing.JPanel password3Panel;
    private javax.swing.JPanel password3_2Panel;
    private javax.swing.JLabel sendMessageLabel;
    // End of variables declaration//GEN-END:variables
}
