
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hp
 */
public class Password2 extends javax.swing.JFrame {

    /**
     * Creates new form Password2
     */
    String accountNumber;
    public Password2(String accountNumber) {
        this.accountNumber=accountNumber;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        password2Panel = new javax.swing.JPanel();
        password2_2Panel = new javax.swing.JPanel();
        logoLabel = new javax.swing.JLabel();
        verifyYourOneTimePasswordLabel = new javax.swing.JLabel();
        verifyOTPButton = new javax.swing.JButton();
        enterOTPLabel = new javax.swing.JLabel();
        enterOTPTextField = new javax.swing.JTextField();
        forgotPasswordLabel = new javax.swing.JLabel();
        noteLabel = new javax.swing.JLabel();
        noteLabel2 = new javax.swing.JLabel();
        closeBtnLabel = new javax.swing.JLabel();
        closeBtnLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        password2Panel.setBackground(new java.awt.Color(0, 51, 255));
        password2Panel.setPreferredSize(new java.awt.Dimension(1120, 630));

        password2_2Panel.setBackground(new java.awt.Color(255, 255, 255));
        password2_2Panel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        password2_2Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/validate-pass.png"))); // NOI18N
        password2_2Panel.add(logoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 78, 1045, -1));

        verifyYourOneTimePasswordLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 36)); // NOI18N
        verifyYourOneTimePasswordLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        verifyYourOneTimePasswordLabel.setText("Verify Your One Time Password");
        password2_2Panel.add(verifyYourOneTimePasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 191, 1045, -1));

        verifyOTPButton.setBackground(new java.awt.Color(0, 51, 102));
        verifyOTPButton.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        verifyOTPButton.setForeground(new java.awt.Color(255, 255, 255));
        verifyOTPButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/check-sm.png"))); // NOI18N
        verifyOTPButton.setText(" Verify OTP");
        verifyOTPButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        verifyOTPButton.setMaximumSize(new java.awt.Dimension(120, 40));
        verifyOTPButton.setMinimumSize(new java.awt.Dimension(120, 40));
        verifyOTPButton.setPreferredSize(new java.awt.Dimension(120, 40));
        verifyOTPButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verifyOTPButtonMouseClicked(evt);
            }
        });
        verifyOTPButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verifyOTPButtonActionPerformed(evt);
            }
        });
        password2_2Panel.add(verifyOTPButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 419, 300, -1));

        enterOTPLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        enterOTPLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        enterOTPLabel.setText("Enter OTP");
        password2_2Panel.add(enterOTPLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 338, 301, -1));

        enterOTPTextField.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        enterOTPTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        enterOTPTextField.setToolTipText("Please Enter OTP");
        password2_2Panel.add(enterOTPTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 367, 301, 34));

        forgotPasswordLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        forgotPasswordLabel.setForeground(new java.awt.Color(0, 51, 255));
        forgotPasswordLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        forgotPasswordLabel.setText("Forgot Password");
        password2_2Panel.add(forgotPasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 50, 1021, -1));

        noteLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        noteLabel.setForeground(new java.awt.Color(0, 51, 255));
        noteLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        noteLabel.setText("Account Verify Successfully!!!");
        password2_2Panel.add(noteLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 271, 1021, -1));

        noteLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        noteLabel2.setForeground(new java.awt.Color(0, 51, 255));
        noteLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        noteLabel2.setText("Please Check Your E-Mail For OTP");
        password2_2Panel.add(noteLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 299, 1021, -1));

        closeBtnLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/goback.png"))); // NOI18N
        closeBtnLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBtnLabelMouseClicked(evt);
            }
        });
        password2_2Panel.add(closeBtnLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        closeBtnLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/close-btn.png"))); // NOI18N
        closeBtnLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBtnLabel1MouseClicked(evt);
            }
        });
        password2_2Panel.add(closeBtnLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 10, 30, -1));

        javax.swing.GroupLayout password2PanelLayout = new javax.swing.GroupLayout(password2Panel);
        password2Panel.setLayout(password2PanelLayout);
        password2PanelLayout.setHorizontalGroup(
            password2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, password2PanelLayout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(password2_2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        password2PanelLayout.setVerticalGroup(
            password2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(password2PanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(password2_2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(password2Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(password2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void verifyOTPButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verifyOTPButtonMouseClicked
        /*createAccount4 AC4= new createAccount4();
        setVisible(false);
        AC4.setVisible(true);
        dispose();*/
    }//GEN-LAST:event_verifyOTPButtonMouseClicked

    private void verifyOTPButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verifyOTPButtonActionPerformed
        if(enterOTPTextField.getText().equals("5695")){
            Password3 Pass3= new Password3(accountNumber);
            setVisible(false);
            Pass3.setVisible(true);
            dispose();
        }else{
            JOptionPane.showMessageDialog(null,"Incorrect OTP");
        }
        
    }//GEN-LAST:event_verifyOTPButtonActionPerformed

    private void closeBtnLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnLabelMouseClicked
        Login L=new Login();
        setVisible(false);
        L.setVisible(true);
        dispose();
    }//GEN-LAST:event_closeBtnLabelMouseClicked

    private void closeBtnLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnLabel1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeBtnLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Password2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Password2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Password2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Password2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Password2("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel closeBtnLabel;
    private javax.swing.JLabel closeBtnLabel1;
    private javax.swing.JLabel enterOTPLabel;
    private javax.swing.JTextField enterOTPTextField;
    private javax.swing.JLabel forgotPasswordLabel;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JLabel noteLabel;
    private javax.swing.JLabel noteLabel2;
    private javax.swing.JPanel password2Panel;
    private javax.swing.JPanel password2_2Panel;
    private javax.swing.JButton verifyOTPButton;
    private javax.swing.JLabel verifyYourOneTimePasswordLabel;
    // End of variables declaration//GEN-END:variables
}
