
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hp
 */
public class Profile extends javax.swing.JFrame {

    /**
     * Creates new form Profile
     */
    String accountNumber;
    public Profile(String accountNumber) throws SQLException {
        this.accountNumber=accountNumber;
        initComponents();
        Conn c=new Conn();
        
        accountNumberTypeLabel2.setText(accountNumberTypeLabel2.getText()+accountNumber);

        int count=1;
        
        if(count>=0)
        {  
            String query1="select * from createAccount1 where accountNumber = '"+accountNumber+"'";
            ResultSet rs1 = c.s.executeQuery(query1);
            if(rs1.next())
            {
                String type=rs1.getString("username");
                userLabel2.setText(userLabel2.getText()+type);
            }
        }
   
        
        if(count>=0)
        {
            String query1="select * from addApplication3 where accountNumber = '"+accountNumber+"'";
            ResultSet rs1 = c.s.executeQuery(query1);
            if(rs1.next())
            {
                
                String address=rs1.getString("accountType");
                accountTypeLabel2.setText(accountTypeLabel2.getText()+address);
            }
                
            
            
        }
        if(count>=0)
        {
            String query1="select * from addApplication1 where accountNumber = '"+accountNumber+"'";
                
            ResultSet rs1 = c.s.executeQuery(query1);
            if(rs1.next())
            {
                String fName=rs1.getString("firstName");
                String LName=rs1.getString("lastName");
                NameLabel.setText(NameLabel.getText()+fName+" "+LName);
                
                String pNum=rs1.getString("phoneNumber");
                PhoneNumberLabel2.setText(PhoneNumberLabel2.getText()+pNum);
                
                String email=rs1.getString("emailAddress");
                emailLabel2.setText(emailLabel2.getText()+email);
            }
            
        }
        if(count>=0)
        {
            String query1="select * from addApplication2_1 where accountNumber = '"+accountNumber+"'";
                
            ResultSet rs1 = c.s.executeQuery(query1);
            if(rs1.next())
            {
                String address=rs1.getString("presentAddress");
                AddressLabel2.setText(AddressLabel2.getText()+address);
            }
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sideBarPanel = new javax.swing.JPanel();
        homeBtnPanel = new javax.swing.JPanel();
        homeBtnLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        homeBtnPanel1 = new javax.swing.JPanel();
        transferBtnLabel = new javax.swing.JLabel();
        homeBtnPanel2 = new javax.swing.JPanel();
        accountBtnLabel = new javax.swing.JLabel();
        homeBtnPanel3 = new javax.swing.JPanel();
        cardsBtnLabel = new javax.swing.JLabel();
        homeBtnPanel4 = new javax.swing.JPanel();
        profileBtnLabel = new javax.swing.JLabel();
        homeBtnPanel5 = new javax.swing.JPanel();
        logoutBtnLabel = new javax.swing.JLabel();
        profilePanel = new javax.swing.JPanel();
        sideBarPanel1 = new javax.swing.JPanel();
        homeBtnPanel6 = new javax.swing.JPanel();
        homeBtnLabel1 = new javax.swing.JLabel();
        transferBtnPanel = new javax.swing.JPanel();
        transferBtnLabel1 = new javax.swing.JLabel();
        accountBtnPanel = new javax.swing.JPanel();
        accountBtnLabel1 = new javax.swing.JLabel();
        cardsBtnPanel = new javax.swing.JPanel();
        cardsBtnLabel1 = new javax.swing.JLabel();
        profileBtnPanel = new javax.swing.JPanel();
        profileBtnLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        logoutBtnPanel = new javax.swing.JPanel();
        logoutBtnLabel1 = new javax.swing.JLabel();
        headingLabel1 = new javax.swing.JLabel();
        admin2_2Panel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        userLabel1 = new javax.swing.JLabel();
        userLabel2 = new javax.swing.JLabel();
        accountNumberTypeLabel1 = new javax.swing.JLabel();
        accountNumberTypeLabel2 = new javax.swing.JLabel();
        accountTypeLabel1 = new javax.swing.JLabel();
        accountTypeLabel2 = new javax.swing.JLabel();
        PhoneNumberLabel1 = new javax.swing.JLabel();
        PhoneNumberLabel2 = new javax.swing.JLabel();
        emailLabel2 = new javax.swing.JLabel();
        emailLabel1 = new javax.swing.JLabel();
        AddressLabel2 = new javax.swing.JLabel();
        AddressLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        NameLabel = new javax.swing.JLabel();
        accountSettingsButton = new javax.swing.JButton();
        closeBtnLabel = new javax.swing.JLabel();

        sideBarPanel.setBackground(new java.awt.Color(0, 51, 255));

        homeBtnPanel.setBackground(new java.awt.Color(0, 0, 255));

        homeBtnLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        homeBtnLabel.setForeground(new java.awt.Color(255, 255, 255));
        homeBtnLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homeBtnLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/white-home.png"))); // NOI18N
        homeBtnLabel.setText(" Home");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/white-indicate.png"))); // NOI18N

        javax.swing.GroupLayout homeBtnPanelLayout = new javax.swing.GroupLayout(homeBtnPanel);
        homeBtnPanel.setLayout(homeBtnPanelLayout);
        homeBtnPanelLayout.setHorizontalGroup(
            homeBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeBtnPanelLayout.createSequentialGroup()
                .addComponent(homeBtnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        homeBtnPanelLayout.setVerticalGroup(
            homeBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homeBtnPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homeBtnLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addContainerGap())
        );

        homeBtnPanel1.setBackground(new java.awt.Color(0, 0, 255));
        homeBtnPanel1.setPreferredSize(new java.awt.Dimension(118, 65));

        transferBtnLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        transferBtnLabel.setForeground(new java.awt.Color(255, 255, 255));
        transferBtnLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        transferBtnLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/transfer-icon.png"))); // NOI18N
        transferBtnLabel.setText(" Transfer");

        javax.swing.GroupLayout homeBtnPanel1Layout = new javax.swing.GroupLayout(homeBtnPanel1);
        homeBtnPanel1.setLayout(homeBtnPanel1Layout);
        homeBtnPanel1Layout.setHorizontalGroup(
            homeBtnPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(transferBtnLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        homeBtnPanel1Layout.setVerticalGroup(
            homeBtnPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeBtnPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(transferBtnLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addContainerGap())
        );

        homeBtnPanel2.setBackground(new java.awt.Color(0, 0, 255));
        homeBtnPanel2.setPreferredSize(new java.awt.Dimension(118, 65));

        accountBtnLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        accountBtnLabel.setForeground(new java.awt.Color(255, 255, 255));
        accountBtnLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        accountBtnLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/white-moneybag.png"))); // NOI18N
        accountBtnLabel.setText(" Account");

        javax.swing.GroupLayout homeBtnPanel2Layout = new javax.swing.GroupLayout(homeBtnPanel2);
        homeBtnPanel2.setLayout(homeBtnPanel2Layout);
        homeBtnPanel2Layout.setHorizontalGroup(
            homeBtnPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(accountBtnLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        homeBtnPanel2Layout.setVerticalGroup(
            homeBtnPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homeBtnPanel2Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(accountBtnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        homeBtnPanel3.setBackground(new java.awt.Color(0, 0, 255));
        homeBtnPanel3.setPreferredSize(new java.awt.Dimension(118, 65));

        cardsBtnLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        cardsBtnLabel.setForeground(new java.awt.Color(255, 255, 255));
        cardsBtnLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cardsBtnLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/white-card.png"))); // NOI18N
        cardsBtnLabel.setText(" Cards");

        javax.swing.GroupLayout homeBtnPanel3Layout = new javax.swing.GroupLayout(homeBtnPanel3);
        homeBtnPanel3.setLayout(homeBtnPanel3Layout);
        homeBtnPanel3Layout.setHorizontalGroup(
            homeBtnPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeBtnPanel3Layout.createSequentialGroup()
                .addComponent(cardsBtnLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        homeBtnPanel3Layout.setVerticalGroup(
            homeBtnPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homeBtnPanel3Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(cardsBtnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        homeBtnPanel4.setBackground(new java.awt.Color(0, 0, 255));
        homeBtnPanel4.setPreferredSize(new java.awt.Dimension(118, 65));

        profileBtnLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        profileBtnLabel.setForeground(new java.awt.Color(255, 255, 255));
        profileBtnLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        profileBtnLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/white-user-icon.png"))); // NOI18N
        profileBtnLabel.setText(" Profile");

        javax.swing.GroupLayout homeBtnPanel4Layout = new javax.swing.GroupLayout(homeBtnPanel4);
        homeBtnPanel4.setLayout(homeBtnPanel4Layout);
        homeBtnPanel4Layout.setHorizontalGroup(
            homeBtnPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeBtnPanel4Layout.createSequentialGroup()
                .addComponent(profileBtnLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        homeBtnPanel4Layout.setVerticalGroup(
            homeBtnPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homeBtnPanel4Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(profileBtnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        homeBtnPanel5.setBackground(new java.awt.Color(0, 0, 255));
        homeBtnPanel5.setPreferredSize(new java.awt.Dimension(118, 65));

        logoutBtnLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        logoutBtnLabel.setForeground(new java.awt.Color(255, 255, 255));
        logoutBtnLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoutBtnLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/white-logout-logo.png"))); // NOI18N
        logoutBtnLabel.setText(" Logout");

        javax.swing.GroupLayout homeBtnPanel5Layout = new javax.swing.GroupLayout(homeBtnPanel5);
        homeBtnPanel5.setLayout(homeBtnPanel5Layout);
        homeBtnPanel5Layout.setHorizontalGroup(
            homeBtnPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeBtnPanel5Layout.createSequentialGroup()
                .addComponent(logoutBtnLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        homeBtnPanel5Layout.setVerticalGroup(
            homeBtnPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homeBtnPanel5Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(logoutBtnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout sideBarPanelLayout = new javax.swing.GroupLayout(sideBarPanel);
        sideBarPanel.setLayout(sideBarPanelLayout);
        sideBarPanelLayout.setHorizontalGroup(
            sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homeBtnPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
            .addComponent(homeBtnPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
            .addComponent(homeBtnPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
            .addComponent(homeBtnPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
            .addComponent(homeBtnPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
            .addComponent(homeBtnPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        sideBarPanelLayout.setVerticalGroup(
            sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarPanelLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(homeBtnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(homeBtnPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(homeBtnPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(homeBtnPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(homeBtnPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(homeBtnPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        profilePanel.setBackground(new java.awt.Color(255, 255, 255));
        profilePanel.setMinimumSize(new java.awt.Dimension(1120, 82));
        profilePanel.setPreferredSize(new java.awt.Dimension(1120, 630));
        profilePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sideBarPanel1.setBackground(new java.awt.Color(0, 51, 255));

        homeBtnPanel6.setBackground(new java.awt.Color(0, 0, 255));
        homeBtnPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeBtnPanel6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeBtnPanel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeBtnPanel6MouseExited(evt);
            }
        });

        homeBtnLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        homeBtnLabel1.setForeground(new java.awt.Color(255, 255, 255));
        homeBtnLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homeBtnLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/white-home.png"))); // NOI18N
        homeBtnLabel1.setText(" Home");

        javax.swing.GroupLayout homeBtnPanel6Layout = new javax.swing.GroupLayout(homeBtnPanel6);
        homeBtnPanel6.setLayout(homeBtnPanel6Layout);
        homeBtnPanel6Layout.setHorizontalGroup(
            homeBtnPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeBtnPanel6Layout.createSequentialGroup()
                .addComponent(homeBtnLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        homeBtnPanel6Layout.setVerticalGroup(
            homeBtnPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homeBtnPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homeBtnLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addContainerGap())
        );

        transferBtnPanel.setBackground(new java.awt.Color(0, 0, 255));
        transferBtnPanel.setPreferredSize(new java.awt.Dimension(118, 65));
        transferBtnPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transferBtnPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                transferBtnPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                transferBtnPanelMouseExited(evt);
            }
        });

        transferBtnLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        transferBtnLabel1.setForeground(new java.awt.Color(255, 255, 255));
        transferBtnLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        transferBtnLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/transfer-icon.png"))); // NOI18N
        transferBtnLabel1.setText(" Transfer");

        javax.swing.GroupLayout transferBtnPanelLayout = new javax.swing.GroupLayout(transferBtnPanel);
        transferBtnPanel.setLayout(transferBtnPanelLayout);
        transferBtnPanelLayout.setHorizontalGroup(
            transferBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(transferBtnLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        transferBtnPanelLayout.setVerticalGroup(
            transferBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transferBtnPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(transferBtnLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addContainerGap())
        );

        accountBtnPanel.setBackground(new java.awt.Color(0, 0, 255));
        accountBtnPanel.setPreferredSize(new java.awt.Dimension(118, 65));
        accountBtnPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accountBtnPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                accountBtnPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                accountBtnPanelMouseExited(evt);
            }
        });

        accountBtnLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        accountBtnLabel1.setForeground(new java.awt.Color(255, 255, 255));
        accountBtnLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        accountBtnLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/white-moneybag.png"))); // NOI18N
        accountBtnLabel1.setText(" Account");

        javax.swing.GroupLayout accountBtnPanelLayout = new javax.swing.GroupLayout(accountBtnPanel);
        accountBtnPanel.setLayout(accountBtnPanelLayout);
        accountBtnPanelLayout.setHorizontalGroup(
            accountBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(accountBtnLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        accountBtnPanelLayout.setVerticalGroup(
            accountBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, accountBtnPanelLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(accountBtnLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        cardsBtnPanel.setBackground(new java.awt.Color(0, 0, 255));
        cardsBtnPanel.setPreferredSize(new java.awt.Dimension(118, 65));
        cardsBtnPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cardsBtnPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cardsBtnPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cardsBtnPanelMouseExited(evt);
            }
        });

        cardsBtnLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        cardsBtnLabel1.setForeground(new java.awt.Color(255, 255, 255));
        cardsBtnLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cardsBtnLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/white-card.png"))); // NOI18N
        cardsBtnLabel1.setText(" Cards");

        javax.swing.GroupLayout cardsBtnPanelLayout = new javax.swing.GroupLayout(cardsBtnPanel);
        cardsBtnPanel.setLayout(cardsBtnPanelLayout);
        cardsBtnPanelLayout.setHorizontalGroup(
            cardsBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardsBtnPanelLayout.createSequentialGroup()
                .addComponent(cardsBtnLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        cardsBtnPanelLayout.setVerticalGroup(
            cardsBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardsBtnPanelLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(cardsBtnLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        profileBtnPanel.setBackground(new java.awt.Color(0, 0, 255));
        profileBtnPanel.setPreferredSize(new java.awt.Dimension(118, 65));
        profileBtnPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileBtnPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                profileBtnPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                profileBtnPanelMouseExited(evt);
            }
        });

        profileBtnLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        profileBtnLabel1.setForeground(new java.awt.Color(255, 255, 255));
        profileBtnLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        profileBtnLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/white-user-icon.png"))); // NOI18N
        profileBtnLabel1.setText(" Profile");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/white-indicate.png"))); // NOI18N

        javax.swing.GroupLayout profileBtnPanelLayout = new javax.swing.GroupLayout(profileBtnPanel);
        profileBtnPanel.setLayout(profileBtnPanelLayout);
        profileBtnPanelLayout.setHorizontalGroup(
            profileBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profileBtnPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(profileBtnLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        profileBtnPanelLayout.setVerticalGroup(
            profileBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(profileBtnPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(profileBtnLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        logoutBtnPanel.setBackground(new java.awt.Color(0, 0, 255));
        logoutBtnPanel.setPreferredSize(new java.awt.Dimension(118, 65));
        logoutBtnPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutBtnPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutBtnPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutBtnPanelMouseExited(evt);
            }
        });

        logoutBtnLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        logoutBtnLabel1.setForeground(new java.awt.Color(255, 255, 255));
        logoutBtnLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoutBtnLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/white-logout-logo.png"))); // NOI18N
        logoutBtnLabel1.setText(" Logout");

        javax.swing.GroupLayout logoutBtnPanelLayout = new javax.swing.GroupLayout(logoutBtnPanel);
        logoutBtnPanel.setLayout(logoutBtnPanelLayout);
        logoutBtnPanelLayout.setHorizontalGroup(
            logoutBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoutBtnPanelLayout.createSequentialGroup()
                .addComponent(logoutBtnLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        logoutBtnPanelLayout.setVerticalGroup(
            logoutBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoutBtnPanelLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(logoutBtnLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout sideBarPanel1Layout = new javax.swing.GroupLayout(sideBarPanel1);
        sideBarPanel1.setLayout(sideBarPanel1Layout);
        sideBarPanel1Layout.setHorizontalGroup(
            sideBarPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homeBtnPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(transferBtnPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
            .addComponent(accountBtnPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
            .addComponent(cardsBtnPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
            .addComponent(profileBtnPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
            .addComponent(logoutBtnPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        sideBarPanel1Layout.setVerticalGroup(
            sideBarPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(homeBtnPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(transferBtnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(accountBtnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(cardsBtnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(profileBtnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(logoutBtnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        profilePanel.add(sideBarPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        headingLabel1.setBackground(new java.awt.Color(0, 0, 0));
        headingLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 3, 36)); // NOI18N
        headingLabel1.setForeground(new java.awt.Color(0, 51, 255));
        headingLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headingLabel1.setText("PROFILE");
        profilePanel.add(headingLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 13, 970, -1));

        admin2_2Panel.setBackground(new java.awt.Color(0, 51, 255));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/male-profile.png"))); // NOI18N

        userLabel1.setBackground(new java.awt.Color(255, 255, 255));
        userLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
        userLabel1.setForeground(new java.awt.Color(255, 255, 255));
        userLabel1.setText("Username :");

        userLabel2.setBackground(new java.awt.Color(255, 255, 255));
        userLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
        userLabel2.setForeground(new java.awt.Color(255, 255, 255));

        accountNumberTypeLabel1.setBackground(new java.awt.Color(255, 255, 255));
        accountNumberTypeLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
        accountNumberTypeLabel1.setForeground(new java.awt.Color(255, 255, 255));
        accountNumberTypeLabel1.setText("Account Number :");

        accountNumberTypeLabel2.setBackground(new java.awt.Color(255, 255, 255));
        accountNumberTypeLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
        accountNumberTypeLabel2.setForeground(new java.awt.Color(255, 255, 255));

        accountTypeLabel1.setBackground(new java.awt.Color(255, 255, 255));
        accountTypeLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
        accountTypeLabel1.setForeground(new java.awt.Color(255, 255, 255));
        accountTypeLabel1.setText("Account Type :");

        accountTypeLabel2.setBackground(new java.awt.Color(255, 255, 255));
        accountTypeLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
        accountTypeLabel2.setForeground(new java.awt.Color(255, 255, 255));

        PhoneNumberLabel1.setBackground(new java.awt.Color(255, 255, 255));
        PhoneNumberLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
        PhoneNumberLabel1.setForeground(new java.awt.Color(255, 255, 255));
        PhoneNumberLabel1.setText("Phone Number :");

        PhoneNumberLabel2.setBackground(new java.awt.Color(255, 255, 255));
        PhoneNumberLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
        PhoneNumberLabel2.setForeground(new java.awt.Color(255, 255, 255));

        emailLabel2.setBackground(new java.awt.Color(255, 255, 255));
        emailLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
        emailLabel2.setForeground(new java.awt.Color(255, 255, 255));

        emailLabel1.setBackground(new java.awt.Color(255, 255, 255));
        emailLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
        emailLabel1.setForeground(new java.awt.Color(255, 255, 255));
        emailLabel1.setText("Email :");

        AddressLabel2.setBackground(new java.awt.Color(255, 255, 255));
        AddressLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
        AddressLabel2.setForeground(new java.awt.Color(255, 255, 255));

        AddressLabel1.setBackground(new java.awt.Color(255, 255, 255));
        AddressLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
        AddressLabel1.setForeground(new java.awt.Color(255, 255, 255));
        AddressLabel1.setText("Address :");

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(368, 5));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 368, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        NameLabel.setBackground(new java.awt.Color(255, 255, 255));
        NameLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 30)); // NOI18N
        NameLabel.setForeground(new java.awt.Color(255, 255, 255));
        NameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        accountSettingsButton.setBackground(new java.awt.Color(0, 51, 102));
        accountSettingsButton.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        accountSettingsButton.setForeground(new java.awt.Color(255, 255, 255));
        accountSettingsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/white-user-icon.png"))); // NOI18N
        accountSettingsButton.setText(" Account Settings");
        accountSettingsButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        accountSettingsButton.setMaximumSize(new java.awt.Dimension(120, 40));
        accountSettingsButton.setMinimumSize(new java.awt.Dimension(120, 40));
        accountSettingsButton.setPreferredSize(new java.awt.Dimension(120, 40));
        accountSettingsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accountSettingsButtonMouseClicked(evt);
            }
        });
        accountSettingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountSettingsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout admin2_2PanelLayout = new javax.swing.GroupLayout(admin2_2Panel);
        admin2_2Panel.setLayout(admin2_2PanelLayout);
        admin2_2PanelLayout.setHorizontalGroup(
            admin2_2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(admin2_2PanelLayout.createSequentialGroup()
                .addGroup(admin2_2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(admin2_2PanelLayout.createSequentialGroup()
                        .addGroup(admin2_2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(admin2_2PanelLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 802, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(admin2_2PanelLayout.createSequentialGroup()
                                .addGap(272, 272, 272)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 18, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, admin2_2PanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(NameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, admin2_2PanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(admin2_2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(userLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(accountTypeLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accountNumberTypeLabel1)
                    .addComponent(PhoneNumberLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(emailLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AddressLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(admin2_2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddressLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PhoneNumberLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accountTypeLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accountNumberTypeLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(196, 196, 196))
            .addGroup(admin2_2PanelLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(accountSettingsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 756, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        admin2_2PanelLayout.setVerticalGroup(
            admin2_2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(admin2_2PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(NameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(admin2_2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(admin2_2PanelLayout.createSequentialGroup()
                        .addComponent(userLabel1)
                        .addGap(14, 14, 14)
                        .addComponent(accountNumberTypeLabel1)
                        .addGap(11, 11, 11)
                        .addComponent(accountTypeLabel1))
                    .addGroup(admin2_2PanelLayout.createSequentialGroup()
                        .addComponent(userLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(accountNumberTypeLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(accountTypeLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addGroup(admin2_2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PhoneNumberLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PhoneNumberLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(admin2_2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(admin2_2PanelLayout.createSequentialGroup()
                        .addComponent(emailLabel1)
                        .addGap(11, 11, 11)
                        .addComponent(AddressLabel1))
                    .addGroup(admin2_2PanelLayout.createSequentialGroup()
                        .addComponent(emailLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AddressLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addComponent(accountSettingsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        profilePanel.add(admin2_2Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 82, -1, -1));

        closeBtnLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/close-btn.png"))); // NOI18N
        closeBtnLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBtnLabelMouseClicked(evt);
            }
        });
        profilePanel.add(closeBtnLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(profilePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(profilePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void homeBtnPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBtnPanel6MouseClicked
        Home H;
        try {
            H = new Home(accountNumber);
            setVisible(false);
            H.setVisible(true);
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(Profile.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_homeBtnPanel6MouseClicked

    private void homeBtnPanel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBtnPanel6MouseEntered
        JPanel btn= homeBtnPanel;
        isEntered(btn);
    }//GEN-LAST:event_homeBtnPanel6MouseEntered

    private void homeBtnPanel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBtnPanel6MouseExited
        JPanel btn= homeBtnPanel;
        isExited(btn);
    }//GEN-LAST:event_homeBtnPanel6MouseExited

    private void transferBtnPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transferBtnPanelMouseClicked
        Transfer TF;
        try {
            TF = new Transfer(accountNumber);
            setVisible(false);
            TF.setVisible(true);
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(Profile.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_transferBtnPanelMouseClicked

    private void transferBtnPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transferBtnPanelMouseEntered
        JPanel btn= transferBtnPanel;
        isEntered(btn);
    }//GEN-LAST:event_transferBtnPanelMouseEntered

    private void transferBtnPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transferBtnPanelMouseExited
        JPanel btn= transferBtnPanel;
        isExited(btn);
    }//GEN-LAST:event_transferBtnPanelMouseExited

    private void accountBtnPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountBtnPanelMouseClicked
        Account A;
        try {
            A = new Account(accountNumber);
            setVisible(false);
            A.setVisible(true);
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(Profile.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_accountBtnPanelMouseClicked

    private void accountBtnPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountBtnPanelMouseEntered
        JPanel btn= accountBtnPanel;
        isEntered(btn);
    }//GEN-LAST:event_accountBtnPanelMouseEntered

    private void accountBtnPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountBtnPanelMouseExited
        JPanel btn= accountBtnPanel;
        isExited(btn);
    }//GEN-LAST:event_accountBtnPanelMouseExited

    private void cardsBtnPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cardsBtnPanelMouseClicked
        Cards CD;
        try {
            CD = new Cards(accountNumber);
            setVisible(false);
            CD.setVisible(true);
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(Profile.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_cardsBtnPanelMouseClicked

    private void cardsBtnPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cardsBtnPanelMouseEntered
        JPanel btn= cardsBtnPanel;
        isEntered(btn);
    }//GEN-LAST:event_cardsBtnPanelMouseEntered

    private void cardsBtnPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cardsBtnPanelMouseExited
        JPanel btn= cardsBtnPanel;
        isExited(btn);
    }//GEN-LAST:event_cardsBtnPanelMouseExited

    private void profileBtnPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileBtnPanelMouseClicked
        /*Profile P= new Profile();
        setVisible(false);
        P.setVisible(true);
        dispose();*/
    }//GEN-LAST:event_profileBtnPanelMouseClicked

    private void profileBtnPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileBtnPanelMouseEntered
        JPanel btn= profileBtnPanel;
        isEntered(btn);
    }//GEN-LAST:event_profileBtnPanelMouseEntered

    private void profileBtnPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileBtnPanelMouseExited
        JPanel btn= profileBtnPanel;
        isExited(btn);
    }//GEN-LAST:event_profileBtnPanelMouseExited

    private void logoutBtnPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnPanelMouseClicked
        Login L= new Login();
        setVisible(false);
        L.setVisible(true);
        dispose();
    }//GEN-LAST:event_logoutBtnPanelMouseClicked

    private void logoutBtnPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnPanelMouseEntered
        JPanel btn= logoutBtnPanel;
        isEntered(btn);
    }//GEN-LAST:event_logoutBtnPanelMouseEntered

    private void logoutBtnPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnPanelMouseExited
        JPanel btn= logoutBtnPanel;
        isExited(btn);
    }//GEN-LAST:event_logoutBtnPanelMouseExited

    private void accountSettingsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountSettingsButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_accountSettingsButtonMouseClicked

    private void accountSettingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountSettingsButtonActionPerformed
        AccountSettings A=new AccountSettings(accountNumber);
        setVisible(false);
        A.setVisible(true);
        dispose();
    }//GEN-LAST:event_accountSettingsButtonActionPerformed

    private void closeBtnLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnLabelMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeBtnLabelMouseClicked
    void isEntered(JPanel btn)
    {
        btn.setBackground(new Color(0,0,204));
    }
    
    void isExited(JPanel btn)
    {
        btn.setBackground(new Color(0,0,255));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Profile("").setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Profile.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddressLabel1;
    private javax.swing.JLabel AddressLabel2;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JLabel PhoneNumberLabel1;
    private javax.swing.JLabel PhoneNumberLabel2;
    private javax.swing.JLabel accountBtnLabel;
    private javax.swing.JLabel accountBtnLabel1;
    private javax.swing.JPanel accountBtnPanel;
    private javax.swing.JLabel accountNumberTypeLabel1;
    private javax.swing.JLabel accountNumberTypeLabel2;
    private javax.swing.JButton accountSettingsButton;
    private javax.swing.JLabel accountTypeLabel1;
    private javax.swing.JLabel accountTypeLabel2;
    private javax.swing.JPanel admin2_2Panel;
    private javax.swing.JLabel cardsBtnLabel;
    private javax.swing.JLabel cardsBtnLabel1;
    private javax.swing.JPanel cardsBtnPanel;
    private javax.swing.JLabel closeBtnLabel;
    private javax.swing.JLabel emailLabel1;
    private javax.swing.JLabel emailLabel2;
    private javax.swing.JLabel headingLabel1;
    private javax.swing.JLabel homeBtnLabel;
    private javax.swing.JLabel homeBtnLabel1;
    private javax.swing.JPanel homeBtnPanel;
    private javax.swing.JPanel homeBtnPanel1;
    private javax.swing.JPanel homeBtnPanel2;
    private javax.swing.JPanel homeBtnPanel3;
    private javax.swing.JPanel homeBtnPanel4;
    private javax.swing.JPanel homeBtnPanel5;
    private javax.swing.JPanel homeBtnPanel6;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logoutBtnLabel;
    private javax.swing.JLabel logoutBtnLabel1;
    private javax.swing.JPanel logoutBtnPanel;
    private javax.swing.JLabel profileBtnLabel;
    private javax.swing.JLabel profileBtnLabel1;
    private javax.swing.JPanel profileBtnPanel;
    private javax.swing.JPanel profilePanel;
    private javax.swing.JPanel sideBarPanel;
    private javax.swing.JPanel sideBarPanel1;
    private javax.swing.JLabel transferBtnLabel;
    private javax.swing.JLabel transferBtnLabel1;
    private javax.swing.JPanel transferBtnPanel;
    private javax.swing.JLabel userLabel1;
    private javax.swing.JLabel userLabel2;
    // End of variables declaration//GEN-END:variables
}
