
import java.awt.Color;
import java.awt.Font;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hp
 */
public class Transfer extends javax.swing.JFrame {

    /**
     * Creates new form Transfer
     */
    String accountNumber;
    public Transfer(String accountNumber) throws SQLException {
        this.accountNumber=accountNumber;
        initComponents();
        transactionTable.getTableHeader().setFont(new Font("Segoe UI",Font.BOLD,16));
        transactionTable.getTableHeader().setOpaque(false);
        transactionTable.getTableHeader().setBackground(new Color(0,51,102));
        transactionTable.getTableHeader().setForeground(new Color(255,255,255));
        transactionTable.setRowHeight(25);
        Conn c=new Conn();
        String query="select * from balance where accountNumber = '"+accountNumber+"'";
        
        //c.s.executeUpdate(query);
                
        ResultSet rs = c.s.executeQuery(query);
        
        
        
        while(rs.next())
        {
            String Type=rs.getString("type");
            String DT=rs.getString("amount");
            String amount=rs.getString("dateAndTime");
            String tbData[]={Type,DT,amount};
            DefaultTableModel  tb1Model=(DefaultTableModel)transactionTable.getModel();
            tb1Model.addRow(tbData);
        }
    }

    private Transfer() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        sideBarPanel = new javax.swing.JPanel();
        homeBtnPanel = new javax.swing.JPanel();
        homeBtnLabel = new javax.swing.JLabel();
        transferBtnPanel = new javax.swing.JPanel();
        transferBtnLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        accountBtnPanel = new javax.swing.JPanel();
        accountBtnLabel = new javax.swing.JLabel();
        cardsBtnPanel = new javax.swing.JPanel();
        cardsBtnLabel = new javax.swing.JLabel();
        profileBtnPanel = new javax.swing.JPanel();
        profileBtnLabel = new javax.swing.JLabel();
        logoutBtnPanel = new javax.swing.JPanel();
        logoutBtnLabel = new javax.swing.JLabel();
        skyPayPanel = new javax.swing.JPanel();
        skyPayLabel1 = new javax.swing.JLabel();
        accountNumberLabel1 = new javax.swing.JLabel();
        enterAmountTextField = new javax.swing.JTextField();
        amountLabel1 = new javax.swing.JLabel();
        accountNumTextField3 = new javax.swing.JTextField();
        receiverAccountNumTextField = new javax.swing.JTextField();
        secureLabel = new javax.swing.JLabel();
        logoLabel = new javax.swing.JLabel();
        amountLabel = new javax.swing.JLabel();
        payNowButton = new javax.swing.JButton();
        takaLabel2 = new javax.swing.JLabel();
        backgroundLabel = new javax.swing.JLabel();
        headingLabel1 = new javax.swing.JLabel();
        payNowButton1 = new javax.swing.JButton();
        skyPayLabel2 = new javax.swing.JLabel();
        skyPayLabel3 = new javax.swing.JLabel();
        payNowButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        transactionTable = new javax.swing.JTable();
        closeBtnLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        backgroundPanel.setBackground(new java.awt.Color(255, 255, 255));
        backgroundPanel.setPreferredSize(new java.awt.Dimension(1120, 630));

        sideBarPanel.setBackground(new java.awt.Color(0, 51, 255));

        homeBtnPanel.setBackground(new java.awt.Color(0, 0, 255));
        homeBtnPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeBtnPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeBtnPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeBtnPanelMouseExited(evt);
            }
        });

        homeBtnLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        homeBtnLabel.setForeground(new java.awt.Color(255, 255, 255));
        homeBtnLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homeBtnLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/white-home.png"))); // NOI18N
        homeBtnLabel.setText(" Home");

        javax.swing.GroupLayout homeBtnPanelLayout = new javax.swing.GroupLayout(homeBtnPanel);
        homeBtnPanel.setLayout(homeBtnPanelLayout);
        homeBtnPanelLayout.setHorizontalGroup(
            homeBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeBtnPanelLayout.createSequentialGroup()
                .addComponent(homeBtnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        homeBtnPanelLayout.setVerticalGroup(
            homeBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homeBtnPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homeBtnLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addContainerGap())
        );

        transferBtnPanel.setBackground(new java.awt.Color(0, 0, 255));
        transferBtnPanel.setPreferredSize(new java.awt.Dimension(118, 65));
        transferBtnPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transferBtnPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                transferBtnPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                transferBtnPanelMouseExited(evt);
            }
        });

        transferBtnLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        transferBtnLabel.setForeground(new java.awt.Color(255, 255, 255));
        transferBtnLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        transferBtnLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/transfer-icon.png"))); // NOI18N
        transferBtnLabel.setText(" Transfer");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/white-indicate.png"))); // NOI18N

        javax.swing.GroupLayout transferBtnPanelLayout = new javax.swing.GroupLayout(transferBtnPanel);
        transferBtnPanel.setLayout(transferBtnPanelLayout);
        transferBtnPanelLayout.setHorizontalGroup(
            transferBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transferBtnPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(transferBtnLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        transferBtnPanelLayout.setVerticalGroup(
            transferBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transferBtnPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(transferBtnLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        accountBtnPanel.setBackground(new java.awt.Color(0, 0, 255));
        accountBtnPanel.setPreferredSize(new java.awt.Dimension(118, 65));
        accountBtnPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accountBtnPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                accountBtnPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                accountBtnPanelMouseExited(evt);
            }
        });

        accountBtnLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        accountBtnLabel.setForeground(new java.awt.Color(255, 255, 255));
        accountBtnLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        accountBtnLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/white-moneybag.png"))); // NOI18N
        accountBtnLabel.setText(" Account");

        javax.swing.GroupLayout accountBtnPanelLayout = new javax.swing.GroupLayout(accountBtnPanel);
        accountBtnPanel.setLayout(accountBtnPanelLayout);
        accountBtnPanelLayout.setHorizontalGroup(
            accountBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(accountBtnLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        accountBtnPanelLayout.setVerticalGroup(
            accountBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, accountBtnPanelLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(accountBtnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        cardsBtnPanel.setBackground(new java.awt.Color(0, 0, 255));
        cardsBtnPanel.setPreferredSize(new java.awt.Dimension(118, 65));
        cardsBtnPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cardsBtnPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cardsBtnPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cardsBtnPanelMouseExited(evt);
            }
        });

        cardsBtnLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        cardsBtnLabel.setForeground(new java.awt.Color(255, 255, 255));
        cardsBtnLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cardsBtnLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/white-card.png"))); // NOI18N
        cardsBtnLabel.setText(" Cards");

        javax.swing.GroupLayout cardsBtnPanelLayout = new javax.swing.GroupLayout(cardsBtnPanel);
        cardsBtnPanel.setLayout(cardsBtnPanelLayout);
        cardsBtnPanelLayout.setHorizontalGroup(
            cardsBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardsBtnPanelLayout.createSequentialGroup()
                .addComponent(cardsBtnLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        cardsBtnPanelLayout.setVerticalGroup(
            cardsBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardsBtnPanelLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(cardsBtnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        profileBtnPanel.setBackground(new java.awt.Color(0, 0, 255));
        profileBtnPanel.setPreferredSize(new java.awt.Dimension(118, 65));
        profileBtnPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileBtnPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                profileBtnPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                profileBtnPanelMouseExited(evt);
            }
        });

        profileBtnLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        profileBtnLabel.setForeground(new java.awt.Color(255, 255, 255));
        profileBtnLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        profileBtnLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/white-user-icon.png"))); // NOI18N
        profileBtnLabel.setText(" Profile");

        javax.swing.GroupLayout profileBtnPanelLayout = new javax.swing.GroupLayout(profileBtnPanel);
        profileBtnPanel.setLayout(profileBtnPanelLayout);
        profileBtnPanelLayout.setHorizontalGroup(
            profileBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profileBtnPanelLayout.createSequentialGroup()
                .addComponent(profileBtnLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        profileBtnPanelLayout.setVerticalGroup(
            profileBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profileBtnPanelLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(profileBtnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        logoutBtnPanel.setBackground(new java.awt.Color(0, 0, 255));
        logoutBtnPanel.setPreferredSize(new java.awt.Dimension(118, 65));
        logoutBtnPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutBtnPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutBtnPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutBtnPanelMouseExited(evt);
            }
        });

        logoutBtnLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        logoutBtnLabel.setForeground(new java.awt.Color(255, 255, 255));
        logoutBtnLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoutBtnLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/white-logout-logo.png"))); // NOI18N
        logoutBtnLabel.setText(" Logout");

        javax.swing.GroupLayout logoutBtnPanelLayout = new javax.swing.GroupLayout(logoutBtnPanel);
        logoutBtnPanel.setLayout(logoutBtnPanelLayout);
        logoutBtnPanelLayout.setHorizontalGroup(
            logoutBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoutBtnPanelLayout.createSequentialGroup()
                .addComponent(logoutBtnLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        logoutBtnPanelLayout.setVerticalGroup(
            logoutBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoutBtnPanelLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(logoutBtnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout sideBarPanelLayout = new javax.swing.GroupLayout(sideBarPanel);
        sideBarPanel.setLayout(sideBarPanelLayout);
        sideBarPanelLayout.setHorizontalGroup(
            sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homeBtnPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(transferBtnPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
            .addComponent(accountBtnPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
            .addComponent(cardsBtnPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
            .addComponent(profileBtnPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
            .addComponent(logoutBtnPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        sideBarPanelLayout.setVerticalGroup(
            sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarPanelLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(homeBtnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(transferBtnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(accountBtnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(cardsBtnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(profileBtnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(logoutBtnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        skyPayPanel.setBackground(new java.awt.Color(255, 255, 255));
        skyPayPanel.setForeground(new java.awt.Color(0, 51, 255));
        skyPayPanel.setPreferredSize(new java.awt.Dimension(480, 364));
        skyPayPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        skyPayLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        skyPayLabel1.setForeground(new java.awt.Color(255, 255, 255));
        skyPayLabel1.setText("Sky Pay");
        skyPayPanel.add(skyPayLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        accountNumberLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        accountNumberLabel1.setForeground(new java.awt.Color(255, 255, 255));
        accountNumberLabel1.setText("Enter Reciver Account Number");
        skyPayPanel.add(accountNumberLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, -1));

        enterAmountTextField.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        enterAmountTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        enterAmountTextField.setToolTipText("Enter Receiver Account Number");
        skyPayPanel.add(enterAmountTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 301, 34));

        amountLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        amountLabel1.setText("Enter Amount");
        skyPayPanel.add(amountLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 659, -1, -1));

        accountNumTextField3.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        accountNumTextField3.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        accountNumTextField3.setToolTipText("Enter Receiver Account Number");
        skyPayPanel.add(accountNumTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 682, 301, 33));

        receiverAccountNumTextField.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        receiverAccountNumTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        receiverAccountNumTextField.setToolTipText("Enter Receiver Account Number");
        skyPayPanel.add(receiverAccountNumTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 301, 34));

        secureLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        secureLabel.setForeground(new java.awt.Color(255, 255, 255));
        secureLabel.setText("Secure Payment");
        skyPayPanel.add(secureLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, -1, -1));

        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/white-shield.png"))); // NOI18N
        skyPayPanel.add(logoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, -1, -1));

        amountLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        amountLabel.setForeground(new java.awt.Color(255, 255, 255));
        amountLabel.setText("Enter Amount");
        skyPayPanel.add(amountLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));

        payNowButton.setBackground(new java.awt.Color(0, 0, 204));
        payNowButton.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        payNowButton.setForeground(new java.awt.Color(255, 255, 255));
        payNowButton.setText("Pay Now");
        payNowButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        payNowButton.setMaximumSize(new java.awt.Dimension(120, 40));
        payNowButton.setMinimumSize(new java.awt.Dimension(120, 40));
        payNowButton.setPreferredSize(new java.awt.Dimension(120, 40));
        payNowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payNowButtonActionPerformed(evt);
            }
        });
        skyPayPanel.add(payNowButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 150, -1));

        takaLabel2.setBackground(new java.awt.Color(0, 0, 0));
        takaLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        takaLabel2.setForeground(new java.awt.Color(255, 255, 255));
        takaLabel2.setText("$");
        skyPayPanel.add(takaLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 20, -1));

        backgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/card-xl.png"))); // NOI18N
        skyPayPanel.add(backgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 470, 360));

        headingLabel1.setBackground(new java.awt.Color(0, 0, 0));
        headingLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 3, 36)); // NOI18N
        headingLabel1.setForeground(new java.awt.Color(0, 51, 255));
        headingLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headingLabel1.setText("TRANSFER");

        payNowButton1.setBackground(new java.awt.Color(0, 51, 102));
        payNowButton1.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        payNowButton1.setForeground(new java.awt.Color(255, 255, 255));
        payNowButton1.setText("Transfer Money");
        payNowButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        payNowButton1.setMaximumSize(new java.awt.Dimension(120, 40));
        payNowButton1.setMinimumSize(new java.awt.Dimension(120, 40));
        payNowButton1.setPreferredSize(new java.awt.Dimension(120, 40));
        payNowButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payNowButton1ActionPerformed(evt);
            }
        });

        skyPayLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        skyPayLabel2.setForeground(new java.awt.Color(0, 51, 102));
        skyPayLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        skyPayLabel2.setText("Add Money From Bkash");

        skyPayLabel3.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        skyPayLabel3.setForeground(new java.awt.Color(0, 51, 102));
        skyPayLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        skyPayLabel3.setText("Transfer Money (Others Bank)");

        payNowButton2.setBackground(new java.awt.Color(0, 51, 102));
        payNowButton2.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        payNowButton2.setForeground(new java.awt.Color(255, 255, 255));
        payNowButton2.setText("Add Money");
        payNowButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        payNowButton2.setMaximumSize(new java.awt.Dimension(120, 40));
        payNowButton2.setMinimumSize(new java.awt.Dimension(120, 40));
        payNowButton2.setPreferredSize(new java.awt.Dimension(120, 40));
        payNowButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payNowButton2ActionPerformed(evt);
            }
        });

        transactionTable.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 15)); // NOI18N
        transactionTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Type", "Amount", "Date & Time"
            }
        ));
        transactionTable.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(transactionTable);

        closeBtnLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/close-btn.png"))); // NOI18N
        closeBtnLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBtnLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout backgroundPanelLayout = new javax.swing.GroupLayout(backgroundPanel);
        backgroundPanel.setLayout(backgroundPanelLayout);
        backgroundPanelLayout.setHorizontalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addComponent(sideBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addComponent(headingLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 904, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(closeBtnLabel))
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addComponent(payNowButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(payNowButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addComponent(skyPayPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addComponent(skyPayLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(skyPayLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        backgroundPanelLayout.setVerticalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sideBarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(headingLabel1))
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(closeBtnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(skyPayPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(skyPayLabel2)
                    .addComponent(skyPayLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(payNowButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(payNowButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void homeBtnPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBtnPanelMouseClicked
        Home H;
        try {
            H = new Home(accountNumber);
            setVisible(false);
            H.setVisible(true);
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(Transfer.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_homeBtnPanelMouseClicked

    private void homeBtnPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBtnPanelMouseEntered
        JPanel btn= homeBtnPanel;
        isEntered(btn);
    }//GEN-LAST:event_homeBtnPanelMouseEntered

    private void homeBtnPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBtnPanelMouseExited
        JPanel btn= homeBtnPanel;
        isExited(btn);
    }//GEN-LAST:event_homeBtnPanelMouseExited

    private void transferBtnPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transferBtnPanelMouseClicked
        /*Transfer TF= new Transfer();
        setVisible(false);
        TF.setVisible(true);
        dispose();*/
    }//GEN-LAST:event_transferBtnPanelMouseClicked

    private void transferBtnPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transferBtnPanelMouseEntered
        JPanel btn= transferBtnPanel;
        isEntered(btn);
    }//GEN-LAST:event_transferBtnPanelMouseEntered

    private void transferBtnPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transferBtnPanelMouseExited
        JPanel btn= transferBtnPanel;
        isExited(btn);
    }//GEN-LAST:event_transferBtnPanelMouseExited

    private void accountBtnPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountBtnPanelMouseClicked
        Account A;
        try {
            A = new Account(accountNumber);
            setVisible(false);
            A.setVisible(true);
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(Transfer.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_accountBtnPanelMouseClicked

    private void accountBtnPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountBtnPanelMouseEntered
        JPanel btn= accountBtnPanel;
        isEntered(btn);
    }//GEN-LAST:event_accountBtnPanelMouseEntered

    private void accountBtnPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountBtnPanelMouseExited
        JPanel btn= accountBtnPanel;
        isExited(btn);
    }//GEN-LAST:event_accountBtnPanelMouseExited

    private void cardsBtnPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cardsBtnPanelMouseClicked
        Cards CD;
        try {
            CD = new Cards(accountNumber);
            setVisible(false);
            CD.setVisible(true);
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(Transfer.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_cardsBtnPanelMouseClicked

    private void cardsBtnPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cardsBtnPanelMouseEntered
        JPanel btn= cardsBtnPanel;
        isEntered(btn);
    }//GEN-LAST:event_cardsBtnPanelMouseEntered

    private void cardsBtnPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cardsBtnPanelMouseExited
        JPanel btn= cardsBtnPanel;
        isExited(btn);
    }//GEN-LAST:event_cardsBtnPanelMouseExited

    private void profileBtnPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileBtnPanelMouseClicked
        Profile P;
        try {
            P = new Profile(accountNumber);
            setVisible(false);
            P.setVisible(true);
        dispose();
        } catch (SQLException ex) {
            Logger.getLogger(Transfer.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_profileBtnPanelMouseClicked

    private void profileBtnPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileBtnPanelMouseEntered
        JPanel btn= profileBtnPanel;
        isEntered(btn);
    }//GEN-LAST:event_profileBtnPanelMouseEntered

    private void profileBtnPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileBtnPanelMouseExited
        JPanel btn= profileBtnPanel;
        isExited(btn);
    }//GEN-LAST:event_profileBtnPanelMouseExited

    private void logoutBtnPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnPanelMouseClicked
        Login L= new Login();
        setVisible(false);
        L.setVisible(true);
        dispose();
    }//GEN-LAST:event_logoutBtnPanelMouseClicked

    private void logoutBtnPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnPanelMouseEntered
        JPanel btn= logoutBtnPanel;
        isEntered(btn);
    }//GEN-LAST:event_logoutBtnPanelMouseEntered

    private void logoutBtnPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnPanelMouseExited
        JPanel btn= logoutBtnPanel;
        isExited(btn);
    }//GEN-LAST:event_logoutBtnPanelMouseExited

    private void payNowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payNowButtonActionPerformed
        // TODO add your handling code here:
        String receiveraccountNumber=receiverAccountNumTextField.getText();
        String amount=enterAmountTextField.getText();
        String type1="Transfer";
        String type2="Deposit";
        Date dateAndTime=new Date();
        //String balance="";
        try{
            if(receiveraccountNumber.equals("")||
                amount.equals(""))
            {
                if(receiveraccountNumber.equals(""))
                {
                    JOptionPane.showMessageDialog(null,"Receiver Account Number is Requied");
                }
                if(amount.equals(""))
                {
                    JOptionPane.showMessageDialog(null,"Transfer Amount is Requied");
                }
            }else{
                Conn c=new Conn();
                String query4="select * from addApplication3 where accountNumber = '"+accountNumber+"'";
                ResultSet rs4=c.s.executeQuery(query4);

                if(rs4.next())
                {
                    String query5="select * from addApplication3 where accountNumber = '"+receiveraccountNumber+"'";
                    ResultSet rs5 = c.s.executeQuery(query5);
                    //2 resultset at a time set and operate kora jay nh
                    if(rs5.next())
                    {   String query1="insert into balance values('"+accountNumber+"', '"+dateAndTime+"', '"+type1+"', '"+amount+"')";
                        c.s.executeUpdate(query1);
                        String query2="insert into balance values('"+receiveraccountNumber+"', '"+dateAndTime+"', '"+type2+"', '"+amount+"')";
                        c.s.executeUpdate(query2);

                        JOptionPane.showMessageDialog(null,amount+" Taka Transfered Sucessfully!!!");
                        Home H= new Home(accountNumber);
                        setVisible(false);
                        H.setVisible(true);
                        dispose();

                    }else{
                        JOptionPane.showMessageDialog(null,"Incorrect Receiver Account Number");
                    }
                }else{
                    JOptionPane.showMessageDialog(null,"Incorrect Account Number");

                }
            }
        }catch(Exception e){
            System.out.println(e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_payNowButtonActionPerformed

    private void payNowButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payNowButton2ActionPerformed
        AddMoney1 AM1= new AddMoney1(accountNumber);
        setVisible(false);
        AM1.setVisible(true);
        dispose();
    }//GEN-LAST:event_payNowButton2ActionPerformed

    private void payNowButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payNowButton1ActionPerformed
       TransferOther1 T1= new TransferOther1(accountNumber);
        setVisible(false);
        T1.setVisible(true);
        dispose();
    }//GEN-LAST:event_payNowButton1ActionPerformed

    private void closeBtnLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnLabelMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeBtnLabelMouseClicked
    void isEntered(JPanel btn)
    {
        btn.setBackground(new Color(0,0,204));
    }
    
    void isExited(JPanel btn)
    {
        btn.setBackground(new Color(0,0,255));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transfer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountBtnLabel;
    private javax.swing.JPanel accountBtnPanel;
    private javax.swing.JTextField accountNumTextField3;
    private javax.swing.JLabel accountNumberLabel1;
    private javax.swing.JLabel amountLabel;
    private javax.swing.JLabel amountLabel1;
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JLabel cardsBtnLabel;
    private javax.swing.JPanel cardsBtnPanel;
    private javax.swing.JLabel closeBtnLabel;
    private javax.swing.JTextField enterAmountTextField;
    private javax.swing.JLabel headingLabel1;
    private javax.swing.JLabel homeBtnLabel;
    private javax.swing.JPanel homeBtnPanel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JLabel logoutBtnLabel;
    private javax.swing.JLabel logoutBtnLabel1;
    private javax.swing.JPanel logoutBtnPanel;
    private javax.swing.JPanel logoutBtnPanel1;
    private javax.swing.JButton payNowButton;
    private javax.swing.JButton payNowButton1;
    private javax.swing.JButton payNowButton2;
    private javax.swing.JLabel profileBtnLabel;
    private javax.swing.JPanel profileBtnPanel;
    private javax.swing.JTextField receiverAccountNumTextField;
    private javax.swing.JLabel secureLabel;
    private javax.swing.JPanel sideBarPanel;
    private javax.swing.JLabel skyPayLabel1;
    private javax.swing.JLabel skyPayLabel2;
    private javax.swing.JLabel skyPayLabel3;
    private javax.swing.JPanel skyPayPanel;
    private javax.swing.JLabel takaLabel2;
    private javax.swing.JTable transactionTable;
    private javax.swing.JLabel transferBtnLabel;
    private javax.swing.JPanel transferBtnPanel;
    // End of variables declaration//GEN-END:variables
}
